# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Japanese → Java "bridge" content: read a real coding problem stated in
# Japanese, then solve it in Java in the normal editor; plus a bank of Japanese
# technical-interview questions with model answers.
#
# exec()'d inside gen_seed.py (after japanese_defs.py). It just defines the
# JP_BRIDGE dict; gen_seed writes it to seeds/jp_bridge.json (embedded via
# include_str! and served by the `jp_bridge` command). Pure reference data —
# no SQLite / SEED_VERSION impact.
#
# Each problem's `slug` must match an existing problem in problems.json so the
# UI can open it in the solver. `vocab` is [term, reading, english] triples.
# ---------------------------------------------------------------------------

JP_BRIDGE = {
    "problems": [
        {
            "slug": "print-greeting",
            "title_ja": "あいさつを出力する",
            "statement_ja": "「Hello, World!」という文字列を1行で出力するプログラムを書いてください。",
            "io_ja": "入力: なし\n出力: Hello, World!",
            "vocab": [
                ["出力", "しゅつりょく", "output"],
                ["文字列", "もじれつ", "string"],
                ["1行", "いちぎょう", "one line"],
            ],
            "hint_ja": "System.out.println を使って文字列をそのまま出力します。",
        },
        {
            "slug": "add-two-numbers",
            "title_ja": "二つの数の和",
            "statement_ja": "2つの整数が空白区切りで1行に与えられます。その和を出力してください。",
            "io_ja": "入力: 3 5\n出力: 8",
            "vocab": [
                ["整数", "せいすう", "integer"],
                ["和", "わ", "sum"],
                ["空白区切り", "くうはくくぎり", "space-separated"],
            ],
            "hint_ja": "Scanner で2つの int を読み取り、足した結果を出力します。",
        },
        {
            "slug": "even-or-odd",
            "title_ja": "偶数か奇数か",
            "statement_ja": "整数 n が与えられます。n が偶数なら「even」、奇数なら「odd」を出力してください。",
            "io_ja": "入力: 4\n出力: even",
            "vocab": [
                ["偶数", "ぐうすう", "even number"],
                ["奇数", "きすう", "odd number"],
                ["剰余", "じょうよ", "remainder / modulo"],
            ],
            "hint_ja": "n を 2 で割った剰余（n % 2）が 0 なら偶数です。",
        },
        {
            "slug": "larger-of-two",
            "title_ja": "大きい方の数",
            "statement_ja": "2つの整数が与えられます。大きい方の数を出力してください。等しい場合はその値を出力します。",
            "io_ja": "入力: 7 3\n出力: 7",
            "vocab": [
                ["比較", "ひかく", "comparison"],
                ["条件分岐", "じょうけんぶんき", "conditional branch"],
                ["以上", "いじょう", "greater than or equal"],
            ],
            "hint_ja": "if 文で比較するか、Math.max を使います。",
        },
        {
            "slug": "sum-to-n",
            "title_ja": "1からNまでの合計",
            "statement_ja": "正の整数 N が与えられます。1 から N までのすべての整数の合計を出力してください。",
            "io_ja": "入力: 5\n出力: 15",
            "vocab": [
                ["合計", "ごうけい", "total / sum"],
                ["繰り返し", "くりかえし", "loop / iteration"],
                ["正の整数", "せいのせいすう", "positive integer"],
            ],
            "hint_ja": "for ループで 1 から N まで足すか、公式 N*(N+1)/2 を使います。",
        },
        {
            "slug": "sum-of-digits",
            "title_ja": "各桁の和",
            "statement_ja": "非負整数 n が与えられます。各桁の数字の合計を出力してください。",
            "io_ja": "入力: 1234\n出力: 10",
            "vocab": [
                ["桁", "けた", "digit"],
                ["各桁", "かくけた", "each digit"],
                ["非負", "ひふ", "non-negative"],
            ],
            "hint_ja": "n % 10 で一の位を取り出し、n /= 10 で桁を1つ減らすのを繰り返します。",
        },
        {
            "slug": "factorial",
            "title_ja": "階乗",
            "statement_ja": "非負整数 n が与えられます。n の階乗（n!）を出力してください。0! は 1 です。",
            "io_ja": "入力: 5\n出力: 120",
            "vocab": [
                ["階乗", "かいじょう", "factorial"],
                ["再帰", "さいき", "recursion"],
                ["積", "せき", "product"],
            ],
            "hint_ja": "1 から n までを掛け合わせます。結果が大きくなるので long を使うと安全です。",
        },
        {
            "slug": "array-minimum",
            "title_ja": "配列の最小値",
            "statement_ja": "1行目に要素数、2行目に整数の配列が与えられます。配列の最小値を出力してください。",
            "io_ja": "入力: 5\n3 1 4 1 5\n出力: 1",
            "vocab": [
                ["配列", "はいれつ", "array"],
                ["最小値", "さいしょうち", "minimum value"],
                ["要素数", "ようそすう", "number of elements"],
            ],
            "hint_ja": "最初の要素を仮の最小値とし、残りと比較しながら更新します。",
        },
        {
            "slug": "array-sum",
            "title_ja": "配列の合計",
            "statement_ja": "1行目に要素数 n、2行目に n 個の整数が与えられます。すべての要素の合計を出力してください。",
            "io_ja": "入力: 4\n1 2 3 4\n出力: 10",
            "vocab": [
                ["要素", "ようそ", "element"],
                ["合計", "ごうけい", "sum"],
                ["走査", "そうさ", "traverse / scan"],
            ],
            "hint_ja": "配列を一度走査して、各要素を合計に足していきます。",
        },
        {
            "slug": "reverse-string",
            "title_ja": "文字列の反転",
            "statement_ja": "文字列が1行で与えられます。文字を逆順にして出力してください。",
            "io_ja": "入力: hello\n出力: olleh",
            "vocab": [
                ["文字列", "もじれつ", "string"],
                ["反転", "はんてん", "reverse"],
                ["逆順", "ぎゃくじゅん", "reverse order"],
            ],
            "hint_ja": "StringBuilder の reverse() を使うか、末尾から1文字ずつ組み立てます。",
        },
        {
            "slug": "gcd",
            "title_ja": "最大公約数",
            "statement_ja": "2つの正の整数が与えられます。最大公約数（GCD）を出力してください。",
            "io_ja": "入力: 12 18\n出力: 6",
            "vocab": [
                ["最大公約数", "さいだいこうやくすう", "greatest common divisor"],
                ["互除法", "ごじょほう", "Euclidean algorithm"],
                ["割り切れる", "わりきれる", "divisible"],
            ],
            "hint_ja": "ユークリッドの互除法：gcd(a, b) = gcd(b, a % b) を b が 0 になるまで繰り返します。",
        },
        {
            "slug": "nth-fibonacci",
            "title_ja": "N番目のフィボナッチ数",
            "statement_ja": "整数 n が与えられます。n 番目のフィボナッチ数を出力してください（0番目は0、1番目は1）。",
            "io_ja": "入力: 7\n出力: 13",
            "vocab": [
                ["フィボナッチ数", "フィボナッチすう", "Fibonacci number"],
                ["漸化式", "ぜんかしき", "recurrence relation"],
                ["動的計画法", "どうてきけいかくほう", "dynamic programming"],
            ],
            "hint_ja": "直前の2つの値を保持しながら、ループで順に足していきます。",
        },
        # ---- DSA stage: patterns -------------------------------------------
        {
            "slug": "second-largest",
            "title_ja": "二番目に大きい値",
            "statement_ja": "整数の配列が与えられます。二番目に大きい異なる値を出力してください。異なる値が一つしかない場合は、その値を出力します。",
            "io_ja": "入力: 3 1 4 1 5\n出力: 4",
            "vocab": [
                ["配列", "はいれつ", "array"],
                ["重複", "ちょうふく", "duplicate"],
                ["境界値", "きょうかいち", "edge case"],
            ],
            "hint_ja": "最大値と二番目の値を同時に保持しながら、一度だけ走査します。",
        },
        {
            "slug": "contains-duplicate",
            "title_ja": "重複の判定",
            "statement_ja": "整数の配列が与えられます。同じ値が二回以上現れる場合は true、そうでなければ false を出力してください。",
            "io_ja": "入力: 1 2 3 1\n出力: true",
            "vocab": [
                ["重複", "ちょうふく", "duplicate"],
                ["集合", "しゅうごう", "set"],
                ["計算量", "けいさんりょう", "complexity"],
            ],
            "hint_ja": "集合に追加しながら、既に入っていれば重複です。",
        },
        {
            "slug": "two-sum-indices",
            "title_ja": "和が目標値になる二つの添字",
            "statement_ja": "整数の配列と目標値が与えられます。足して目標値になる二つの要素の添字を、1から数えて出力してください。答えはちょうど一つあり、同じ要素を二度使うことはできません。",
            "io_ja": "入力: 4\n2 7 11 15\n9\n出力: 1 2",
            "vocab": [
                ["添字", "そえじ", "index"],
                ["要素", "ようそ", "element"],
                ["探索", "たんさく", "search"],
            ],
            "hint_ja": "「目標値 - 今の値」を鍵にして、これまで見た値を記録しておきます。",
        },
        {
            "slug": "move-zeroes",
            "title_ja": "ゼロを末尾へ移す",
            "statement_ja": "整数の配列が与えられます。0 でない要素の順序を保ったまま、すべての 0 を末尾へ移した配列を出力してください。",
            "io_ja": "入力: 0 1 0 3 12\n出力: 1 3 12 0 0",
            "vocab": [
                ["配列", "はいれつ", "array"],
                ["要素", "ようそ", "element"],
                ["尺取り法", "しゃくとりほう", "two pointers"],
            ],
            "hint_ja": "書き込み位置を別に持ち、0 でない値だけを前へ詰めます。",
        },
        {
            "slug": "longest-unique-substring",
            "title_ja": "重複のない最長の部分文字列",
            "statement_ja": "文字列が与えられます。同じ文字を含まない最長の部分文字列の長さを出力してください。",
            "io_ja": "入力: abcabcbb\n出力: 3",
            "vocab": [
                ["部分文字列", "ぶぶんもじれつ", "substring"],
                ["最長", "さいちょう", "longest"],
                ["尺取り法", "しゃくとりほう", "sliding window"],
            ],
            "hint_ja": "尺取り法で区間を保ち、重複が出たら左端を進めます。",
        },
        {
            "slug": "running-sum",
            "title_ja": "累積和",
            "statement_ja": "整数の配列が与えられます。各位置までの要素の合計を並べた配列を出力してください。",
            "io_ja": "入力: 1 2 3 4\n出力: 1 3 6 10",
            "vocab": [
                ["累積和", "るいせきわ", "prefix sum"],
                ["総和", "そうわ", "summation"],
                ["走査", "そうさ", "traversal"],
            ],
            "hint_ja": "直前までの合計に今の値を足していくだけで求まります。",
        },
        # ---- DSA stage: search & sort --------------------------------------
        {
            "slug": "sort-by-frequency",
            "title_ja": "出現回数による並べ替え",
            "statement_ja": "文字列が与えられます。文字を出現回数の降順に並べ替えて出力してください。回数が同じ文字は、文字の昇順に並べます。",
            "io_ja": "入力: tree\n出力: eert",
            "vocab": [
                ["降順", "こうじゅん", "descending order"],
                ["整列", "せいれつ", "sorting"],
                ["順序付け", "じゅんじょづけ", "ordering"],
            ],
            "hint_ja": "文字ごとの個数を数えてから、回数と文字を鍵に並べ替えます。",
        },
        {
            "slug": "binary-search-first",
            "title_ja": "最初に現れる位置",
            "statement_ja": "非減少に並んだ整数の配列と目標値が与えられます。目標値が最初に現れる添字を 0 から数えて出力してください。存在しない場合は -1 を出力します。",
            "io_ja": "入力: 5\n1 2 2 2 3\n2\n出力: 1",
            "vocab": [
                ["二分探索", "にぶんたんさく", "binary search"],
                ["単調", "たんちょう", "monotonic"],
                ["添字", "そえじ", "index"],
            ],
            "hint_ja": "見つかっても止めず、より左にないかを探し続けます。",
        },
        {
            "slug": "single-number",
            "title_ja": "一つだけの数",
            "statement_ja": "整数の配列が与えられます。一つを除くすべての要素は二回現れます。一度しか現れない要素を出力してください。",
            "io_ja": "入力: 2 3 2\n出力: 3",
            "vocab": [
                ["要素", "ようそ", "element"],
                ["重複", "ちょうふく", "duplicate"],
                ["計算量", "けいさんりょう", "complexity"],
            ],
            "hint_ja": "排他的論理和は同じ値を二回適用すると打ち消し合います。",
        },
        # ---- DSA stage: structures -----------------------------------------
        {
            "slug": "valid-parentheses",
            "title_ja": "括弧の対応",
            "statement_ja": "() [] {} だけから成る文字列が与えられます。すべての括弧が正しい順序で開いて閉じているかを判定し、true か false を出力してください。",
            "io_ja": "入力: ()[]{}\n出力: true",
            "vocab": [
                ["判定", "はんてい", "determination"],
                ["対応", "たいおう", "correspondence"],
                ["境界値", "きょうかいち", "edge case"],
            ],
            "hint_ja": "開き括弧を積み上げ、閉じ括弧が来たら一番上と対応するか確かめます。",
        },
        {
            "slug": "implement-queue-stacks",
            "title_ja": "スタックで待ち行列を作る",
            "statement_ja": "先入れ先出しの待ち行列を実装してください。操作は push x、pop（取り出した値を出力）、peek（先頭を出力）、empty（true か false を出力）です。",
            "io_ja": "入力: 6\npush 1\npush 2\npeek\npop\npop\nempty\n出力: 1\n1\n2\ntrue",
            "vocab": [
                ["待ち行列", "まちぎょうれつ", "queue"],
                ["操作", "そうさ", "operation"],
                ["償却計算量", "しょうきゃくけいさんりょう", "amortized complexity"],
            ],
            "hint_ja": "入力用と出力用の二つを使い、空になったときだけ移し替えます。",
        },
        {
            "slug": "reverse-linked-list",
            "title_ja": "連結リストの反転",
            "statement_ja": "連結リストが与えられます。順序を反転した後の値を順に出力してください。",
            "io_ja": "入力: 1 2 3 4\n出力: 4 3 2 1",
            "vocab": [
                ["逆順", "ぎゃくじゅん", "reverse order"],
                ["参照型", "さんしょうがた", "reference type"],
                ["反復", "はんぷく", "iteration"],
            ],
            "hint_ja": "直前の節点を持ちながら、つなぎ替えて進みます。",
        },
        {
            "slug": "merge-two-sorted-lists",
            "title_ja": "二つの整列済みリストの併合",
            "statement_ja": "整列済みの連結リストが二つ与えられます。併合して一つの整列済みリストにし、その値を順に出力してください。",
            "io_ja": "入力: 1 2 4\n1 3 4\n出力: 1 1 2 3 4 4",
            "vocab": [
                ["整列", "せいれつ", "sorting"],
                ["昇順", "しょうじゅん", "ascending order"],
                ["番兵", "ばんぺい", "sentinel"],
            ],
            "hint_ja": "先頭に番兵を置くと、最初の節点だけを特別扱いせずに済みます。",
        },
        {
            "slug": "kth-largest-in-array",
            "title_ja": "k 番目に大きい要素",
            "statement_ja": "整数の配列と整数 k が与えられます。値の大きい方から数えて k 番目の要素を出力してください。同じ値も別々に数えます。",
            "io_ja": "入力: 3 2 1 5 6 4\n2\n出力: 5",
            "vocab": [
                ["降順", "こうじゅん", "descending order"],
                ["計算量", "けいさんりょう", "complexity"],
                ["整列", "せいれつ", "sorting"],
            ],
            "hint_ja": "大きさ k の最小ヒープを保てば、全体を整列させずに済みます。",
        },
        {
            "slug": "min-stack",
            "title_ja": "最小値を返すスタック",
            "statement_ja": "最小値を O(1) で返せるスタックを設計してください。操作は push x、pop、top（先頭を出力）、getMin（最小値を出力）です。",
            "io_ja": "入力: 6\npush 2\npush 1\ngetMin\npop\ntop\ngetMin\n出力: 1\n2\n2",
            "vocab": [
                ["設計", "せっけい", "design"],
                ["最小値", "さいしょうち", "minimum value"],
                ["不変条件", "ふへんじょうけん", "invariant"],
            ],
            "hint_ja": "各段でそこまでの最小値も一緒に積んでおきます。",
        },
        # ---- DSA stage: hierarchies ----------------------------------------
        {
            "slug": "max-depth-tree",
            "title_ja": "二分木の高さ",
            "statement_ja": "二分木が幅優先の順で与えられます。根から葉までの最も長い経路に含まれる節点の数を出力してください。",
            "io_ja": "入力: 3 9 20 null null 15 7\n出力: 3",
            "vocab": [
                ["高さ", "たかさ", "height"],
                ["根", "ね", "root"],
                ["葉", "は", "leaf"],
            ],
            "hint_ja": "左右の部分木の高さを求め、大きい方に 1 を足します。",
        },
        {
            "slug": "level-order-traversal",
            "title_ja": "階層ごとの走査",
            "statement_ja": "二分木が与えられます。各階層を上から順に、同じ階層では左から右へたどり、値を一列に出力してください。",
            "io_ja": "入力: 3 9 20 null null 15 7\n出力: 3 9 20 15 7",
            "vocab": [
                ["幅優先探索", "はばゆうせんたんさく", "breadth-first search"],
                ["待ち行列", "まちぎょうれつ", "queue"],
                ["階層", "かいそう", "level"],
            ],
            "hint_ja": "待ち行列に根を入れ、取り出しながら子を入れていきます。",
        },
        {
            "slug": "validate-bst",
            "title_ja": "二分探索木かどうかの判定",
            "statement_ja": "二分木が与えられます。すべての節点が左部分木のどの値よりも大きく、右部分木のどの値よりも小さい場合に true を、そうでなければ false を出力してください。",
            "io_ja": "入力: 5 3 8 2 4 7 9\n出力: true",
            "vocab": [
                ["二分探索木", "にぶんたんさくぎ", "binary search tree"],
                ["範囲", "はんい", "range"],
                ["再帰", "さいき", "recursion"],
            ],
            "hint_ja": "親だけでなく、各節点が取りうる値の範囲を下へ渡していきます。",
        },
        {
            "slug": "generate-subsets",
            "title_ja": "部分集合の列挙",
            "statement_ja": "重複のない整数の集合が与えられます。すべての部分集合を列挙してください。空集合は - で表し、並べる順序は問いません。",
            "io_ja": "入力: 1 2 3\n出力: - 1 2 3 1,2 1,3 2,3 1,2,3",
            "vocab": [
                ["集合", "しゅうごう", "set"],
                ["列挙", "れっきょ", "enumeration"],
                ["再帰", "さいき", "recursion"],
            ],
            "hint_ja": "各要素について「入れる」「入れない」を選びながら再帰します。",
        },
        {
            "slug": "number-of-islands",
            "title_ja": "島の数",
            "statement_ja": "0 と 1 から成る格子が与えられます。上下左右に隣接する 1 のまとまりを島と数え、島の数を出力してください。斜めは隣接とみなしません。",
            "io_ja": "入力: 4 5\n11110\n11010\n11000\n00000\n出力: 1",
            "vocab": [
                ["連結成分", "れんけつせいぶん", "connected component"],
                ["深さ優先探索", "ふかさゆうせんたんさく", "depth-first search"],
                ["隣接", "りんせつ", "adjacency"],
            ],
            "hint_ja": "未訪問の 1 を見つけるたびに島を一つ数え、そこから全体を塗りつぶします。",
        },
        {
            "slug": "course-schedule",
            "title_ja": "履修できるかどうか",
            "statement_ja": "0 から n-1 の番号が付いた n 個の科目と、先に履修すべき科目の対が与えられます。「a b」は b を a より先に履修する必要があることを表します。すべての科目を履修できるかどうかを判定してください。",
            "io_ja": "入力: 2 1\n1 0\n出力: true",
            "vocab": [
                ["位相整列", "いそうせいれつ", "topological sort"],
                ["閉路", "へいろ", "cycle"],
                ["依存関係", "いぞんかんけい", "dependencies"],
            ],
            "hint_ja": "閉路がなければ履修できます。入次数 0 の科目から順に取り除きます。",
        },
        {
            "slug": "number-of-provinces",
            "title_ja": "連結成分の数",
            "statement_ja": "0 から n-1 の番号が付いた都市と、直接つながっている都市の対が二つの配列で与えられます。直接または間接につながった都市のまとまりがいくつあるかを出力してください。",
            "io_ja": "入力: 3\n0\n1\n出力: 2",
            "vocab": [
                ["連結成分", "れんけつせいぶん", "connected component"],
                ["頂点", "ちょうてん", "vertex"],
                ["辺", "へん", "edge"],
            ],
            "hint_ja": "素集合データ構造で併合し、最後に代表元の数を数えます。",
        },
        {
            "slug": "grid-bfs-distance",
            "title_ja": "迷路の最短手数",
            "statement_ja": "H 行 W 列の格子に、. （通れる）、# （壁）、S （出発点）、G （目的地）が与えられます。上下左右に一歩進む費用を 1 として、S から G までの最短の手数を出力してください。到達できない場合は -1 を出力します。",
            "io_ja": "入力: 3 4\nS..#\n.#..\n...G\n出力: 5",
            "vocab": [
                ["最短経路", "さいたんけいろ", "shortest path"],
                ["幅優先探索", "はばゆうせんたんさく", "breadth-first search"],
                ["探索空間", "たんさくくうかん", "search space"],
            ],
            "hint_ja": "辺の重みがすべて 1 なので、幅優先探索が最短を与えます。",
        },
        # ---- DSA stage: advanced -------------------------------------------
        {
            "slug": "best-time-buy-sell",
            "title_ja": "株の売買で得られる最大の利益",
            "statement_ja": "日ごとの価格が与えられます。一度買って、その後に一度売るときの最大の利益を出力してください。利益が出ない場合は 0 を出力します。",
            "io_ja": "入力: 7 1 5 3 6 4\n出力: 5",
            "vocab": [
                ["貪欲法", "どんよくほう", "greedy algorithm"],
                ["最小値", "さいしょうち", "minimum value"],
                ["走査", "そうさ", "traversal"],
            ],
            "hint_ja": "これまでの最安値を持ちながら、今日売った場合の利益を比べます。",
        },
        {
            "slug": "merge-intervals",
            "title_ja": "区間の併合",
            "statement_ja": "開始と終了の二つの配列で区間が与えられます。重なり合う区間をすべて併合し、開始の昇順に並べて出力してください。",
            "io_ja": "入力: 1 2 8 15\n3 6 10 18\n出力: 1 6 8 10 15 18",
            "vocab": [
                ["区間", "くかん", "interval"],
                ["昇順", "しょうじゅん", "ascending order"],
                ["整列", "せいれつ", "sorting"],
            ],
            "hint_ja": "開始で整列してから、直前の区間と重なるかどうかを順に見ます。",
        },
        {
            "slug": "climbing-stairs",
            "title_ja": "階段の上り方",
            "statement_ja": "n 段の階段を、一度に 1 段または 2 段ずつ上ります。上り方が何通りあるかを出力してください。",
            "io_ja": "入力: 2\n出力: 2",
            "vocab": [
                ["漸化式", "ぜんかしき", "recurrence relation"],
                ["動的計画法", "どうてきけいかくほう", "dynamic programming"],
                ["状態遷移", "じょうたいせんい", "state transition"],
            ],
            "hint_ja": "n 段目への行き方は、n-1 段目と n-2 段目からの合計です。",
        },
        {
            "slug": "unique-paths",
            "title_ja": "経路の数",
            "statement_ja": "m 行 n 列の格子を、右か下にだけ進んで左上から右下へ移動します。異なる経路が何通りあるかを出力してください。",
            "io_ja": "入力: 3\n7\n出力: 28",
            "vocab": [
                ["動的計画法", "どうてきけいかくほう", "dynamic programming"],
                ["経路", "けいろ", "route"],
                ["状態遷移", "じょうたいせんい", "state transition"],
            ],
            "hint_ja": "各升目への経路数は、上の升目と左の升目の合計です。",
        },
        {
            "slug": "trie-insert-lookup",
            "title_ja": "木による完全一致の検索",
            "statement_ja": "n 個の単語を木に挿入し、その後 q 個の問い合わせについて、その単語がそのまま挿入されていれば YES、そうでなければ NO を出力してください。前方一致ではなく完全一致で判定します。",
            "io_ja": "入力: 3\ncar\ncard\ncat\n4\ncar\nca\ncard\ncot\n出力: YES\nNO\nYES\nNO",
            "vocab": [
                ["挿入", "そうにゅう", "insert"],
                ["探索", "たんさく", "search"],
                ["接頭辞", "せっとうじ", "prefix"],
            ],
            "hint_ja": "単語の終わりに印を付けておかないと、ca と car を区別できません。",
        },
    ],
    # Every question carries its interview STAGE as the first tag — 自己紹介,
    # コーディング, 設計 or 振り返り — followed by a topical tag. `terms` names
    # vocabulary words the answer actually leans on, and the UI links each to
    # its card; gen_seed asserts every one of them exists.
    "interview": [
        # ---- 自己紹介 -------------------------------------------------------
        {
            "q_ja": "自己紹介をお願いします。",
            "q_en": "Could you introduce yourself?",
            "a_ja": "現在はバックエンドの開発を担当しており、Javaでの実装と設計を主に行っています。直近では検索機能の応答時間の改善に取り組みました。",
            "a_en": "I currently work on backend development, mostly implementation and design in Java. Most recently I worked on improving the response time of our search feature.",
            "tags": ["自己紹介", "経歴"],
            "terms": ["担当", "設計", "応答時間", "改善"],
        },
        {
            "q_ja": "これまでのご経験を教えてください。",
            "q_en": "Tell me about your experience so far.",
            "a_ja": "三年間、Webアプリケーションの開発に携わりました。要件の整理から設計、実装、単体試験まで一通り担当しています。",
            "a_en": "I've spent three years on web application development, covering everything from gathering requirements through design, implementation and unit testing.",
            "tags": ["自己紹介", "経歴"],
            "terms": ["要件", "設計", "単体試験", "担当"],
        },
        {
            "q_ja": "得意な技術は何ですか。",
            "q_en": "What technologies are you strongest in?",
            "a_ja": "Javaと型安全な設計が得意です。総称型や不変なオブジェクトを使って、誤りが実行時ではなくコンパイル時に見つかるようにすることを心がけています。",
            "a_en": "Java, and type-safe design. I try to use generics and immutable objects so mistakes surface at compile time rather than at runtime.",
            "tags": ["自己紹介", "技術"],
            "terms": ["型安全", "総称型", "不変", "実行時"],
        },
        {
            "q_ja": "チームではどのような役割を担ってきましたか。",
            "q_en": "What role have you played on your team?",
            "a_ja": "実装に加えて、コードレビューと後輩への引き継ぎを担当してきました。進捗の共有と、詰まっている人への相談の場づくりを大事にしています。",
            "a_en": "Alongside implementation I've handled code review and onboarding. I put weight on sharing progress and making it easy for people to ask for help.",
            "tags": ["自己紹介", "チーム"],
            "terms": ["引き継ぎ", "進捗", "共有", "相談"],
        },
        {
            "q_ja": "最近学んだことは何ですか。",
            "q_en": "What have you learned recently?",
            "a_ja": "データベースの実行計画の読み方を学びました。索引が使われず全表走査になっている問い合わせを見つけて改善できました。",
            "a_en": "How to read a database execution plan. I found a query that was doing a full table scan instead of using an index, and fixed it.",
            "tags": ["自己紹介", "学習"],
            "terms": ["実行計画", "索引", "全表走査", "改善"],
        },
        {
            "q_ja": "なぜこの職種を志望されたのですか。",
            "q_en": "Why are you applying for this role?",
            "a_ja": "設計から関わり、長く使われるものを作りたいからです。目の前の不具合の対応だけでなく、根本原因まで踏み込める環境に魅力を感じています。",
            "a_en": "I want to be involved from the design stage and build things that last. I'm drawn to an environment where you can go after root causes, not just handle the defect in front of you.",
            "tags": ["自己紹介", "志望動機"],
            "terms": ["設計", "不具合", "対応", "根本原因"],
        },
        {
            "q_ja": "最後に何か質問はありますか。",
            "q_en": "Do you have any questions for us?",
            "a_ja": "はい。コードレビューはどのように進めていますか。また、仕様が途中で変わったとき、優先度の調整は誰が行いますか。",
            "a_en": "Yes — how do you run code review? And when a specification changes mid-way, who decides how priorities are adjusted?",
            "tags": ["自己紹介", "逆質問"],
            "terms": ["仕様", "優先度", "調整"],
        },
        # ---- コーディング ---------------------------------------------------
        {
            "q_ja": "このアルゴリズムの時間計算量はいくつですか？",
            "q_en": "What is the time complexity of this algorithm?",
            "a_ja": "配列を一度だけ走査するので、時間計算量は O(n) です。",
            "a_en": "We scan the array only once, so the time complexity is O(n).",
            "tags": ["コーディング", "計算量"],
            "terms": ["計算量", "配列", "走査"],
        },
        {
            "q_ja": "なぜハッシュマップを使ったのですか？",
            "q_en": "Why did you use a hash map?",
            "a_ja": "値の検索を平均 O(1) で行えるため、全体を O(n) に抑えられるからです。",
            "a_en": "It looks up values in O(1) on average, which keeps the whole solution O(n).",
            "tags": ["コーディング", "データ構造"],
            "terms": ["探索", "計算量", "写像"],
        },
        {
            "q_ja": "空間計算量はどうなりますか？",
            "q_en": "What is the space complexity?",
            "a_ja": "追加の配列を使わず、変数だけで処理するので空間計算量は O(1) です。",
            "a_en": "We use only a few variables and no extra array, so the space complexity is O(1).",
            "tags": ["コーディング", "計算量"],
            "terms": ["計算量", "配列"],
        },
        {
            "q_ja": "このコードのエッジケースは何ですか？",
            "q_en": "What are the edge cases for this code?",
            "a_ja": "空の配列、要素が1つだけの場合、負の数が含まれる場合を考慮する必要があります。",
            "a_en": "We need to consider an empty array, a single element, and negative numbers.",
            "tags": ["コーディング", "エッジケース"],
            "terms": ["境界値", "要素", "配列"],
        },
        {
            "q_ja": "計算量をさらに改善できますか？",
            "q_en": "Can you improve the complexity further?",
            "a_ja": "はい、整列の代わりに集合を使えば O(n log n) から O(n) に改善できます。",
            "a_en": "Yes — using a set instead of sorting improves it from O(n log n) to O(n).",
            "tags": ["コーディング", "最適化"],
            "terms": ["計算量", "整列", "集合"],
        },
        {
            "q_ja": "再帰と反復のどちらを選びますか？",
            "q_en": "Would you choose recursion or iteration?",
            "a_ja": "深い再帰は呼び出し履歴があふれる危険があるため、この場合は反復を選びます。",
            "a_en": "Deep recursion risks overflowing the call stack, so here I'd choose iteration.",
            "tags": ["コーディング", "再帰"],
            "terms": ["再帰", "反復", "呼び出し履歴"],
        },
        {
            "q_ja": "なぜ int ではなく long を使ったのですか？",
            "q_en": "Why did you use long instead of int?",
            "a_ja": "合計が int の範囲を超える可能性があり、桁あふれを防ぐためです。",
            "a_en": "The sum could exceed the int range, so long prevents an overflow.",
            "tags": ["コーディング", "型"],
            "terms": ["桁あふれ", "基本型", "総和"],
        },
        {
            "q_ja": "まず何から始めますか？",
            "q_en": "How do you start solving a problem?",
            "a_ja": "まず要件を確認し、入力と出力の例を整理してから、考え方を説明します。",
            "a_en": "First I confirm the requirements, work through input/output examples, then explain my approach.",
            "tags": ["コーディング", "進め方"],
            "terms": ["要件", "入力", "出力"],
        },
        {
            "q_ja": "このアルゴリズムをどうテストしますか？",
            "q_en": "How would you test this algorithm?",
            "a_ja": "通常の場合、境界値、異常な入力について単体試験を書いて確認します。",
            "a_en": "I write unit tests for the normal case, boundary values, and invalid input.",
            "tags": ["コーディング", "テスト"],
            "terms": ["単体試験", "境界値", "検証"],
        },
        {
            "q_ja": "null が渡されたらどうなりますか？",
            "q_en": "What happens if null is passed in?",
            "a_ja": "最初に null かどうかを確認し、例外を送出するか空の結果を返します。",
            "a_en": "I check for null first and either throw an exception or return an empty result.",
            "tags": ["コーディング", "例外処理"],
            "terms": ["例外", "送出", "事前条件"],
        },
        {
            "q_ja": "このメソッドはスレッドセーフですか？",
            "q_en": "Is this method thread-safe?",
            "a_ja": "共有する状態を変更せず、局所的な変数だけを使うので安全です。状態を持つ場合は排他制御が必要になります。",
            "a_en": "It doesn't modify shared state and uses only local variables, so it's safe. If it held state, it would need mutual exclusion.",
            "tags": ["コーディング", "並行処理"],
            "terms": ["排他制御", "競合状態", "不変"],
        },
        {
            "q_ja": "単体試験では何を確かめますか。",
            "q_en": "What do you actually check in a unit test?",
            "a_ja": "事後条件が満たされることと、境界値で壊れないことを確かめます。網羅率は目安にしますが、目標にはしません。",
            "a_en": "That the postcondition holds and that it doesn't break at the boundaries. I treat coverage as a signal, not a target.",
            "tags": ["コーディング", "テスト"],
            "terms": ["事後条件", "境界値", "網羅率"],
        },
        {
            "q_ja": "この処理を並行化できますか。",
            "q_en": "Could this work be parallelized?",
            "a_ja": "各要素の処理が互いに独立していれば並列に実行できます。共有する状態があるなら、まず不変にできないかを考えます。",
            "a_en": "If the per-element work is independent, yes. If there's shared state, my first question is whether it can be made immutable instead.",
            "tags": ["コーディング", "並行処理"],
            "terms": ["並列", "並行処理", "不変", "競合状態"],
        },
        {
            "q_ja": "不変なオブジェクトにすると何が良いのですか。",
            "q_en": "What do you gain by making an object immutable?",
            "a_ja": "生成後に状態が変わらないため、複数のスレッドから安全に共有でき、不変条件が壊れる心配もありません。",
            "a_en": "Its state can't change after construction, so it can be shared safely between threads and its invariants can't be broken.",
            "tags": ["コーディング", "設計"],
            "terms": ["不変", "不変条件", "並行処理"],
        },
        {
            "q_ja": "制約から解法をどう決めますか。",
            "q_en": "How do the constraints tell you which solution to write?",
            "a_ja": "制約は必要な計算量をそのまま示しています。N が 20 程度なら全探索で足り、10 の 5 乗なら O(n log n) までに収める必要があります。",
            "a_en": "The constraints tell you the complexity you need. If N is around 20, brute force is enough; at 10^5 you have to stay within O(n log n).",
            "tags": ["コーディング", "進め方"],
            "terms": ["制約", "計算量", "全探索", "探索空間"],
        },
        # ---- 設計 -----------------------------------------------------------
        {
            "q_ja": "このシステムをどう設計しますか。",
            "q_en": "How would you design this system?",
            "a_ja": "まず要件と制約を確認します。読み取りと書き込みのどちらが多いか、どこまでの一貫性が必要かによって設計が変わるためです。",
            "a_en": "I'd start from the requirements and constraints — whether it's read-heavy or write-heavy, and how much consistency is actually required, change the design entirely.",
            "tags": ["設計", "進め方"],
            "terms": ["設計", "要件", "制約", "一貫性"],
        },
        {
            "q_ja": "データベースの表をどう設計しますか。",
            "q_en": "How do you design the database tables?",
            "a_ja": "同じ事実が一度だけ保存されるように正規化し、参照整合性を保ちます。速度が問題になってから、測ったうえで崩すことを検討します。",
            "a_en": "Normalize so each fact is stored once, and keep referential integrity. If speed becomes a problem, I'd denormalize — but only after measuring.",
            "tags": ["設計", "データベース"],
            "terms": ["正規化", "参照整合性", "表", "列"],
        },
        {
            "q_ja": "索引はどの列に張りますか。",
            "q_en": "Which columns would you index?",
            "a_ja": "検索条件と結合の条件に使う列です。ただし索引は書き込みを遅くするので、実行計画で効果を確認してから追加します。",
            "a_en": "The columns used in search and join conditions — but an index slows writes down, so I confirm the benefit in the execution plan before adding one.",
            "tags": ["設計", "データベース"],
            "terms": ["索引", "結合", "実行計画", "更新"],
        },
        {
            "q_ja": "認証と認可はどう分けて考えますか。",
            "q_en": "How do you separate authentication from authorization?",
            "a_ja": "認証は誰であるかを確かめること、認可は何を許すかを決めることです。順序も別で、認証を通った後に認可を判断します。",
            "a_en": "Authentication establishes who you are; authorization decides what you may do. They're also ordered — authorization is judged after authentication passes.",
            "tags": ["設計", "セキュリティ"],
            "terms": ["認証", "認可", "権限", "資格情報"],
        },
        {
            "q_ja": "負荷が増えたらどう対応しますか。",
            "q_en": "How would you handle increased load?",
            "a_ja": "まずどこが遅いのかを測ります。そのうえで負荷分散を行うか、重い問い合わせを改善するかを決めます。推測で増やすことはしません。",
            "a_en": "Measure where it's actually slow first. Then decide between load balancing and fixing the expensive queries — I wouldn't scale on a guess.",
            "tags": ["設計", "性能"],
            "terms": ["負荷", "負荷分散", "応答時間", "実行計画"],
        },
        {
            "q_ja": "再試行を安全に行うにはどうしますか。",
            "q_en": "How do you make a retry safe?",
            "a_ja": "処理を冪等にします。二回実行しても結果が変わらなければ、再試行しても二重に反映される心配がありません。",
            "a_en": "Make the operation idempotent. If running it twice leaves the same result, a retry can't double-apply.",
            "tags": ["設計", "信頼性"],
            "terms": ["再試行", "冪等", "通信", "取引"],
        },
        {
            "q_ja": "一貫性と応答速度のどちらを優先しますか。",
            "q_en": "Would you prioritize consistency or speed?",
            "a_ja": "扱うデータによります。残高のように誤れないものは一貫性を優先し、表示の件数のような値なら多少遅れても構いません。",
            "a_en": "It depends on the data. Something like a balance must be consistent; something like a displayed count can lag a little.",
            "tags": ["設計", "トレードオフ"],
            "terms": ["一貫性", "取引", "待ち時間", "永続化"],
        },
        {
            "q_ja": "応答時間をどう改善しますか。",
            "q_en": "How would you improve response time?",
            "a_ja": "まず測って、どこに時間がかかっているかを特定します。多くの場合は問い合わせか通信で、索引の追加や取得回数の削減が効きます。",
            "a_en": "Measure first and find where the time actually goes. Usually it's a query or a network round trip — adding an index or cutting the number of fetches helps most.",
            "tags": ["設計", "性能"],
            "terms": ["応答時間", "取得", "索引", "通信"],
        },
        {
            "q_ja": "この設計の弱点はどこですか。",
            "q_en": "Where is this design weak?",
            "a_ja": "単一障害点があることです。この部分が止まると全体が止まるため、冗長化か、停止しても縮退して動く仕組みが必要です。",
            "a_en": "It has a single point of failure — if that part stops, everything stops. It needs redundancy, or a way to degrade rather than halt.",
            "tags": ["設計", "トレードオフ"],
            "terms": ["負荷分散", "再試行", "課題"],
        },
        {
            "q_ja": "秘密の情報はどう扱いますか。",
            "q_en": "How do you handle secrets?",
            "a_ja": "資格情報はソースコードに書かず、設定として外から与えます。保存する場合は暗号化し、通信も暗号化された経路を使います。",
            "a_en": "Credentials never go in source code — they're supplied from outside as configuration. Stored secrets are encrypted, and the transport is encrypted too.",
            "tags": ["設計", "セキュリティ"],
            "terms": ["資格情報", "暗号化", "通信", "脆弱性"],
        },
        # ---- 振り返り -------------------------------------------------------
        {
            "q_ja": "詰まったときはどうしますか？",
            "q_en": "What do you do when you get stuck?",
            "a_ja": "簡単な例を手で試し、問題を小さく分解して考え直します。それでも進まなければ早めに相談します。",
            "a_en": "I work a small example by hand and break the problem down. If that doesn't move it, I ask for help early.",
            "tags": ["振り返り", "進め方"],
            "terms": ["分割統治", "相談", "課題"],
        },
        {
            "q_ja": "失敗した経験を教えてください。",
            "q_en": "Tell me about a time you failed.",
            "a_ja": "確認が不十分なまま反映し、不具合を出したことがあります。根本原因を調べ、再発防止として試験を追加しました。",
            "a_en": "I once shipped without checking enough and caused a defect. I investigated the root cause and added a test as recurrence prevention.",
            "tags": ["振り返り", "失敗"],
            "terms": ["不具合", "根本原因", "再発防止", "検証"],
        },
        {
            "q_ja": "意見が対立したときはどうしますか。",
            "q_en": "How do you handle disagreement?",
            "a_ja": "まず相手の前提を確認します。多くの場合、見ている制約が違うだけなので、事実を揃えてから合意を取ります。",
            "a_en": "I check the other person's assumptions first. Usually we're looking at different constraints, so I line up the facts and then reach agreement.",
            "tags": ["振り返り", "チーム"],
            "terms": ["制約", "合意", "調整", "相談"],
        },
        {
            "q_ja": "締め切りに間に合わないと分かったらどうしますか。",
            "q_en": "What do you do if you realize you'll miss a deadline?",
            "a_ja": "分かった時点ですぐ報告します。そのうえで優先度を見直し、何を落とすか、何を後回しにするかを調整します。",
            "a_en": "Report it the moment I know. Then revisit priorities and agree what gets dropped or deferred.",
            "tags": ["振り返り", "進め方"],
            "terms": ["締め切り", "報告", "優先度", "調整"],
        },
        {
            "q_ja": "コードレビューで指摘を受けたらどうしますか。",
            "q_en": "How do you respond to code review feedback?",
            "a_ja": "指摘の意図を確認してから直します。同じ指摘が繰り返されるようなら、個別の修正ではなく手順の改善を提案します。",
            "a_en": "I make sure I understand the intent before changing anything. If the same comment keeps recurring, I propose a process improvement rather than another one-off fix.",
            "tags": ["振り返り", "チーム"],
            "terms": ["差分", "対応", "改善", "合意"],
        },
        {
            "q_ja": "不具合の根本原因をどう特定しますか。",
            "q_en": "How do you find the root cause of a defect?",
            "a_ja": "再現する最小の手順を作ることから始めます。再現できれば、差分を見て原因の範囲を狭めていけます。",
            "a_en": "I start by building the smallest reproduction. Once it reproduces, the diff narrows down where the cause can be.",
            "tags": ["振り返り", "調査"],
            "terms": ["根本原因", "不具合", "差分", "範囲"],
        },
        {
            "q_ja": "進捗はどのように共有していますか。",
            "q_en": "How do you share progress?",
            "a_ja": "終わったことより、残っている課題と見通しを伝えるようにしています。遅れは早いほど調整しやすいためです。",
            "a_en": "I report the remaining issues and the outlook rather than just what's done — a delay is far easier to absorb the earlier it's known.",
            "tags": ["振り返り", "チーム"],
            "terms": ["進捗", "共有", "課題", "報告"],
        },
        {
            "q_ja": "引き継ぎで気をつけていることは何ですか。",
            "q_en": "What do you pay attention to in a handover?",
            "a_ja": "手順だけでなく、なぜそうしたかを残します。仕様の背景が分からないと、後任は変更してよいかを判断できないためです。",
            "a_en": "I record why, not just how. Without the reasoning behind a specification, the next person can't judge whether a change is safe.",
            "tags": ["振り返り", "チーム"],
            "terms": ["引き継ぎ", "仕様", "議事録", "担当"],
        },
    ],
}
