# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Japanese core vocabulary — the FIRST section of the Learn tab's 日本語 view.
#
# This file is exec()'d inside gen_seed.py's namespace (right after
# japanese_bridge.py). It defines JP_VOCAB, written to seeds/jp_vocab.json and
# served by the `jp_vocab` command.
#
# WHAT'S DIFFERENT FROM japanese_defs.py:
#   Those are glossary *tables* grouped into sets. This is a flat list of
#   individual words, each with a TAG (java / problems / typescript) the menu
#   filters on, and each opening as its own flashcard with a description in
#   BOTH English and Japanese, the reading, and an example sentence.
#
# RULES (asserted below, so a bad edit fails the build instead of the UI):
#   * No katakana in the term. Loanwords like クラス or ソート are their own
#     reading and teach nothing about kanji; this list is for the words you
#     can't sound out. (Katakana inside sentences and descriptions is fine.)
#   * The reading is hiragana only.
#   * The example sentence contains the term verbatim, so the flashcard can
#     highlight it.
#   * Terms and ids are unique; every word has a known tag.
#
# Row format:
#   (term, reading, romaji, meaning, desc_en, desc_ja, example_ja, example_en)
# ---------------------------------------------------------------------------

import re as _jpv_re
import unicodedata as _jpv_ud

JP_VOCAB_TAGS = [
    {"id": "java", "label": "Java", "label_ja": "Java"},
    {"id": "problems", "label": "Coding problems", "label_ja": "コーディング問題"},
    {"id": "typescript", "label": "TypeScript", "label_ja": "TypeScript"},
    {"id": "sql", "label": "SQL", "label_ja": "データベース"},
    {"id": "web", "label": "Web", "label_ja": "Webと通信"},
]

_JPV_JAVA = [
    ("継承", "けいしょう", "keishō", "inheritance",
     "A class taking on the fields and methods of another class with extends, so the subclass can reuse and extend its parent's behavior.",
     "extendsを使って、あるクラスが別のクラスのフィールドやメソッドを引き継ぐ仕組みです。子クラスは親クラスの機能を再利用できます。",
     "DogクラスはAnimalクラスを継承しています。", "The Dog class inherits from the Animal class."),
    ("抽象化", "ちゅうしょうか", "chūshōka", "abstraction",
     "Hiding the details of how something works and exposing only what callers need — in Java, through abstract classes and interfaces.",
     "内部の細かい仕組みを隠し、利用者に必要な部分だけを見せる考え方です。Javaでは抽象クラスやインターフェースで表現します。",
     "共通の処理をインターフェースに抽象化しました。", "I abstracted the shared logic into an interface."),
    ("多態性", "たたいせい", "tataisei", "polymorphism",
     "One reference type standing for many concrete classes, with the method that actually runs chosen at runtime by the object's real class.",
     "同じ型の変数で異なるクラスのオブジェクトを扱い、実行時に実際のクラスのメソッドが呼ばれる性質です。",
     "多態性のおかげで、Shape型のリストに円も四角形も入れられます。", "Thanks to polymorphism, a list of Shape can hold both circles and squares."),
    ("情報隠蔽", "じょうほういんぺい", "jōhō inpei", "information hiding (encapsulation)",
     "Keeping an object's fields private and allowing access only through methods, so its internal state can't be broken from outside.",
     "フィールドをprivateにして、メソッド経由でしか操作できないようにすることです。外部から内部状態を壊されるのを防ぎます。",
     "情報隠蔽のために、フィールドはすべてprivateにしてください。", "For information hiding, please make all fields private."),
    ("修飾子", "しゅうしょくし", "shūshokushi", "modifier",
     "A keyword placed before a declaration that changes its meaning or visibility, such as public, private, static or final.",
     "宣言の前に付けて、意味や公開範囲を変えるキーワードです。public、private、static、finalなどがあります。",
     "このメソッドにはアクセス修飾子が付いていません。", "This method has no access modifier."),
    ("静的", "せいてき", "seiteki", "static",
     "Belonging to the class itself rather than to any one instance; a static member is shared and can be used without creating an object.",
     "インスタンスではなくクラスそのものに属することです。静的メンバーはオブジェクトを作らなくても使えます。",
     "mainメソッドは静的メソッドなので、インスタンスなしで呼び出せます。", "main is a static method, so it can be called without an instance."),
    ("参照型", "さんしょうがた", "sanshōgata", "reference type",
     "A type whose variables hold a reference to an object rather than the value itself — classes, arrays, interfaces and String.",
     "変数に値そのものではなく、オブジェクトへの参照を持つ型です。クラス、配列、インターフェース、Stringなどが該当します。",
     "Stringは参照型なので、比較にはequalsを使います。", "String is a reference type, so use equals to compare."),
    ("基本型", "きほんがた", "kihongata", "primitive type",
     "One of Java's eight built-in value types (int, long, double, boolean, char, byte, short, float) that store the value directly.",
     "int、double、booleanなど、値を直接保持するJavaの8つの組み込み型です。",
     "intは基本型なので、nullを代入できません。", "int is a primitive type, so you can't assign null to it."),
    ("例外", "れいがい", "reigai", "exception",
     "An object representing an error or unusual condition that interrupts the normal flow of a program until something handles it.",
     "エラーや想定外の状況を表すオブジェクトです。処理されるまでプログラムの通常の流れを中断します。",
     "配列の範囲外にアクセスすると例外が発生します。", "Accessing outside an array's bounds raises an exception."),
    ("検査例外", "けんされいがい", "kensa reigai", "checked exception",
     "An exception the compiler forces you to deal with — either catch it or declare it with throws. IOException is the classic example.",
     "コンパイラが処理を強制する例外です。catchするか、throwsで宣言しなければなりません。IOExceptionが代表例です。",
     "ファイル読み込みは検査例外を投げるので、try-catchが必要です。", "Reading a file throws a checked exception, so you need try-catch."),
    ("送出", "そうしゅつ", "sōshutsu", "throwing (an exception)",
     "Raising an exception with the throw keyword so that control jumps to the nearest matching catch block.",
     "throwキーワードで例外を発生させることです。制御は最も近い対応するcatchブロックへ移ります。",
     "引数が負の数ならIllegalArgumentExceptionを送出します。", "If the argument is negative, it throws IllegalArgumentException."),
    ("捕捉", "ほそく", "hosoku", "catching (an exception)",
     "Intercepting a thrown exception in a catch block so the program can recover instead of crashing.",
     "発生した例外をcatchブロックで受け取ることです。プログラムを停止させずに回復できます。",
     "NumberFormatExceptionを捕捉して、エラーメッセージを表示します。", "We catch the NumberFormatException and show an error message."),
    ("宣言", "せんげん", "sengen", "declaration",
     "Introducing a name — a variable, method or class — together with its type, before it is used.",
     "変数、メソッド、クラスなどの名前を、その型と一緒にコードに導入することです。",
     "変数は使う前に宣言する必要があります。", "A variable must be declared before it is used."),
    ("初期化", "しょきか", "shokika", "initialization",
     "Giving a variable or object its first value. Local variables in Java must be initialized before they are read.",
     "変数やオブジェクトに最初の値を与えることです。Javaのローカル変数は、読み取る前に初期化が必要です。",
     "カウンターを0で初期化してからループを始めます。", "Initialize the counter to 0, then start the loop."),
    ("生成", "せいせい", "seisei", "creation (instantiation)",
     "Making a new object from a class with the new keyword, which allocates memory and runs a constructor.",
     "newキーワードでクラスから新しいオブジェクトを作ることです。メモリが確保され、コンストラクタが実行されます。",
     "newでArrayListのインスタンスを生成します。", "Create an ArrayList instance with new."),
    ("総称型", "そうしょうがた", "sōshōgata", "generic type (generics)",
     "A class or interface with type parameters, like List<T>, so the same code works for many types while staying type-safe.",
     "List<T>のように型パラメータを持つクラスやインターフェースです。型安全を保ったまま、さまざまな型で同じコードを使えます。",
     "総称型を使えば、キャストなしで要素を取り出せます。", "With generics you can take elements out without casting."),
    ("型消去", "かたしょうきょ", "kata shōkyo", "type erasure",
     "The compiler removing generic type arguments after checking them, so at runtime a List<String> is just a List.",
     "コンパイラが総称型の型引数をチェックした後に取り除くことです。実行時にはList<String>も単なるListになります。",
     "型消去があるため、実行時にList<Integer>かどうかは判定できません。", "Because of type erasure, you can't check at runtime whether something is a List<Integer>."),
    ("不変", "ふへん", "fuhen", "immutable",
     "Unable to change after creation. String is immutable; methods that seem to modify it actually return a new object.",
     "生成後に状態を変更できないことです。Stringは不変なので、変更しているように見えるメソッドも新しいオブジェクトを返します。",
     "不変オブジェクトはスレッド間で安全に共有できます。", "Immutable objects can be shared safely between threads."),
    ("同期", "どうき", "dōki", "synchronization",
     "Coordinating threads so only one at a time runs a critical section, typically with synchronized or a Lock.",
     "複数のスレッドのうち、一度に一つだけが重要な処理を実行するよう調整することです。synchronizedやLockを使います。",
     "このメソッドは同期されているので、同時に一つのスレッドしか入れません。", "This method is synchronized, so only one thread can enter at a time."),
    ("排他制御", "はいたせいぎょ", "haita seigyo", "mutual exclusion",
     "Guaranteeing that a shared resource is used by only one thread at a time so concurrent updates don't corrupt it.",
     "共有資源を同時に一つのスレッドだけが使えるように保証することです。同時更新によるデータの破損を防ぎます。",
     "残高の更新には排他制御が必要です。", "Updating the balance requires mutual exclusion."),
    ("並行処理", "へいこうしょり", "heikō shori", "concurrency",
     "Structuring a program so several tasks make progress during overlapping time periods, e.g. with threads or an ExecutorService.",
     "複数のタスクが重なり合う時間の中で進むようにプログラムを組むことです。スレッドやExecutorServiceを使います。",
     "並行処理でダウンロードを高速化しました。", "We sped up the downloads with concurrency."),
    ("競合状態", "きょうごうじょうたい", "kyōgō jōtai", "race condition",
     "A bug where the result depends on the unpredictable timing of threads, such as two threads incrementing the same counter.",
     "スレッドの実行タイミングによって結果が変わってしまう不具合です。二つのスレッドが同時にカウンターを増やす場合などに起きます。",
     "count++はアトミックではないため、競合状態が発生します。", "count++ isn't atomic, so a race condition occurs."),
    ("匿名", "とくめい", "tokumei", "anonymous",
     "Having no name — an anonymous class is defined and instantiated in one expression, and is often replaced today by a lambda.",
     "名前を持たないことです。匿名クラスは一つの式で定義と生成を同時に行い、現在はラムダ式で置き換えられることが多いです。",
     "匿名クラスの代わりにラムダ式で書けます。", "You can write it as a lambda instead of an anonymous class."),
    ("再定義", "さいていぎ", "saiteigi", "overriding",
     "A subclass providing its own version of a method inherited from its parent, with the same name and parameters (@Override).",
     "子クラスが親クラスから継承したメソッドを、同じ名前と引数で書き直すことです。@Overrideを付けます。",
     "toStringメソッドを再定義して、中身が読みやすく表示されるようにしました。", "I overrode toString so the contents print readably."),
    ("多重定義", "たじゅうていぎ", "tajū teigi", "overloading",
     "Defining several methods with the same name but different parameter lists; the compiler picks one from the arguments.",
     "同じ名前で引数の型や数が異なるメソッドを複数定義することです。どれが呼ばれるかはコンパイル時に引数で決まります。",
     "printメソッドはintとString用に多重定義されています。", "The print method is overloaded for int and String."),
    ("型変換", "かたへんかん", "kata henkan", "type conversion (casting)",
     "Turning a value of one type into another, either automatically (widening) or explicitly with a cast like (int) 3.7.",
     "ある型の値を別の型に変えることです。自動で行われる場合と、(int) 3.7のように明示的にキャストする場合があります。",
     "doubleからintへの型変換で小数点以下が切り捨てられます。", "Converting from double to int truncates the decimal part."),
    ("列挙型", "れっきょがた", "rekkyogata", "enum type",
     "A type with a fixed set of named constants, declared with enum, such as the days of the week or order statuses.",
     "enumで宣言する、決まった名前付き定数の集まりを表す型です。曜日や注文の状態などに使います。",
     "信号の色を列挙型で表しました。", "I represented the traffic-light colors with an enum."),
    ("注釈", "ちゅうしゃく", "chūshaku", "annotation",
     "Metadata attached to code with @, such as @Override or @Deprecated, read by the compiler, tools or frameworks.",
     "@Overrideや@Deprecatedのように、@でコードに付けるメタデータです。コンパイラやツール、フレームワークが読み取ります。",
     "@Override注釈を付けると、再定義のミスをコンパイラが見つけてくれます。", "With the @Override annotation, the compiler catches overriding mistakes for you."),
    ("定数", "ていすう", "teisū", "constant",
     "A value that never changes after it is set, usually declared static final with an UPPER_SNAKE_CASE name.",
     "一度設定したら変わらない値です。通常はstatic finalで宣言し、大文字のスネークケースで名前を付けます。",
     "最大人数をMAX_USERSという定数にしました。", "I made the maximum number of users a constant called MAX_USERS."),
    ("同一性", "どういつせい", "dōitsusei", "identity",
     "Whether two references point to the very same object, tested with ==, as opposed to equality of contents tested with equals.",
     "二つの参照がまったく同じオブジェクトを指しているかどうかです。==で判定し、内容の等しさを調べるequalsとは区別します。",
     "==は同一性を比べ、equalsは等価性を比べます。", "== compares identity; equals compares equality."),
    ("仮引数", "かりひきすう", "kari hikisū", "parameter (formal parameter)",
     "The variable named in a method's declaration that receives a value when the method is called.",
     "メソッドの宣言に書かれ、呼び出し時に値を受け取る変数です。",
     "add(int a, int b)のaとbが仮引数です。", "In add(int a, int b), a and b are the parameters."),
    ("実引数", "じつひきすう", "jitsu hikisū", "argument (actual argument)",
     "The actual value passed in when a method is called, which is copied into the corresponding parameter.",
     "メソッドを呼び出すときに実際に渡す値です。対応する仮引数にコピーされます。",
     "add(2, 3)の2と3が実引数です。", "In add(2, 3), 2 and 3 are the arguments."),
    ("中間操作", "ちゅうかんそうさ", "chūkan sōsa", "intermediate operation",
     "A Stream operation like filter or map that returns another Stream and does no work until a terminal operation runs.",
     "filterやmapのように新しいStreamを返すStream操作です。終端操作が実行されるまで処理は行われません。",
     "mapは中間操作なので、それだけでは何も実行されません。", "map is an intermediate operation, so on its own nothing runs."),
    ("終端操作", "しゅうたんそうさ", "shūtan sōsa", "terminal operation",
     "A Stream operation like collect, count or forEach that produces a result and actually runs the whole pipeline.",
     "collect、count、forEachのように結果を生み出し、パイプライン全体を実際に実行するStream操作です。",
     "collectなどの終端操作を呼ぶと、ストリームが処理されます。", "Calling a terminal operation such as collect processes the stream."),
]

_JPV_PROBLEMS = [
    ("配列", "はいれつ", "hairetsu", "array",
     "A fixed-length sequence of elements of the same type stored side by side, accessed by index in constant time.",
     "同じ型の要素を連続して並べた固定長のデータ構造です。添字を使って定数時間でアクセスできます。",
     "整数の配列が与えられます。", "You are given an array of integers."),
    ("添字", "そえじ", "soeji", "index (subscript)",
     "The position number used to access an element, starting from 0 in Java and TypeScript.",
     "要素にアクセスするための位置を表す番号です。JavaやTypeScriptでは0から始まります。",
     "添字が配列の長さ以上になると範囲外です。", "An index at or beyond the array's length is out of bounds."),
    ("要素", "ようそ", "yōso", "element",
     "A single item stored in an array, list, set or other collection.",
     "配列やリスト、集合などに格納されている一つひとつの値です。",
     "配列の中で最大の要素を返してください。", "Return the largest element in the array."),
    ("探索", "たんさく", "tansaku", "search",
     "Looking through data to find a target value, or a state that satisfies a condition.",
     "データの中から目的の値や、条件を満たす状態を見つけることです。",
     "目的の値が見つかるまで探索を続けます。", "Keep searching until the target value is found."),
    ("二分探索", "にぶんたんさく", "nibun tansaku", "binary search",
     "Searching a sorted range by repeatedly halving it, comparing the middle element with the target — O(log n).",
     "整列済みの範囲を、中央の要素と比べながら半分ずつ絞っていく探索です。計算量はO(log n)です。",
     "配列は整列されているので、二分探索が使えます。", "The array is sorted, so binary search can be used."),
    ("整列", "せいれつ", "seiretsu", "sorting",
     "Rearranging elements into order, ascending or descending — the textbook word alongside the loanword ソート.",
     "要素を昇順や降順などの順番に並べ替えることです。「ソート」とも言います。",
     "まず配列を整列してから重複を取り除きます。", "First sort the array, then remove the duplicates."),
    ("昇順", "しょうじゅん", "shōjun", "ascending order",
     "Ordered from smallest to largest (1, 2, 3 or A to Z).",
     "小さいものから大きいものへ並んだ順番です（1, 2, 3やAからZ）。",
     "結果を昇順で出力してください。", "Output the results in ascending order."),
    ("降順", "こうじゅん", "kōjun", "descending order",
     "Ordered from largest to smallest (3, 2, 1 or Z to A).",
     "大きいものから小さいものへ並んだ順番です（3, 2, 1やZからA）。",
     "点数の降順に並べ替えます。", "Sort in descending order of score."),
    ("計算量", "けいさんりょう", "keisanryō", "computational complexity",
     "How the time or memory an algorithm needs grows with the input size, written in Big-O notation such as O(n log n).",
     "入力サイズが大きくなるにつれて、アルゴリズムに必要な時間やメモリがどう増えるかを表すものです。O(n log n)のように書きます。",
     "この解法の時間計算量はO(n)です。", "This solution's time complexity is O(n)."),
    ("再帰", "さいき", "saiki", "recursion",
     "A function solving a problem by calling itself on a smaller version of it, stopping at a base case.",
     "関数が自分自身を、より小さな問題に対して呼び出して解く方法です。基底ケースで停止します。",
     "階乗は再帰で簡単に書けます。", "Factorial is easy to write with recursion."),
    ("動的計画法", "どうてきけいかくほう", "dōteki keikakuhō", "dynamic programming",
     "Solving a problem by breaking it into overlapping subproblems and storing each answer so it is computed only once.",
     "問題を重なり合う部分問題に分け、それぞれの答えを記録して一度だけ計算する手法です。",
     "動的計画法を使えば、指数時間の解法がO(n²)になります。", "With dynamic programming, an exponential-time solution becomes O(n²)."),
    ("貪欲法", "どんよくほう", "don'yokuhō", "greedy algorithm",
     "Building a solution by always taking the choice that looks best right now — correct only for problems with the right structure.",
     "その時点で最も良く見える選択を毎回行って解を作る手法です。問題の性質によっては正しい答えになりません。",
     "区間スケジューリングは貪欲法で解けます。", "Interval scheduling can be solved with a greedy algorithm."),
    ("全探索", "ぜんたんさく", "zentansaku", "brute force (exhaustive search)",
     "Trying every possible candidate and checking each one — simple and correct, but often too slow for large inputs.",
     "考えられる候補をすべて試して確かめる方法です。単純で確実ですが、入力が大きいと遅すぎることがあります。",
     "制約が小さいので全探索で間に合います。", "The constraints are small, so brute force is fast enough."),
    ("幅優先探索", "はばゆうせんたんさく", "haba yūsen tansaku", "breadth-first search (BFS)",
     "Exploring a graph level by level with a queue, which finds the shortest path when every edge has the same cost.",
     "キューを使って、グラフを近い順に一層ずつ調べる探索です。辺の重みがすべて同じなら最短経路が求まります。",
     "迷路の最短手数は幅優先探索で求めます。", "Find the fewest moves through a maze with breadth-first search."),
    ("深さ優先探索", "ふかさゆうせんたんさく", "fukasa yūsen tansaku", "depth-first search (DFS)",
     "Exploring a graph by going as deep as possible along one path before backtracking, using recursion or a stack.",
     "一つの道をできるだけ深く進んでから戻る探索です。再帰やスタックを使って実装します。",
     "連結成分の数を深さ優先探索で数えます。", "Count the connected components with depth-first search."),
    ("木", "き", "ki", "tree",
     "A connected graph with no cycles, usually drawn with the root at the top and children below.",
     "閉路のない連結なグラフです。通常は根を上に、子を下に描きます。",
     "二分木の高さを求めてください。", "Find the height of the binary tree."),
    ("根", "ね", "ne", "root (of a tree)",
     "The single top node of a rooted tree — the one node that has no parent.",
     "根付き木の一番上にある、親を持たない唯一の節点です。",
     "根から葉までの最長の経路を求めます。", "Find the longest path from the root to a leaf."),
    ("頂点", "ちょうてん", "chōten", "vertex (node)",
     "One of the points in a graph that edges connect.",
     "グラフで、辺によって結ばれる点のことです。",
     "頂点の数はN、辺の数はMです。", "There are N vertices and M edges."),
    ("辺", "へん", "hen", "edge",
     "A connection between two vertices in a graph, which may have a direction or a weight.",
     "グラフの二つの頂点を結ぶつながりです。向きや重みを持つことがあります。",
     "各辺には重みが付いています。", "Each edge has a weight."),
    ("隣接", "りんせつ", "rinsetsu", "adjacency (adjacent)",
     "Two vertices being directly connected by an edge; an adjacency list stores each vertex's neighbors.",
     "二つの頂点が辺で直接つながっていることです。隣接リストは各頂点の隣を記録します。",
     "グラフを隣接リストで表現します。", "Represent the graph with an adjacency list."),
    ("最短経路", "さいたんけいろ", "saitan keiro", "shortest path",
     "The route between two vertices with the fewest edges or the smallest total weight, found with BFS or Dijkstra's algorithm.",
     "二つの頂点の間で、辺の数や重みの合計が最小になる道のりです。幅優先探索やダイクストラ法で求めます。",
     "始点から各頂点への最短経路の長さを出力してください。", "Output the shortest-path length from the start to each vertex."),
    ("部分文字列", "ぶぶんもじれつ", "bubun mojiretsu", "substring",
     "A contiguous run of characters taken from inside a string.",
     "文字列の中から連続して取り出した一部分です。",
     "同じ文字を含まない最長の部分文字列を求めてください。", "Find the longest substring without repeating characters."),
    ("部分配列", "ぶぶんはいれつ", "bubun hairetsu", "subarray",
     "A contiguous run of elements from an array — unlike a subsequence, the elements must be next to each other.",
     "配列の中の連続した要素の並びです。部分列と違い、要素は隣り合っていなければなりません。",
     "和が最大になる部分配列を見つけてください。", "Find the subarray with the largest sum."),
    ("累積和", "るいせきわ", "ruisekiwa", "prefix sum",
     "An array where each position holds the total of all elements up to it, so any range sum can be answered in O(1).",
     "各位置にそこまでの要素の合計を記録した配列です。任意の区間の和をO(1)で求められます。",
     "累積和を前計算しておけば、区間の和がすぐに分かります。", "If you precompute prefix sums, range sums are instant."),
    ("尺取り法", "しゃくとりほう", "shakutorihō", "two pointers (sliding window)",
     "Advancing a left and a right pointer over an array to maintain a window — the usual Japanese competitive-programming name for the technique.",
     "左端と右端の二つのポインタを前に進めながら区間を管理する手法です。競技プログラミングでよく使われる名前です。",
     "尺取り法を使うとO(n)で解けます。", "Using two pointers, it can be solved in O(n)."),
    ("入力", "にゅうりょく", "nyūryoku", "input",
     "The data a program receives; in a problem statement, the section describing the format read from standard input.",
     "プログラムが受け取るデータです。問題文では、標準入力から読み込む形式を説明する部分を指します。",
     "入力は一行目に整数Nが与えられます。", "In the input, an integer N is given on the first line."),
    ("出力", "しゅつりょく", "shutsuryoku", "output",
     "The result a program produces; in a problem statement, the exact format your answer must be printed in.",
     "プログラムが生み出す結果です。問題文では、答えを表示する正確な形式を指します。",
     "答えを一行で出力してください。", "Output the answer on one line."),
    ("制約", "せいやく", "seiyaku", "constraints",
     "The limits on input sizes and values stated in a problem, which tell you how fast your solution needs to be.",
     "問題に書かれた入力の大きさや値の範囲です。解法にどれくらいの速さが必要かの手がかりになります。",
     "制約はN ≤ 10⁵なので、O(n²)では間に合いません。", "The constraint is N ≤ 10⁵, so O(n²) is too slow."),
    ("境界値", "きょうかいち", "kyōkaichi", "boundary value (edge case)",
     "An input at the very edge of what is allowed — empty, zero, one element, or the maximum — where bugs most often hide.",
     "空、0、要素が一つ、最大値など、許される範囲のぎりぎりの入力です。不具合が最も起きやすいところです。",
     "空の配列などの境界値もテストしてください。", "Please also test boundary values such as an empty array."),
    ("重複", "ちょうふく", "chōfuku", "duplicate",
     "The same value appearing more than once; problems often ask you to detect, count or remove duplicates.",
     "同じ値が二回以上現れることです。重複を見つける、数える、取り除くといった問題がよく出ます。",
     "配列に重複する要素があればtrueを返してください。", "Return true if the array contains any duplicate elements."),
    ("回文", "かいぶん", "kaibun", "palindrome",
     "A string that reads the same forwards and backwards, like \"level\" or \"しんぶんし\".",
     "前から読んでも後ろから読んでも同じになる文字列です。「level」や「しんぶんし」などがあります。",
     "与えられた文字列が回文かどうか判定してください。", "Determine whether the given string is a palindrome."),
    ("順列", "じゅんれつ", "junretsu", "permutation",
     "One particular ordering of a set of items; n distinct items have n! permutations.",
     "いくつかのものを一列に並べた、ある一つの並べ方です。異なるn個のものにはn!通りの順列があります。",
     "1からNまでのすべての順列を列挙してください。", "List all permutations of 1 to N."),
    ("余り", "あまり", "amari", "remainder (modulo)",
     "What is left over after integer division, computed with %; answers are often required modulo 10⁹+7.",
     "整数の割り算で割り切れずに残る数です。%で計算します。答えを10⁹+7で割った余りを求める問題もよくあります。",
     "答えを1,000,000,007で割った余りを出力してください。", "Output the answer modulo 1,000,000,007."),
]

_JPV_TYPESCRIPT = [
    ("型注釈", "かたちゅうしゃく", "kata chūshaku", "type annotation",
     "Writing a type explicitly after a name with a colon, as in let count: number = 0.",
     "let count: number = 0のように、名前の後ろにコロンを付けて型を明示的に書くことです。",
     "関数の引数には型注釈を付けましょう。", "Let's add type annotations to function parameters."),
    ("型推論", "かたすいろん", "kata suiron", "type inference",
     "The compiler working out a type on its own from the value or context, so you don't have to annotate everything.",
     "値や文脈からコンパイラが自動的に型を判断することです。すべてに型注釈を書く必要はありません。",
     "let x = 5と書くと、型推論でxはnumber型になります。", "Write let x = 5 and type inference makes x a number."),
    ("型安全", "かたあんぜん", "kata anzen", "type safety",
     "A guarantee that values are only used in ways their types allow, so whole classes of bugs are caught before the code runs.",
     "値がその型で許された方法でしか使われないことの保証です。多くの不具合を実行前に見つけられます。",
     "anyを使うと型安全が失われます。", "Using any gives up type safety."),
    ("型検査", "かたけんさ", "kata kensa", "type checking",
     "Verifying that every expression is used consistently with its type; tsc does this at compile time.",
     "すべての式が型に合った使われ方をしているか確かめることです。tscがコンパイル時に行います。",
     "tsc --noEmitで型検査だけを実行します。", "Run only the type check with tsc --noEmit."),
    ("静的型付け", "せいてきかたづけ", "seiteki katazuke", "static typing",
     "Types being checked before the program runs, as in TypeScript and Java, rather than while it runs.",
     "プログラムの実行前に型をチェックする方式です。TypeScriptやJavaが該当します。",
     "TypeScriptはJavaScriptに静的型付けを加えた言語です。", "TypeScript is JavaScript with static typing added."),
    ("動的型付け", "どうてきかたづけ", "dōteki katazuke", "dynamic typing",
     "Types being attached to values and checked only while the program runs, as in plain JavaScript or Python.",
     "型が値に結び付き、実行中にだけチェックされる方式です。JavaScriptやPythonが該当します。",
     "JavaScriptは動的型付けなので、実行するまで型の誤りに気づきません。", "JavaScript is dynamically typed, so you don't notice type mistakes until it runs."),
    ("構造的型付け", "こうぞうてきかたづけ", "kōzōteki katazuke", "structural typing",
     "Two types being compatible when they have the same shape, regardless of their names — how TypeScript compares types.",
     "名前に関係なく、同じ形（プロパティの構成）を持っていれば互換とみなす方式です。TypeScriptはこの方式で型を比較します。",
     "構造的型付けなので、同じプロパティを持つオブジェクトなら代入できます。", "Because of structural typing, any object with the same properties can be assigned."),
    ("公称型", "こうしょうがた", "kōshōgata", "nominal typing",
     "Types being compatible only when they share the same declared name, as in Java; TypeScript imitates it with branded types.",
     "宣言された名前が同じ場合にだけ互換とみなす方式です。Javaが該当し、TypeScriptではブランド型で真似します。",
     "Javaは公称型なので、同じ形のクラスでも別の型として扱われます。", "Java uses nominal typing, so classes with the same shape are still different types."),
    ("合併型", "がっぺいがた", "gappeigata", "union type",
     "A type that can be any one of several types, written with |, as in string | number.",
     "string | numberのように|で書き、いくつかの型のうちどれか一つになれる型です。「ユニオン型」とも言います。",
     "IDは文字列か数値の合併型にしました。", "I made the ID a union type of string or number."),
    ("交差型", "こうさがた", "kōsagata", "intersection type",
     "A type that has all the members of several types at once, written with &, as in A & B.",
     "A & Bのように&で書き、複数の型のメンバーをすべて併せ持つ型です。",
     "交差型を使ってUserとTimestampsを一つにまとめます。", "Use an intersection type to combine User and Timestamps."),
    ("部分型", "ぶぶんがた", "bubungata", "subtype",
     "A type that can be used wherever another type is expected, because it has at least everything that type requires.",
     "別の型に必要なものをすべて持っているため、その型が期待される場所で使える型です。",
     "{ name: string; age: number }は{ name: string }の部分型です。", "{ name: string; age: number } is a subtype of { name: string }."),
    ("互換性", "ごかんせい", "gokansei", "compatibility (assignability)",
     "Whether a value of one type may be assigned to another; the compiler reports an error when the types aren't compatible.",
     "ある型の値を別の型に代入できるかどうかです。互換性がなければコンパイラがエラーを出します。",
     "型に互換性がないため、代入でエラーになりました。", "The types aren't compatible, so the assignment is an error."),
    ("絞り込み", "しぼりこみ", "shiborikomi", "narrowing",
     "The compiler refining a broad type to a more specific one inside a branch, after a check like typeof or in.",
     "typeofやinなどのチェックの後、分岐の中で広い型をより具体的な型にすることです。",
     "typeofで型を絞り込み、文字列の場合だけtoUpperCaseを呼びます。", "Narrow the type with typeof, and call toUpperCase only for strings."),
    ("型述語", "かたじゅつご", "kata jutsugo", "type predicate",
     "A return type of the form value is Type, telling the compiler the argument's type whenever the function returns true.",
     "value is Typeという形の戻り値の型です。関数がtrueを返したとき、引数の型をコンパイラに伝えます。",
     "isFish(pet): pet is Fishは型述語を使った関数です。", "isFish(pet): pet is Fish is a function that uses a type predicate."),
    ("網羅性", "もうらせい", "mōrasei", "exhaustiveness",
     "Every possible case of a union being handled; assigning the leftover value to never makes the compiler check it.",
     "合併型のすべての場合を処理していることです。残りの値をnever型に代入すると、コンパイラが確認してくれます。",
     "neverを使ってswitch文の網羅性をチェックします。", "Use never to check that the switch statement is exhaustive."),
    ("判別可能", "はんべつかのう", "hanbetsu kanō", "discriminated (union)",
     "Describes a union whose members share a literal tag property, like kind, so checking that property narrows to one member.",
     "kindのような共通のリテラル型プロパティを持つ合併型のことです。そのプロパティを調べると一つの型に絞り込めます。",
     "kindプロパティを持つ判別可能な合併型で図形を表します。", "Represent shapes with a discriminated union that has a kind property."),
    ("条件型", "じょうけんがた", "jōkengata", "conditional type",
     "A type that chooses between two types based on a test, written T extends U ? X : Y.",
     "T extends U ? X : Yと書き、条件によって二つの型のどちらかを選ぶ型です。",
     "条件型を使って、配列なら要素の型を取り出します。", "Use a conditional type to extract the element type when it's an array."),
    ("型引数", "かたひきすう", "kata hikisū", "type argument",
     "The concrete type supplied to a generic, as in Array<string> or useState<number>(0).",
     "Array<string>やuseState<number>(0)のように、総称型に渡す具体的な型です。",
     "型引数を省略すると、TypeScriptが推論します。", "If you leave out the type argument, TypeScript infers it."),
    ("型表明", "かたひょうめい", "kata hyōmei", "type assertion",
     "Telling the compiler to treat a value as a specific type with as — it overrides checking and can hide real mistakes.",
     "asを使って、値を特定の型として扱うようコンパイラに伝えることです。型検査を上書きするため、誤りを隠すことがあります。",
     "型表明は最後の手段にしてください。", "Please treat type assertions as a last resort."),
    ("読み取り専用", "よみとりせんよう", "yomitori sen'yō", "read-only",
     "A property or array that can't be reassigned after creation, marked with readonly or ReadonlyArray.",
     "readonlyやReadonlyArrayで指定する、生成後に書き換えられないプロパティや配列です。",
     "idプロパティは読み取り専用なので変更できません。", "The id property is read-only, so it can't be changed."),
    ("省略可能", "しょうりゃくかのう", "shōryaku kanō", "optional",
     "A property or parameter that may be left out, marked with ?, whose type then includes undefined.",
     "?を付けて指定する、省略してもよいプロパティや引数です。型にはundefinedが含まれます。",
     "emailは省略可能なプロパティです。", "email is an optional property."),
    ("未定義", "みていぎ", "miteigi", "undefined",
     "The state of having no value assigned yet; in TypeScript, the value and type undefined.",
     "値がまだ設定されていない状態です。TypeScriptではundefinedという値と型で表します。",
     "存在しないキーにアクセスすると未定義になります。", "Accessing a key that doesn't exist gives undefined."),
    ("厳格", "げんかく", "genkaku", "strict",
     "Stricter compiler checking, turned on with \"strict\": true in tsconfig, which enables null checks and forbids implicit any.",
     "tsconfigで\"strict\": trueにすると有効になる、より厳しい型チェックです。nullチェックや暗黙のanyの禁止などが含まれます。",
     "新しいプロジェクトでは厳格モードを有効にしましょう。", "Let's turn on strict mode in new projects."),
    ("非同期", "ひどうき", "hidōki", "asynchronous",
     "Work that finishes later without blocking the rest of the program, handled with Promises and async/await.",
     "他の処理を止めずに、後で完了する処理のことです。Promiseやasync/awaitで扱います。",
     "fetchは非同期に実行されます。", "fetch runs asynchronously."),
    ("待機", "たいき", "taiki", "waiting (await)",
     "Pausing an async function until a Promise settles, with the await keyword, without blocking the thread.",
     "awaitキーワードで、Promiseが完了するまで非同期関数の実行を一時停止することです。スレッドはブロックされません。",
     "awaitでレスポンスを待機してから画面に表示します。", "Await the response, then show it on screen."),
    ("並列", "へいれつ", "heiretsu", "parallel",
     "Several tasks running at the same time; Promise.all starts async work together instead of one after another.",
     "複数の処理を同時に進めることです。Promise.allを使うと、非同期処理を順番ではなく一緒に開始できます。",
     "Promise.allで三つのリクエストを並列に送ります。", "Send three requests in parallel with Promise.all."),
    ("分割代入", "ぶんかつだいにゅう", "bunkatsu dainyū", "destructuring assignment",
     "Unpacking the properties of an object or the items of an array into separate variables, as in const { id, name } = user.",
     "const { id, name } = userのように、オブジェクトのプロパティや配列の要素を個別の変数に取り出すことです。",
     "分割代入でpropsから必要な値だけを取り出します。", "Use destructuring to pull just the values you need out of props."),
    ("展開構文", "てんかいこうぶん", "tenkai kōbun", "spread syntax",
     "Using ... to expand an array or object into individual elements or properties, as in [...a, ...b].",
     "[...a, ...b]のように...を使って、配列やオブジェクトを個々の要素やプロパティに展開する構文です。",
     "展開構文を使って、元のオブジェクトを変えずにコピーを作ります。", "Use spread syntax to make a copy without changing the original object."),
    ("残余引数", "ざんよひきすう", "zan'yo hikisū", "rest parameters",
     "A final parameter written ...args that gathers any number of remaining arguments into an array.",
     "...argsのように最後の引数に書き、残りの引数をすべて配列にまとめるものです。",
     "残余引数を使えば、いくつでも数値を受け取れます。", "With rest parameters, you can accept any number of numbers."),
    ("既定値", "きていち", "kiteichi", "default value",
     "The value a parameter or property takes when none is supplied, as in function greet(name = \"world\").",
     "値が渡されなかったときに使われる値です。function greet(name = \"world\")のように書きます。",
     "pageの既定値は1にしました。", "I set page's default value to 1."),
    ("名前空間", "なまえくうかん", "namae kūkan", "namespace",
     "A named scope that groups related declarations to avoid name collisions; modern TypeScript mostly uses ES modules instead.",
     "関連する宣言をまとめて名前の衝突を避けるための範囲です。現在のTypeScriptでは主にESモジュールが使われます。",
     "名前空間が違えば、同じ名前の関数を定義できます。", "In different namespaces, you can define functions with the same name."),
    ("依存関係", "いぞんかんけい", "izon kankei", "dependencies",
     "The packages a project needs, listed in package.json under dependencies and devDependencies.",
     "プロジェクトが必要とするパッケージのことです。package.jsonのdependenciesとdevDependenciesに書かれます。",
     "npm installで依存関係をインストールします。", "Install the dependencies with npm install."),
    ("実行時", "じっこうじ", "jikkōji", "runtime",
     "While the program is actually running. TypeScript's types are erased by then, so runtime checks need real JavaScript code.",
     "プログラムが実際に動いている間のことです。TypeScriptの型はその時点で消えているため、実行時のチェックにはJavaScriptのコードが必要です。",
     "型は実行時には存在しません。", "Types don't exist at runtime."),
]

_JPV_SQL = [
    ("結合", "けつごう", "ketsugō", "join",
     "Combining rows from two tables by matching a column they have in common — the operation most SQL questions are really about.",
     "共通する列の値を手がかりに、二つの表の行を組み合わせる操作です。SQLの問題の多くはこれが中心になります。",
     "顧客表と注文表を顧客IDで結合します。", "We join the customer table and the order table on the customer ID."),
    ("内部結合", "ないぶけつごう", "naibu ketsugō", "inner join",
     "A join that keeps only the rows matching on both sides, dropping anything with no partner.",
     "両方の表で条件に一致した行だけを残す結合です。相手のない行は取り除かれます。",
     "内部結合では、注文のない顧客は結果に現れません。", "With an inner join, customers with no orders don't appear in the result."),
    ("外部結合", "がいぶけつごう", "gaibu ketsugō", "outer join",
     "A join that keeps rows from one side even when nothing matches, filling the missing columns with NULL.",
     "一致する行がなくても片方の表の行を残す結合です。足りない列はNULLで埋められます。",
     "外部結合を使えば、注文のない顧客も一覧に残ります。", "With an outer join, customers with no orders stay in the list."),
    ("集計", "しゅうけい", "shūkei", "aggregation",
     "Reducing many rows to one summary value — a count, a total, an average — usually per group.",
     "多くの行を、件数や合計、平均といった一つの値にまとめることです。普通はグループごとに行います。",
     "部署ごとに給与を集計します。", "We aggregate salaries by department."),
    ("集約関数", "しゅうやくかんすう", "shūyaku kansū", "aggregate function",
     "A function such as COUNT, SUM or AVG that takes a group of rows and returns a single value.",
     "COUNTやSUM、AVGのように、行のグループを受け取って一つの値を返す関数です。",
     "COUNTは最もよく使う集約関数です。", "COUNT is the most commonly used aggregate function."),
    ("副問い合わせ", "ふくといあわせ", "fuku toiawase", "subquery",
     "A query written inside another query, whose result the outer query uses as a value, a list or a table.",
     "別の問い合わせの中に書く問い合わせです。その結果を外側が値や一覧、表として使います。",
     "平均より高い給与を探すには副問い合わせが便利です。", "A subquery is handy for finding salaries above the average."),
    ("索引", "さくいん", "sakuin", "index",
     "A separate structure the database keeps so it can find rows by a column's value without scanning the whole table.",
     "列の値から行を素早く見つけるために、データベースが別に持つ仕組みです。表全体を調べずに済みます。",
     "検索が遅いので、その列に索引を作りました。", "The search was slow, so I created an index on that column."),
    ("正規化", "せいきか", "seikika", "normalization",
     "Splitting data across tables so each fact is stored exactly once, which removes the update anomalies duplication causes.",
     "同じ事実が一度だけ保存されるように、データを複数の表に分ける設計です。重複による更新の矛盾を防げます。",
     "住所を別の表に分けて正規化しました。", "I normalized it by moving the address into its own table."),
    ("一貫性", "いっかんせい", "ikkansei", "consistency",
     "The guarantee that a transaction moves the database from one valid state to another, never leaving it half-updated.",
     "取引の前後でデータベースが常に正しい状態であることの保証です。途中の状態が残ることはありません。",
     "取引によってデータの一貫性が保たれます。", "A transaction keeps the data consistent."),
    ("取引", "とりひき", "torihiki", "transaction",
     "A group of statements that either all take effect or none do, so a failure part-way through leaves nothing behind.",
     "まとめて全部成功するか、全部なかったことになるかのどちらかになる処理の単位です。途中で失敗しても中途半端な結果は残りません。",
     "送金は一つの取引として実行します。", "A transfer runs as a single transaction."),
    ("行", "ぎょう", "gyō", "row",
     "One record in a table — a single set of values, one per column.",
     "表の中の一件のデータです。各列に一つずつ値を持ちます。",
     "この表には千件の行があります。", "This table has a thousand rows."),
    ("列", "れつ", "retsu", "column",
     "One named field of a table, with a type, holding the same kind of value for every row.",
     "表の中の名前と型を持つ項目です。どの行でも同じ種類の値が入ります。",
     "名前を保存する列を追加しました。", "I added a column to store the name."),
    ("表", "ひょう", "hyō", "table",
     "The basic container of a relational database: named columns, and any number of rows.",
     "関係データベースの基本的な入れ物です。名前の付いた列と、任意の数の行から成ります。",
     "利用者の情報は別の表に保存します。", "We store the user information in a separate table."),
    ("抽出", "ちゅうしゅつ", "chūshutsu", "extraction (SELECT)",
     "Taking just the rows and columns you want out of a table — what a SELECT statement does.",
     "表から必要な行と列だけを取り出すことです。SELECT文が行う処理を指します。",
     "条件に合う行だけを抽出します。", "We extract only the rows matching the condition."),
    ("挿入", "そうにゅう", "sōnyū", "insert",
     "Adding a new row to a table, with INSERT.",
     "INSERTで表に新しい行を追加することです。",
     "新しい利用者を表に挿入します。", "We insert the new user into the table."),
    ("削除", "さくじょ", "sakujo", "delete",
     "Removing rows from a table with DELETE — usually with a WHERE clause, since without one it removes them all.",
     "DELETEで表から行を取り除くことです。WHEREを付けないとすべての行が消えるので注意が必要です。",
     "古いデータを削除してください。", "Please delete the old data."),
    ("更新", "こうしん", "kōshin", "update",
     "Changing the values in rows that already exist, with UPDATE.",
     "UPDATEで既にある行の値を変更することです。",
     "在庫の数を更新します。", "We update the stock count."),
    ("並べ替え", "ならべかえ", "narabekae", "ordering (ORDER BY)",
     "Putting the result rows in a stated order; without it a database is free to return them in any order at all.",
     "結果の行を指定した順番に並べることです。指定しなければ、どの順で返ってくるかは決まっていません。",
     "日付の新しい順に並べ替えます。", "We order them by date, newest first."),
    ("件数", "けんすう", "kensū", "row count",
     "How many rows something produced — the answer COUNT gives.",
     "行がいくつあるかという数です。COUNTが返す値を指します。",
     "条件に合う件数を数えます。", "We count how many rows match the condition."),
    ("合計", "ごうけい", "gōkei", "total (SUM)",
     "The sum of a numeric column across the rows of a group.",
     "グループの中で、数値の列を足し合わせた値です。",
     "月ごとの売上の合計を求めます。", "We find the total sales per month."),
    ("平均", "へいきん", "heikin", "average (AVG)",
     "The mean of a numeric column — the total divided by the number of rows counted.",
     "数値の列の平均値です。合計を行数で割った値になります。",
     "平均の点数を計算します。", "We calculate the average score."),
    ("最大値", "さいだいち", "saidaichi", "maximum value (MAX)",
     "The largest value in a column across a group of rows.",
     "グループの中で列の値が最も大きいものです。",
     "各部署の給与の最大値を求めます。", "We find the maximum salary in each department."),
    ("最小値", "さいしょうち", "saishōchi", "minimum value (MIN)",
     "The smallest value in a column across a group of rows.",
     "グループの中で列の値が最も小さいものです。",
     "最小値と最大値の両方を出力します。", "We output both the minimum and the maximum value."),
    ("実行計画", "じっこうけいかく", "jikkō keikaku", "execution plan",
     "The steps the database decided to take to answer a query — the first thing to read when a query is slow.",
     "問い合わせに答えるためにデータベースが選んだ手順です。遅い問い合わせを調べるとき最初に見ます。",
     "実行計画を見ると、索引が使われていませんでした。", "Looking at the execution plan, the index wasn't being used."),
    ("一意制約", "いちいせいやく", "ichii seiyaku", "unique constraint",
     "A rule that no two rows may share a value in a column, which the database itself enforces.",
     "ある列の値が二つの行で重複してはならないという規則です。データベース自身が守らせます。",
     "メールアドレスの列に一意制約を付けます。", "We put a unique constraint on the email column."),
]

_JPV_WEB = [
    ("認証", "にんしょう", "ninshō", "authentication",
     "Establishing who a user is — checking a password, a token or a key. Distinct from deciding what they may do.",
     "利用者が誰であるかを確かめることです。パスワードやトークンを検査します。何ができるかを決める認可とは別の話です。",
     "ログイン画面で利用者の認証を行います。", "We authenticate the user on the login screen."),
    ("認可", "にんか", "ninka", "authorization",
     "Deciding what an already-identified user is allowed to do. Authentication comes first; this is the separate second question.",
     "誰であるかが分かった利用者に、何を許すかを決めることです。認証の後に来る別の判断です。",
     "認証は通りましたが、認可されていない操作です。", "They authenticated fine, but this operation isn't authorized."),
    ("要求", "ようきゅう", "yōkyū", "request",
     "What a client sends to a server: a method, a path, headers and sometimes a body.",
     "クライアントがサーバーへ送るものです。メソッド、パス、ヘッダー、場合によっては本文から成ります。",
     "サーバーに要求を送ります。", "We send a request to the server."),
    ("応答", "おうとう", "ōtō", "response",
     "What the server sends back: a status code, headers and usually a body.",
     "サーバーが返すものです。状態コードとヘッダー、多くの場合は本文から成ります。",
     "サーバーからの応答を待ちます。", "We wait for the server's response."),
    ("通信", "つうしん", "tsūshin", "communication",
     "Data moving between two machines over a network.",
     "ネットワークを通じて機械の間でデータをやり取りすることです。",
     "サーバーと通信します。", "We communicate with the server."),
    ("永続化", "えいぞくか", "eizokuka", "persistence",
     "Writing state somewhere it survives the process ending — a database or a file, rather than memory.",
     "処理が終わっても残る場所に状態を保存することです。メモリではなくデータベースやファイルに書きます。",
     "入力された内容をデータベースに永続化します。", "We persist the entered content to the database."),
    ("権限", "けんげん", "kengen", "permission",
     "A specific right granted to a user or role — to read a file, to delete a record.",
     "利用者や役割に与えられる個別の権利です。ファイルを読む、記録を消すといった単位で与えます。",
     "管理者の権限が必要です。", "Admin permission is required."),
    ("状態", "じょうたい", "jōtai", "state",
     "The data a component or a system is currently holding, which changes over time and drives what is shown.",
     "部品やシステムがその時点で持っているデータです。時間とともに変わり、表示の内容を決めます。",
     "コンポーネントの状態を管理します。", "We manage the component's state."),
    ("取得", "しゅとく", "shutoku", "fetch / get",
     "Asking another system for data and receiving it back.",
     "別のシステムにデータを求めて受け取ることです。",
     "APIからデータを取得します。", "We fetch data from the API."),
    ("表示", "ひょうじ", "hyōji", "display",
     "Putting something on screen where the user can see it.",
     "利用者が見えるように画面に出すことです。",
     "結果を画面に表示します。", "We display the result on the screen."),
    ("描画", "びょうが", "byōga", "render",
     "The act of turning state and markup into what is actually drawn on screen.",
     "状態やマークアップを、実際に画面に描かれるものへ変える処理です。",
     "状態が変わると画面が描画されます。", "When the state changes, the screen is rendered."),
    ("端末", "たんまつ", "tanmatsu", "terminal",
     "The text console you type commands into — and, in other contexts, a user's device.",
     "コマンドを入力する文字の画面です。文脈によっては利用者の機器そのものを指すこともあります。",
     "端末でコマンドを実行します。", "We run commands in the terminal."),
    ("経路", "けいろ", "keiro", "route",
     "The path part of a URL, and the rule that maps it to the code handling it.",
     "URLのパスの部分と、それを担当する処理に結び付ける規則のことです。",
     "新しい経路を追加して画面を増やします。", "We add a new route to add another screen."),
    ("見出し", "みだし", "midashi", "heading",
     "A title marking the start of a section, which on the web also gives a page its outline for screen readers.",
     "節の始まりを示す題名です。Webでは読み上げソフトのための構造にもなります。",
     "各節に見出しを付けてください。", "Please put a heading on each section."),
    ("階層", "かいそう", "kaisō", "hierarchy",
     "Structure in which items contain other items — nested components, nested routes, a tree of elements.",
     "要素が別の要素を含む入れ子の構造です。部品や経路、要素の木がこれにあたります。",
     "コンポーネントの階層が深くなりすぎました。", "The component hierarchy got too deep."),
    ("遷移", "せんい", "sen'i", "transition (navigation)",
     "Moving from one screen or state to another.",
     "ある画面や状態から別の画面や状態へ移ることです。",
     "ボタンを押すと次の画面に遷移します。", "Pressing the button navigates to the next screen."),
    ("識別子", "しきべつし", "shikibetsushi", "identifier",
     "A value that names one thing uniquely — an id on a record, on an element, or in a URL.",
     "一つのものを他と区別して指し示す値です。記録や要素、URLに付ける識別のための値です。",
     "各要素に一意の識別子を付けます。", "We give each element a unique identifier."),
    ("資格情報", "しかくじょうほう", "shikaku jōhō", "credentials",
     "The secrets proving who you are — a password, a token, a key. Never to be written into source code.",
     "本人であることを示す秘密の情報です。パスワードやトークン、鍵などが該当し、ソースコードに書いてはいけません。",
     "資格情報をコードに書かないでください。", "Please don't write credentials into the code."),
    ("暗号化", "あんごうか", "angōka", "encryption",
     "Transforming data so only a holder of the key can read it.",
     "鍵を持つ人だけが読めるようにデータを変換することです。",
     "通信は暗号化されています。", "The communication is encrypted."),
    ("復号", "ふくごう", "fukugō", "decryption",
     "Turning encrypted data back into the original, using the key.",
     "鍵を使って、暗号化されたデータを元に戻すことです。",
     "受け取った内容を復号します。", "We decrypt the content we received."),
    ("脆弱性", "ぜいじゃくせい", "zeijakusei", "vulnerability",
     "A weakness an attacker can use — an unescaped input, a missing permission check.",
     "攻撃者に利用されうる弱点です。入力の処理漏れや権限確認の不足などが該当します。",
     "この脆弱性は早く直す必要があります。", "This vulnerability needs fixing quickly."),
    ("負荷", "ふか", "fuka", "load",
     "How much work a system is being asked to do at once.",
     "システムが同時に処理を求められている量のことです。",
     "アクセスが増えてサーバーの負荷が高くなりました。", "Traffic rose and the load on the server got high."),
    ("帯域幅", "たいいきはば", "taiikihaba", "bandwidth",
     "How much data a connection can carry per second.",
     "接続が一秒あたりに運べるデータの量です。",
     "画像を小さくして帯域幅を節約します。", "We shrink the images to save bandwidth."),
    ("転送", "てんそう", "tensō", "transfer",
     "Moving data from one place to another over a connection.",
     "接続を通じてデータをある場所から別の場所へ移すことです。",
     "大きなファイルの転送には時間がかかります。", "Transferring a large file takes time."),
    ("待ち時間", "まちじかん", "machi jikan", "latency",
     "The delay before a response starts coming back — distinct from how fast it then arrives.",
     "応答が返り始めるまでの遅れのことです。その後の速さとは別の指標です。",
     "待ち時間が長いと操作が重く感じます。", "When latency is high, the interface feels sluggish."),
]

# Katakana block, the katakana phonetic extensions, and half-width katakana.
_JPV_KATAKANA = _jpv_re.compile(r"[゠-ヿㇰ-ㇿｦ-ﾟ]")
_JPV_HIRAGANA = _jpv_re.compile(r"^[ぁ-ゟ]+$")


def _jpv_slug(romaji):
    """"kata hikisū" -> "kata-hikisu" — a stable, ASCII, URL-safe id."""
    s = _jpv_ud.normalize("NFKD", romaji)
    s = "".join(ch for ch in s if not _jpv_ud.combining(ch)).lower()
    return _jpv_re.sub(r"[^a-z0-9]+", "-", s).strip("-")


# ---------------------------------------------------------------------------
# Difficulty, keyed by word id: 1 everyday · 2 textbook · 3 specialist.
#
# Kept beside the rows rather than inside them so adding a level to 100 existing
# words stayed a reviewable table instead of 100 edited tuples. It is NOT a
# second source of truth: _jpv_build asserts that every word has an entry and
# that every entry names a real word, so a word added without a level fails the
# build rather than quietly defaulting.
# ---------------------------------------------------------------------------
_JPV_LEVEL = {
    # --- java ---
    "keisho": 2, "chushoka": 2, "tataisei": 3, "joho-inpei": 3, "shushokushi": 2,
    "seiteki": 2, "sanshogata": 2, "kihongata": 2, "reigai": 1, "kensa-reigai": 3,
    "soshutsu": 2, "hosoku": 2, "sengen": 1, "shokika": 1, "seisei": 1,
    "soshogata": 3, "kata-shokyo": 3, "fuhen": 2, "doki": 2, "haita-seigyo": 3,
    "heiko-shori": 2, "kyogo-jotai": 3, "tokumei": 2, "saiteigi": 2, "taju-teigi": 3,
    "kata-henkan": 2, "rekkyogata": 2, "chushaku": 2, "teisu": 1, "doitsusei": 3,
    "kari-hikisu": 2, "jitsu-hikisu": 2, "chukan-sosa": 3, "shutan-sosa": 3,
    # --- problems ---
    "hairetsu": 1, "soeji": 2, "yoso": 1, "tansaku": 1, "nibun-tansaku": 2,
    "seiretsu": 1, "shojun": 2, "kojun": 2, "keisanryo": 2, "saiki": 2,
    "doteki-keikakuho": 3, "don-yokuho": 3, "zentansaku": 2, "haba-yusen-tansaku": 3,
    "fukasa-yusen-tansaku": 3, "ki": 1, "ne": 1, "choten": 2, "hen": 1,
    "rinsetsu": 3, "saitan-keiro": 2, "bubun-mojiretsu": 2, "bubun-hairetsu": 2,
    "ruisekiwa": 3, "shakutoriho": 3, "nyuryoku": 1, "shutsuryoku": 1,
    "seiyaku": 2, "kyokaichi": 3, "chofuku": 2, "kaibun": 2, "junretsu": 3,
    "amari": 1,
    # --- typescript ---
    "kata-chushaku": 2, "kata-suiron": 2, "kata-anzen": 2, "kata-kensa": 2,
    "seiteki-katazuke": 2, "doteki-katazuke": 2, "kozoteki-katazuke": 3,
    "koshogata": 3, "gappeigata": 2, "kosagata": 3, "bubungata": 3, "gokansei": 2,
    "shiborikomi": 3, "kata-jutsugo": 3, "morasei": 3, "hanbetsu-kano": 3,
    "jokengata": 3, "kata-hikisu": 2, "kata-hyomei": 3, "yomitori-sen-yo": 2,
    "shoryaku-kano": 2, "miteigi": 1, "genkaku": 2, "hidoki": 2, "taiki": 2,
    "heiretsu": 1, "bunkatsu-dainyu": 2, "tenkai-kobun": 2, "zan-yo-hikisu": 3,
    "kiteichi": 2, "namae-kukan": 3, "izon-kankei": 2, "jikkoji": 1,
    # --- sql ---
    "ketsugo": 2, "naibu-ketsugo": 3, "gaibu-ketsugo": 3, "shukei": 2,
    "shuyaku-kansu": 3, "fuku-toiawase": 3, "sakuin": 2, "seikika": 3,
    "ikkansei": 3, "torihiki": 2, "gyo": 1, "retsu": 1, "hyo": 1,
    "chushutsu": 2, "sonyu": 2, "sakujo": 1, "koshin": 1, "narabekae": 2,
    "kensu": 2, "gokei": 1, "heikin": 1, "saidaichi": 2, "saishochi": 2,
    "jikko-keikaku": 3, "ichii-seiyaku": 3,
    # --- web ---
    "ninsho": 2, "ninka": 3, "yokyu": 1, "oto": 1, "tsushin": 2,
    "eizokuka": 3, "kengen": 2, "jotai": 1, "shutoku": 1, "hyoji": 1,
    "byoga": 2, "tanmatsu": 2, "keiro": 2, "midashi": 1, "kaiso": 2,
    "sen-i": 3, "shikibetsushi": 2, "shikaku-joho": 3, "angoka": 3,
    "fukugo": 3, "zeijakusei": 3, "fuka": 2, "taiikihaba": 3, "tenso": 2,
    "machi-jikan": 2,
}

# The list only grows. Raised as each batch of Step 6 lands, so a word removed
# by accident fails the build instead of shrinking the track silently.
_JPV_FLOORS = {
    "java": 34,
    "problems": 33,
    "typescript": 33,
    "sql": 25,
    "web": 25,
}
_JPV_TOTAL_FLOOR = 150

# Words that genuinely live under more than one tag, beyond the list they are
# authored in. 計算量 is as much a Java-interview word as a coding-problem one,
# and the filter should find it under both.
_JPV_EXTRA_TAGS = {
    "keisanryo": ["java"],
    "saiki": ["java"],
    "hairetsu": ["java"],
    "kaibun": ["java"],
    "hidoki": ["java"],
    "heiretsu": ["java"],
    "kata-henkan": ["typescript"],
    "fuhen": ["typescript"],
    "soshogata": ["typescript"],
    "kata-hikisu": ["java"],
    "izon-kankei": ["java"],
    "jikkoji": ["java"],
    "bubun-mojiretsu": ["typescript"],
}


def _jpv_build():
    tag_ids = {t["id"] for t in JP_VOCAB_TAGS}
    words, seen_terms, seen_ids = [], set(), set()
    for tag, rows in (("java", _JPV_JAVA), ("problems", _JPV_PROBLEMS),
                      ("typescript", _JPV_TYPESCRIPT), ("sql", _JPV_SQL),
                      ("web", _JPV_WEB)):
        assert tag in tag_ids, f"unknown vocab tag {tag!r}"
        for row in rows:
            assert len(row) == 8, f"vocab row needs 8 fields: {row!r}"
            term, reading, romaji, meaning, desc_en, desc_ja, ex_ja, ex_en = row
            for field in row:
                assert field.strip(), f"empty field in vocab row for {term!r}"
            assert not _JPV_KATAKANA.search(term), f"vocab term must not be katakana: {term!r}"
            assert _JPV_HIRAGANA.match(reading), f"vocab reading must be hiragana: {term!r} -> {reading!r}"
            assert term in ex_ja, f"example sentence must contain the term {term!r}: {ex_ja!r}"
            wid = _jpv_slug(romaji)
            assert term not in seen_terms, f"duplicate vocab term {term!r}"
            assert wid not in seen_ids, f"duplicate vocab id {wid!r} ({term!r})"
            seen_terms.add(term)
            seen_ids.add(wid)

            # The tag the word is authored under comes first; any extra tags
            # follow, de-duplicated and checked against the declared set.
            tags = [tag]
            for extra in _JPV_EXTRA_TAGS.get(wid, []):
                assert extra in tag_ids, f"unknown extra tag {extra!r} on {term!r}"
                assert extra != tag, f"redundant extra tag {extra!r} on {term!r}"
                if extra not in tags:
                    tags.append(extra)

            assert wid in _JPV_LEVEL, f"no level for {term!r} (id {wid!r}) — add one to _JPV_LEVEL"
            level = _JPV_LEVEL[wid]
            assert level in (1, 2, 3), f"level must be 1, 2 or 3: {term!r} -> {level!r}"

            words.append({
                "id": wid,
                "term": term,
                "reading": reading,
                "romaji": romaji,
                "tags": tags,
                "level": level,
                "meaning": meaning,
                "desc_en": desc_en,
                "desc_ja": desc_ja,
                "example_ja": ex_ja,
                "example_en": ex_en,
            })

    # A per-tag floor rather than one total: a batch can land without rewriting
    # the number, but no tag can quietly wither while the total still looks fine.
    for t, floor in _JPV_FLOORS.items():
        have = sum(1 for w in words if t in w["tags"])
        assert have >= floor, f"tag {t!r} has {have} words, below its floor of {floor}"
    assert len(words) >= _JPV_TOTAL_FLOOR, (
        f"expected at least {_JPV_TOTAL_FLOOR} vocabulary words, got {len(words)}"
    )

    # No stale levels: every entry must name a word that still exists.
    unknown = set(_JPV_LEVEL) - seen_ids
    assert not unknown, f"_JPV_LEVEL names words that don't exist: {sorted(unknown)}"
    unknown = set(_JPV_EXTRA_TAGS) - seen_ids
    assert not unknown, f"_JPV_EXTRA_TAGS names words that don't exist: {sorted(unknown)}"

    # Every tag is learnable from the ground up: a tag that only has specialist
    # words has no entry point, and one with no specialist words is thin.
    for t in tag_ids:
        have = {w["level"] for w in words if t in w["tags"]}
        assert have == {1, 2, 3}, f"tag {t!r} is missing words at level(s) {sorted({1, 2, 3} - have)}"

    return {"tags": JP_VOCAB_TAGS, "words": words}


JP_VOCAB = _jpv_build()
