# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Review cards for the TypeScript Mastery track — 12 per week.
#
# Completing a week used to seed exactly one card per chapter: the chapter's
# name on the front, its one-line summary on the back. That tests whether you
# remember a title, not whether you know TypeScript. These cards ask the
# questions the week is actually about — what does this infer, which error is
# this, why does this line compile — and land in Flashcards (the SM-2 deck)
# when the week is completed, or at launch for weeks already completed.
#
# exec()'d inside gen_seed.py's namespace right after mastery_defs.py, so
# TS_WEEKS exists. Fronts must be unique across the track: the deck dedupes on
# (front, source), and two weeks asking the same thing is a wasted card.
#
# Every claim here is about TypeScript 5.x under `--strict`, which is what the
# judge runs (src-tauri/src/tscheck.rs).
# ---------------------------------------------------------------------------

TS_CARDS = {
    1: [
        ("What type does `const x = 5` infer, and what does `let y = 5` infer?",
         "`x` is the literal type `5` — a `const` can never hold anything else. `y` widens to `number`, because a `let` can be reassigned."),
        ("Why reach for `const` by default?",
         "It forbids reassigning the binding, which removes a whole class of accidental-overwrite bugs. Switch to `let` only when the value genuinely changes."),
        ("`let count = 0; count = \"zero\";` — what happens?",
         "Compile error (TS2322): `count` was inferred as `number` from its initializer, and that inference is binding."),
        ("`any` vs `unknown` — the one-line difference?",
         "`any` switches type checking off for that value; `unknown` keeps it on and makes you narrow before you use the value."),
        ("Does a type annotation change what a program does at runtime?",
         "No. Types are erased before the code runs — the judge literally strips them. They only decide whether the program is allowed to compile."),
        ("Where are annotations most worth writing?",
         "On function boundaries (parameters and exported return types). Locals are usually better inferred from their initializer."),
        ("How does a judged program read all of stdin?",
         "`import * as fs from \"fs\"; const input = fs.readFileSync(0, \"utf8\");` — file descriptor 0 is standard input."),
        ("Why `.trim()` input before parsing it?",
         "Input ends with a newline, and on Windows lines end in `\\r\\n`; a stray `\\r` makes string comparisons fail silently."),
        ("`Number(\"\")`, `Number(\"12px\")`, `Number(\" 7 \")` — results?",
         "`0`, `NaN`, `7`. `Number` ignores surrounding whitespace, treats an empty string as zero, and rejects any trailing junk."),
        ("`parseInt(\"12px\")` vs `Number(\"12px\")`?",
         "`parseInt` reads the leading digits and returns `12`; `Number` requires the whole string to be numeric and returns `NaN`."),
        ("What does `console.log(\"a\", 1)` print?",
         "`a 1` — `console.log` joins its arguments with a single space."),
        ("Is there an `int` type in TypeScript?",
         "No. `number` is one type for integers and fractions alike (IEEE-754 doubles); `bigint` is a separate type for arbitrarily large integers."),
    ],
    2: [
        ("`===` vs `==`?",
         "`===` compares without type coercion. `==` coerces first, so `\"\" == 0` and `null == undefined` are both true. Use `===`."),
        ("List the falsy values.",
         "`false`, `0`, `-0`, `0n`, `\"\"`, `null`, `undefined`, `NaN`. Everything else — including `\"0\"`, `[]` and `{}` — is truthy."),
        ("`value || 10` vs `value ?? 10` when `value` is `0`?",
         "`||` gives `10` (0 is falsy); `??` gives `0` (it only replaces `null` and `undefined`)."),
        ("Why is `a ?? b || c` a syntax error?",
         "Mixing `??` with `||` or `&&` without parentheses is rejected on purpose — the precedence is too easy to misread. Write `(a ?? b) || c`."),
        ("What is `-7 % 3`?",
         "`-1`. The remainder takes the sign of the dividend, so an \"is it odd?\" check must be `n % 2 !== 0`, not `n % 2 === 1`."),
        ("`NaN === NaN`?",
         "`false` — NaN is not equal to anything. Test with `Number.isNaN(x)`."),
        ("`\"10\" < \"9\"`?",
         "`true`. Strings compare character by character, and `\"1\"` sorts before `\"9\"`. Convert to numbers first."),
        ("What goes wrong when a `switch` case has no `break`?",
         "Execution falls through into the next case. `noFallthroughCasesInSwitch` turns that into a compile error (TS7029)."),
        ("When is a ternary better than an `if`?",
         "When you are choosing a value: `const label = n >= 0 ? \"pos\" : \"neg\"`. Use `if` when you are choosing what to *do*."),
        ("Why does `if (count)` hide bugs?",
         "It skips `0` as well as `undefined`. Say what you mean: `if (count !== undefined)`."),
        ("What does an early `return` buy you?",
         "Fewer nested blocks: handle the edge cases first, then the main path reads straight down."),
        ("TS2367 \"This comparison appears to be unintentional\" — cause?",
         "Comparing values whose types cannot overlap, e.g. `status === \"done\"` when `status` is `\"idle\" | \"loading\"`."),
    ],
    3: [
        ("`0.1 + 0.2 === 0.3`?",
         "`false` — it is `0.30000000000000004`. Work in integer cents for money, or compare with a tolerance."),
        ("How should money be stored?",
         "As an integer number of cents. Divide by 100 only when formatting for display."),
        ("`Math.floor(-2.5)` vs `Math.trunc(-2.5)`?",
         "`-3` vs `-2`. `floor` rounds toward −∞; `trunc` drops the fraction, rounding toward zero."),
        ("`(1.005).toFixed(2)`?",
         "`\"1.00\"` — 1.005 is stored as 1.00499999… `toFixed` also returns a *string*."),
        ("What is `Number.MAX_SAFE_INTEGER` and why care?",
         "2^53 − 1. Above it, not every integer is representable, so arithmetic silently loses precision. Use `bigint` beyond it."),
        ("How do you write and use a `bigint`?",
         "Suffix with `n`: `10n ** 20n`. You cannot mix `bigint` and `number` in arithmetic (TS2365) — convert one explicitly."),
        ("`for…of` vs `for…in` over an array?",
         "`for…of` gives the values; `for…in` gives the keys as *strings* (`\"0\"`, `\"1\"`, …). Use `for…of` for arrays."),
        ("How do you peel the digits off a positive integer?",
         "Loop: `digit = n % 10; n = Math.trunc(n / 10);` until `n` is 0."),
        ("How far must a primality check go?",
         "Divisors up to `√n` — any factor above the square root pairs with one below it."),
        ("What is a loop invariant?",
         "Something true before and after every iteration (e.g. \"`sum` is the total of items 0..i-1\"). Stating it is how you avoid off-by-one errors."),
        ("How do you format `1234567.8` as `1,234,567.80`?",
         "`new Intl.NumberFormat(\"en-US\", { minimumFractionDigits: 2 }).format(1234567.8)`."),
        ("`Number.isInteger(5.0)`?",
         "`true` — 5.0 and 5 are the same number."),
    ],
    4: [
        ("Can you change a character inside a string?",
         "No — strings are immutable. Build a new one: `s[0].toUpperCase() + s.slice(1)`."),
        ("`\"a-b-a\".replace(\"a\", \"x\")`?",
         "`\"x-b-a\"`. A string pattern replaces only the first match; use `replaceAll` or a `/g` regex for all of them."),
        ("`\"a  b\".split(\" \")`?",
         "`[\"a\", \"\", \"b\"]` — the empty string between the two spaces is kept. Split on `/\\s+/` to collapse runs."),
        ("`slice` vs `substring` with a negative index?",
         "`slice(-2)` counts from the end; `substring` treats negatives as 0."),
        ("Why can `\"😀\".length` be 2?",
         "`length` counts UTF-16 code units, and an emoji is two. `[...s]` iterates code points."),
        ("How do you right-align a value in a column of width 8?",
         "`String(value).padStart(8)` — or `padEnd` to left-align."),
        ("How do you sort strings the way a human expects?",
         "`words.sort((a, b) => a.localeCompare(b))`. The default sort compares UTF-16 code units, so `\"Z\"` comes before `\"a\"`."),
        ("What does `str.match(/x(\\d+)/)` return when nothing matches?",
         "`null` — which is why TypeScript makes you check the result before indexing it."),
        ("How do you get every match of a regex, with its groups?",
         "`for (const m of text.matchAll(/(\\w+)=(\\d+)/g))` — `matchAll` needs the `g` flag."),
        ("What is a named capture group?",
         "`/(?<year>\\d{4})-(?<month>\\d{2})/` — read it back as `match.groups?.year`."),
        ("Why build a string with `parts.join(\"\")` rather than `+=` in a loop?",
         "It states the intent and avoids off-by-one separators; `join(\", \")` puts separators only *between* items."),
        ("`\"Hello\".at(-1)`?",
         "`\"o\"` — `at` accepts negative indices, counting from the end."),
    ],
    5: [
        ("Optional parameter vs default parameter?",
         "`f(x?: number)` makes `x` `number | undefined` inside. `f(x = 8)` makes `x` a `number` inside, with 8 used when the caller passes nothing."),
        ("Can a required parameter follow an optional one?",
         "No (TS1016). Optional and defaulted parameters go last — or take an options object."),
        ("When should you annotate a function's return type?",
         "On exported and public functions — it pins the contract, so a mistake inside is reported at the function rather than at every caller."),
        ("What is the type of a rest parameter?",
         "An array (or tuple): `function sum(...xs: number[])`."),
        ("`void` vs `undefined` as a return type?",
         "`void` means \"ignore the result\" — a callback typed `() => void` may still return something. `undefined` means it really returns `undefined`."),
        ("Function declaration vs arrow function — two practical differences?",
         "Declarations are hoisted (callable before the line they appear on); arrows capture `this` from where they are defined."),
        ("What is a closure?",
         "A function that keeps access to the variables of the scope it was created in, even after that scope has returned."),
        ("Why use an options object instead of many positional parameters?",
         "Call sites become self-describing (`format(v, { width: 8 })`), every option can be optional, and adding one breaks no caller."),
        ("What are overload signatures for?",
         "Describing a function whose return type depends on its argument types. Only the overloads are visible to callers — the implementation signature is not."),
        ("When is a union parameter better than overloads?",
         "When the return type does not depend on which member was passed: `f(x: string | number): string` beats two overloads."),
        ("What is a pure function?",
         "Same inputs → same output, and no side effects. It is trivially testable and safe to reuse."),
        ("TS2554 — cause?",
         "Wrong number of arguments: \"Expected 2 arguments, but got 1.\""),
    ],
    6: [
        ("What is a higher-order function?",
         "One that takes a function as an argument, returns one, or both — `map`, `filter`, a `pipe` helper."),
        ("How do you write the type of a function that takes a number and returns a string?",
         "`(x: number) => string`. The parameter name is part of the syntax but not of the type."),
        ("Why don't callbacks usually need parameter annotations?",
         "Contextual typing: in `nums.map((n) => n * 2)`, `n` is inferred from `nums`' element type."),
        ("`pipe` vs `compose`?",
         "`pipe(f, g)(x)` is `g(f(x))` — left to right. `compose(f, g)(x)` is `f(g(x))` — right to left."),
        ("`[\"1\", \"2\", \"3\"].map(parseInt)`?",
         "`[1, NaN, NaN]` — `map` passes `(value, index)`, so `parseInt` receives the index as its radix. Write `map((s) => parseInt(s, 10))`."),
        ("What is currying?",
         "Turning `f(a, b)` into `f(a)(b)`, so you can fix the first argument now and supply the rest later."),
        ("What goes wrong with `arr.forEach(obj.method)`?",
         "The method is detached from `obj`, so `this` is `undefined` inside it. Pass `(x) => obj.method(x)` instead."),
        ("What must every recursive function have?",
         "A base case that stops without recursing, and a recursive case that moves strictly toward it."),
        ("What error does unbounded recursion raise in Node?",
         "`RangeError: Maximum call stack size exceeded`."),
        ("What is memoisation?",
         "Caching a pure function's results by argument, so repeated calls cost a lookup. It turns naive Fibonacci from O(2^n) into O(n)."),
        ("`reduce` without an initial value on an empty array?",
         "It throws `TypeError: Reduce of empty array with no initial value`. Always pass one."),
        ("What does a function returning a function let you build?",
         "Configured behaviour: `multiplyBy(2)` returns a doubler; a counter factory keeps private state in its closure."),
    ],
    7: [
        ("`[10, 9, 1].sort()`?",
         "`[1, 10, 9]` — the default sort compares elements as strings. Pass a comparator: `sort((a, b) => a - b)`."),
        ("Which array methods mutate the array in place?",
         "`push`, `pop`, `shift`, `unshift`, `splice`, `sort`, `reverse`, `fill`. The copying versions are `toSorted`, `toReversed`, `toSpliced`, `with`."),
        ("What does `find` return when nothing matches?",
         "`undefined` — its type is `T | undefined`, so TypeScript makes you handle the miss."),
        ("How do you sort without touching the original array?",
         "`[...xs].sort(cmp)` — or `xs.toSorted(cmp)` in ES2023+."),
        ("What is a tuple type?",
         "A fixed-length array whose positions have their own types: `[string, number]`. Good for returning a pair: `function minMax(xs): [number, number]`."),
        ("`T[]` vs `Array<T>`?",
         "Identical. `T[]` is the usual spelling; `readonly T[]` is the read-only form."),
        ("Why does `new Array(3).map((_, i) => i)` return holes?",
         "`new Array(3)` has no elements, only a length, and `map` skips holes. Use `Array.from({ length: 3 }, (_, i) => i)`."),
        ("How do you stop a `forEach` early?",
         "You can't. Use a `for…of` loop with `break`, or `some` / `every` / `find`."),
        ("`includes` vs `indexOf(x) !== -1`?",
         "Same intent, but `includes` also finds `NaN`, and reads as a question."),
        ("What does `flatMap` do?",
         "Maps each element to an array and flattens one level: `lines.flatMap((l) => l.split(\" \"))`."),
        ("How do you get the last element safely?",
         "`xs.at(-1)` — typed `T | undefined`, because the array might be empty."),
        ("What does `noUncheckedIndexedAccess` change about `xs[i]`?",
         "Its type becomes `T | undefined`, so an out-of-range read has to be handled instead of silently producing `undefined`."),
    ],
    8: [
        ("Destructuring with a default: what does `const { tags = [] } = obj` do?",
         "Binds `tags` to `obj.tags`, or `[]` when that is `undefined` (not when it is `null`)."),
        ("How deep does a spread copy?",
         "One level. `{ ...a }` copies top-level properties; nested objects are still shared."),
        ("`{ ...a, ...b }` when both have `x`?",
         "`b.x` wins — later spreads overwrite earlier keys."),
        ("Why does `Object.keys(obj)` return `string[]` and not `(keyof T)[]`?",
         "Structural typing: a value may carry extra keys its type does not mention, so `keyof T` would be a lie."),
        ("What does `JSON.parse` return, type-wise?",
         "`any` — the compiler has no idea what the text contains. Treat it as `unknown` and validate."),
        ("What does `JSON.stringify` drop?",
         "`undefined` values, functions and symbols (in objects); `NaN` and `Infinity` become `null`."),
        ("`interface` vs `type` — when does it matter?",
         "Interfaces can be merged by redeclaring them and extended with `extends`; type aliases can name unions, tuples and mapped types. For object shapes, either works."),
        ("What is an excess-property check?",
         "A fresh object literal with a key the target type does not declare is an error (TS2353). It only applies to literals, not to variables."),
        ("How do you type an object used as a dictionary?",
         "`Record<string, number>` or `{ [key: string]: number }`."),
        ("Destructuring `null` vs spreading `null`?",
         "`const { a } = null` throws a TypeError; `{ ...null }` is just `{}`."),
        ("How do you pretty-print JSON with 2-space indentation?",
         "`JSON.stringify(value, null, 2)`."),
        ("TS2741 — cause?",
         "A required property is missing from an object assigned to a type: \"Property 'id' is missing in type …\"."),
    ],
    9: [
        ("`Map` vs a plain object as a lookup table — three reasons for `Map`?",
         "Any key type (not just strings), a real `size`, and no inherited keys like `toString` to trip over."),
        ("What type does `map.get(key)` have?",
         "`V | undefined` — the key might be absent."),
        ("The frequency-count idiom with a Map?",
         "`counts.set(k, (counts.get(k) ?? 0) + 1)`."),
        ("Are two identical object literals the same `Map` key?",
         "No — object keys compare by identity. `{a: 1}` and `{a: 1}` are two different keys."),
        ("In what order does a `Map` iterate?",
         "Insertion order. Setting an existing key again keeps its original position."),
        ("How do you de-duplicate an array?",
         "`[...new Set(xs)]` — keeps the first occurrence of each value, in order."),
        ("`JSON.stringify(new Map([[\"a\", 1]]))`?",
         "`\"{}\"` — Maps do not serialise. Convert first: `Object.fromEntries(map)`."),
        ("Why is Map/Set lookup O(1) on average?",
         "They are hash tables: a key's hash picks a bucket directly, so no scan is needed."),
        ("What is a `WeakMap` for?",
         "Attaching data to objects without keeping them alive: when the key object is garbage-collected, the entry goes too."),
        ("`new Set(\"hello\")`?",
         "A set of characters: `{\"h\", \"e\", \"l\", \"o\"}` — a string is iterable."),
        ("What does `map[\"key\"] = 1` do to a `Map`?",
         "Sets an ordinary object property, not a Map entry — `map.get(\"key\")` is still `undefined`. Always use `set`."),
        ("Two-sum in one pass?",
         "For each `x`, check whether `target - x` is already in a Map of seen values; if not, record `x`."),
    ],
    10: [
        ("What is a union type?",
         "A value that is exactly one of several types: `string | number`, or `\"idle\" | \"loading\" | \"done\"`."),
        ("Why does `let dir = \"up\"` not have the type `\"up\"`?",
         "`let` widens a literal to its base type (`string`) because it can be reassigned. `const` keeps `\"up\"`."),
        ("What does `as const` do to `[\"S\", \"M\", \"L\"]`?",
         "Makes it `readonly [\"S\", \"M\", \"L\"]` — a read-only tuple of literal types instead of `string[]`."),
        ("How do you derive a union from an `as const` array?",
         "`type Size = (typeof SIZES)[number]` — gives `\"S\" | \"M\" | \"L\"`."),
        ("Why prefer a literal union over an `enum`?",
         "It is pure type syntax (erased, nothing emitted), it needs no import at use sites, and it works in strip-only runners like Node's — which reject `enum`."),
        ("What does a numeric `enum` emit at runtime?",
         "A real object with forward *and* reverse mappings (`Color[0] === \"Red\"`) — it is code, not just a type."),
        ("`type` alias vs `interface` for a union?",
         "Only a `type` alias can name a union: `type Id = string | number`."),
        ("Union of objects vs object with union fields?",
         "`{ ok: true; value: T } | { ok: false; error: E }` forbids impossible combinations; `{ ok: boolean; value?: T; error?: E }` allows them."),
        ("What does `Record<Light, Light>` guarantee for a transition table?",
         "Every member of `Light` has an entry, and every entry is a valid `Light` — miss one and it is a compile error."),
        ("TS2322 on `const s: \"a\" | \"b\" = input`?",
         "`input` is a `string`, which is wider than the union. Validate it first, or narrow with a check."),
        ("What is erasable syntax?",
         "TypeScript that can be deleted to leave valid JavaScript. `enum`, `namespace` and parameter properties are not erasable — they emit code."),
        ("What is `typeof x` in a type position?",
         "The type of the variable `x` — how you lift a value's shape into the type world."),
    ],
    11: [
        ("What is narrowing?",
         "The compiler refining a variable's type inside a branch, from checks like `typeof x === \"string\"` or `x !== null`."),
        ("Which checks narrow?",
         "`typeof`, `instanceof`, `in`, `===`/`!==` against literals, truthiness, `Array.isArray`, and user-defined type predicates."),
        ("What is a type predicate?",
         "A return type `x is T`: `function isPerson(x: unknown): x is Person`. When it returns true, the caller's variable narrows to `Person`."),
        ("What happens if a type predicate lies?",
         "The compiler trusts it anyway — the wrong type flows onward and fails at runtime. The check inside must really prove the claim."),
        ("`typeof null`?",
         "`\"object\"` — a historical bug. Check `x !== null` alongside `typeof x === \"object\"`."),
        ("What is an assertion function?",
         "`function assert(c: unknown): asserts c` — if it returns at all, the condition is true, and the caller narrows."),
        ("Why can narrowing disappear inside a callback?",
         "The callback may run later, after the variable has changed, so narrowing on a `let` does not carry into it. Copy to a `const` first."),
        ("How do you narrow `unknown` to an object with an `id` string?",
         "`typeof x === \"object\" && x !== null && \"id\" in x && typeof x.id === \"string\"`."),
        ("What does the `in` operator narrow?",
         "Between union members by property: `if (\"radius\" in shape)` picks the member that declares `radius`."),
        ("TS18047 / TS18048 — cause?",
         "Using a value that is possibly `null` (18047) or possibly `undefined` (18048) without checking it first."),
        ("Why is `if (x)` a risky narrowing check for numbers?",
         "It removes `0` along with `undefined` and `null`. Use `x !== undefined`."),
        ("What does narrowing do to the runtime?",
         "Nothing — it is compile-time only. The runtime check you wrote is what does the work."),
        ("What does `strictNullChecks` change?",
         "`null` and `undefined` stop being members of every type. `string` no longer admits `null`; you must write `string | null`."),
        ("What does optional chaining return when it short-circuits?",
         "`undefined`. `user?.address?.city` is `undefined` if any link is `null` or `undefined`."),
        ("`a?.b.c` — what if `a.b` is `undefined`?",
         "It throws. `?.` only guards the link it is written on; you need `a?.b?.c`."),
        ("What does `x ??= y` do?",
         "Assigns `y` to `x` only when `x` is `null` or `undefined`."),
        ("How do you honestly handle `map.get(k)` under strict?",
         "Check it: `const v = map.get(k); if (v === undefined) { … }` — or supply a default with `??`."),
        ("`null` vs `undefined` — a convention that keeps code sane?",
         "`undefined` for \"not provided / absent\"; `null` for \"deliberately empty\". Don't mix them for one concept."),
    ],
    12: [
        ("What makes a union \"discriminated\"?",
         "Every member has a common property with a distinct literal type — the tag — e.g. `kind: \"circle\" | \"square\"`."),
        ("How do you narrow a discriminated union?",
         "`switch (shape.kind)` — inside each `case`, `shape` is that member, with its own fields available."),
        ("How do you make a `switch` prove it handles every member?",
         "In `default`, assign the value to `never`: `const unreachable: never = shape;`. A new, unhandled member becomes a compile error."),
        ("What is `never`?",
         "The type with no values — the empty union. A variable narrowed to `never` is in code that cannot run."),
        ("Why does a `kind: string` tag not work?",
         "It is not a literal type, so checking it cannot tell members apart. Tags must be literals."),
        ("What is a `Result<T, E>`?",
         "`{ ok: true; value: T } | { ok: false; error: E }` — a success-or-failure value the caller has to check before using."),
        ("Why can a `default:` branch hide bugs?",
         "It silently absorbs members added later. Prefer an exhaustive `never` check, so the compiler lists every place to update."),
        ("How should state that carries data be modelled?",
         "Per state: `{ status: \"done\"; value: T } | { status: \"failed\"; error: string }` — the data exists only in the state that has it."),
        ("What does a reducer look like in TypeScript?",
         "`(state: State, action: Action) => State`, with `Action` a discriminated union switched on `action.type`."),
        ("`unknown` vs `never`?",
         "`unknown` is the top type (every value fits); `never` is the bottom type (no value fits)."),
        ("TS2339 on `shape.radius` when `shape` is `Circle | Square`?",
         "`radius` exists on only one member. Narrow first (`if (shape.kind === \"circle\")`)."),
        ("What does exhaustiveness checking buy you in a refactor?",
         "Add a variant and the compiler points at every `switch` that does not handle it yet."),
    ],
    13: [
        ("Checkpoint: which week's tool handles \"count how often each word appears\"?",
         "A `Map<string, number>` with the `(get(k) ?? 0) + 1` idiom — then sort the entries by count, breaking ties by key."),
        ("Checkpoint: how do you sort entries by count descending, then alphabetically?",
         "`entries.sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))`."),
        ("Checkpoint: reading a JSON record from untrusted input — the three steps?",
         "Parse into `unknown`, check the shape with a type predicate, then use the narrowed value."),
        ("Checkpoint: string, number or array — which methods mutate?",
         "Strings and numbers never. Arrays do for `push`, `pop`, `splice`, `sort`, `reverse`; prefer the copying versions."),
        ("Checkpoint: what does `const` protect, and what doesn't it?",
         "It stops reassigning the binding; it does not stop mutating the object or array it points to."),
        ("Checkpoint: the fastest way to test membership repeatedly?",
         "Build a `Set` once, then `set.has(x)` is O(1) — `array.includes` is O(n) each time."),
        ("Checkpoint: where do default values belong — `||` or `??`?",
         "`??`, unless you really mean to replace every falsy value, including `0` and `\"\"`."),
        ("Checkpoint: how do you avoid mutating an argument inside a function?",
         "Copy first (`[...xs]`, `{ ...obj }`), or type the parameter `readonly` so the compiler refuses."),
        ("Checkpoint: sliding window over a string — what is the state?",
         "A left pointer and a map or set of what is inside the window; the right pointer extends it, the left shrinks it."),
        ("Checkpoint: prefix sums answer which question in O(1)?",
         "The sum of any range `[i, j)`: `prefix[j] - prefix[i]`."),
        ("Checkpoint: when is `!` (non-null assertion) acceptable?",
         "When you have just proved non-null in a way the compiler can't follow — e.g. right after `map.has(k)` for `map.get(k)!`."),
        ("Checkpoint: why diff a rewrite against your old version?",
         "Each difference you can justify is something you now understand; each one you can't is something to go and look up."),
        ("Write the type of a callable object that also has a `label: string`.",
         "`{ (x: number): string; label: string }` — a call signature plus a property."),
        ("Write the type of \"something you call with `new` and a number to get a `Shape`\".",
         "`new (size: number) => Shape` — a construct signature. A class value has one."),
        ("A slot wants `(value, index) => void`. May you pass `(value) => value * 2`?",
         "Yes: fewer parameters are fine, and a `void` slot accepts any return value — it is simply ignored."),
        ("Why is `(e: \"click\") => void` not assignable to `(e: string) => void` under `strict`?",
         "Parameters are checked contravariantly: the slot may pass any string, and the handler only accepts one."),
        ("What makes `type _ = Expect<Equal<A, B>>` a test?",
         "`Expect` only accepts `true`, and `Equal` is `true` only for identical types — so the line compiles only when the claim holds."),
        ("What does an unused `@ts-expect-error` do?",
         "It is itself an error (TS2578) — which is exactly what makes it a negative test."),
    ],
    14: [
        ("What does `noUncheckedIndexedAccess` add?",
         "`undefined` to the type of every index read — `xs[i]` becomes `T | undefined`, `record[key]` becomes `V | undefined`."),
        ("Name four flags `strict` turns on.",
         "`strictNullChecks`, `noImplicitAny`, `strictFunctionTypes`, `strictPropertyInitialization` (also `useUnknownInCatchVariables`, `alwaysStrict`, `strictBindCallApply`)."),
        ("What does `noImplicitAny` catch?",
         "Parameters and variables whose type would silently fall back to `any` (TS7006, TS7005)."),
        ("`exactOptionalPropertyTypes` — what changes?",
         "`{ x?: number }` no longer accepts `x: undefined` explicitly — only a missing `x`."),
        ("Why is `skipLibCheck` common?",
         "It skips type-checking `.d.ts` files, which speeds builds and avoids errors in third-party types — at the cost of hiding real ones."),
        ("TS2532 \"Object is possibly 'undefined'\" — the usual source under `noUncheckedIndexedAccess`?",
         "An element access like `xs[0]` or `row[i]` — an index read that might be out of range."),
        ("Named export vs default export?",
         "`export function f` is imported as `{ f }` under that exact name; a default export is imported under any name. Named exports refactor more safely."),
        ("What is `import type` for?",
         "Importing only types. The import is erased entirely, which strip-only runners and `verbatimModuleSyntax` rely on."),
        ("What is a `.d.ts` file?",
         "A declaration file: types only, no implementation — how types are described for JavaScript code."),
        ("What does `declare` mean?",
         "\"This exists at runtime, trust me\" — it describes a value without creating it, e.g. `declare const VERSION: string`."),
        ("How do you type an untyped JavaScript module?",
         "Write `declare module \"lib\" { export function f(x: number): string; }` in a `.d.ts` file."),
        ("What is module augmentation?",
         "Reopening an existing module's declarations to add members: `declare module \"lib\" { interface Options { extra?: boolean } }`."),
        ("What does `declare global` do?",
         "Adds declarations to the global scope from inside a module file."),
        ("Why can a barrel file (`index.ts` re-exporting everything) hurt?",
         "It can create circular imports and pull the whole folder into every importer."),
        ("What is a circular import's typical symptom?",
         "A value is `undefined` at the moment it's used, because its module hadn't finished evaluating."),
        ("Why does `namespace` not run in Node's type-stripping mode?",
         "A namespace emits a real object and code — it isn't erasable. Use ES modules instead."),
        ("What is `moduleResolution: \"bundler\"` for?",
         "Resolving imports the way modern bundlers do: extensionless relative imports allowed, `package.json` `exports` respected."),
    ],
    15: [
        ("What does `as T` actually do?",
         "Nothing at runtime. It tells the compiler \"trust me, this is a T\" — a claim, not a conversion."),
        ("When is `x as unknown as T` needed?",
         "When the two types don't overlap enough for a direct `as` (TS2352). Its ugliness is deliberate — it flags a dangerous claim."),
        ("`: T` vs `as T` vs `satisfies T` on an object literal?",
         "`: T` checks and widens to `T`; `as T` asserts with little checking; `satisfies T` checks but keeps the literal's own, narrower type."),
        ("Why use `satisfies` on a config table?",
         "You get errors for a wrong shape *and* keep the literal keys, so `keyof typeof table` is the exact key union."),
        ("What is structural typing?",
         "Compatibility by shape, not by name: any value with the required members fits, whatever it was declared as."),
        ("A variable with extra properties is assigned to a narrower type. What happens to the extras at runtime?",
         "They stay. The type just stops mentioning them — `Object.keys` still lists them."),
        ("Why are excess-property errors only reported for literals?",
         "A fresh literal can't be used anywhere else, so an extra key is almost certainly a typo. A variable may legitimately have more."),
        ("Why is `Dog[]` assignable to `Animal[]` a hole in the type system?",
         "Arrays are treated covariantly, so you can push a plain `Animal` through the `Animal[]` view into what is really a `Dog[]`."),
        ("Contravariance in one sentence?",
         "A function that accepts `Animal` can stand in for one that accepts `Dog` — not the other way round."),
        ("Why are methods declared with method syntax riskier than function-typed properties?",
         "Method parameters are checked bivariantly even under `strictFunctionTypes`, so an unsafe override compiles."),
        ("TS1360 — cause?",
         "A `satisfies` check failed: the expression does not satisfy the type named after it."),
        ("Why test membership with `Object.hasOwn(obj, k)` instead of `k in obj`?",
         "`in` also sees inherited properties — `\"toString\" in {}` is `true`."),
    ],
    16: [
        ("What is a branded type?",
         "A primitive intersected with a tag: `type Cents = number & { readonly __brand: \"Cents\" }`, so a plain `number` is not accepted where `Cents` is expected."),
        ("How should branded values be created?",
         "By one validating constructor that returns `Cents | null` (or throws) — the only place the `as Cents` cast appears."),
        ("Does a brand exist at runtime?",
         "No — it is purely a type. A `Cents` is an ordinary number when the program runs."),
        ("What does `readonly` on a property prevent?",
         "Assigning to it through that type (TS2540). It does not deep-freeze, and it does not exist at runtime."),
        ("`readonly number[]` vs `ReadonlyArray<number>`?",
         "The same type; both drop `push`, `pop`, `sort` and the other mutators."),
        ("What does `Object.freeze` do that `readonly` doesn't?",
         "It is enforced at runtime. But it is shallow, and a write to a frozen property fails silently in sloppy mode and throws only in strict mode."),
        ("What is aliasing, and why is it a bug source?",
         "Two names for one object. Mutating through one changes what the other sees — the fix is copying, or making mutation impossible."),
        ("How do you update one element of an array immutably?",
         "`xs.with(i, value)` (ES2023) or `xs.map((x, j) => (j === i ? value : x))`."),
        ("How does an undo stack stay cheap with immutable state?",
         "Each state is a new value that shares unchanged parts with the old one, so keeping history is just keeping references."),
        ("What is `Readonly<T>`?",
         "A mapped type that marks every property of `T` `readonly` — one level deep only."),
        ("Why prefer parsing to validating?",
         "A parser returns a narrower type (`Email`, not `string`), so later code can't forget the check was done — the type carries the proof."),
        ("TS2540 — cause?",
         "\"Cannot assign to 'x' because it is a read-only property.\""),
    ],
    17: [
        ("What does `Partial<T>` do?",
         "Makes every property of `T` optional — the natural type for an update or patch."),
        ("`Pick<T, K>` vs `Omit<T, K>` — which checks its keys?",
         "`Pick` requires `K extends keyof T` (a typo is TS2344). `Omit` accepts any key, so a typo omits nothing, silently."),
        ("Does `Omit<User, \"password\">` remove `password` at runtime?",
         "No. `return { ...user }` typed as the `Omit` still contains the password. You must actually delete or not copy it."),
        ("What is `Record<K, V>`?",
         "An object type with keys `K` and values `V`: `Record<\"a\" | \"b\", number>` is `{ a: number; b: number }`."),
        ("`Exclude<U, X>` vs `Extract<U, X>`?",
         "`Exclude` removes the union members assignable to `X`; `Extract` keeps only those."),
        ("What does `NonNullable<T>` remove?",
         "`null` and `undefined` from `T`."),
        ("How do you get a function's return type without repeating it?",
         "`ReturnType<typeof fn>`. And `Parameters<typeof fn>` gives its parameter tuple."),
        ("What does `Awaited<Promise<Promise<number>>>` give?",
         "`number` — `Awaited` unwraps promises recursively, like `await` does."),
        ("What does `Required<T>` do?",
         "Removes `?` from every property of `T`."),
        ("Why derive `TaskDraft` from `Task` instead of writing it out?",
         "One source of truth: add a field to `Task` and every derived type updates. Hand-written copies drift apart."),
        ("Composition over inheritance — in one line?",
         "Build behaviour by combining small functions and objects, rather than extending a class hierarchy."),
        ("TS2344 — cause?",
         "A type argument doesn't satisfy its constraint, e.g. `Pick<User, \"nope\">`."),
    ],
    18: [
        ("What problem do generics solve?",
         "Reusing code across types without losing precision: `first<T>(xs: T[]): T | undefined` returns a `number` for a `number[]`, not `any`."),
        ("How are type arguments usually supplied?",
         "Inferred from the arguments: `first([1, 2])` infers `T = number`. Pass them explicitly only when inference can't see them."),
        ("What does `<T extends { id: string }>` mean?",
         "`T` can be any type, as long as it has a string `id` — so the body may use `x.id`."),
        ("What does `K extends keyof T` give you?",
         "A key that really exists on `T`, so `obj[key]` is typed `T[K]` — the value type for that exact key."),
        ("Smell: a type parameter used only once. Why?",
         "It adds nothing — `<T>(x: T): void` is just `(x: unknown): void`. A generic earns its place by linking two positions."),
        ("What is a generic default?",
         "`<T = string>` — the type used when `T` is neither passed nor inferable."),
        ("Why might `T extends object` surprise you?",
         "Arrays and functions are objects too, so they satisfy it."),
        ("What does TS2322 \"'T' could be instantiated with an arbitrary type\" mean?",
         "You returned a specific type where the caller chose `T`. The body must work for *every* `T`, not just the one you had in mind."),
        ("What does a `const` type parameter do (TS 5.0)?",
         "`<const T>` infers literal types for arguments, as if the caller wrote `as const` — `f([\"a\", \"b\"])` infers `readonly [\"a\", \"b\"]`."),
        ("What is `NoInfer<T>` for (TS 5.4)?",
         "Blocking inference from one argument, so `T` is decided by the others — e.g. a default value that must match the options list."),
        ("How do you type a generic `groupBy`?",
         "`function groupBy<T, K extends PropertyKey>(xs: T[], key: (x: T) => K): Map<K, T[]>`."),
        ("Generic class — how is `T` fixed?",
         "At construction: `new Stack<number>()`, or inferred from constructor arguments."),
    ],
    19: [
        ("What does `keyof T` produce?",
         "The union of `T`'s property names: `keyof { a: 1; b: 2 }` is `\"a\" | \"b\"`."),
        ("What is an indexed access type?",
         "`T[K]` — the type of property `K` on `T`. `Person[\"age\"]` is `number`."),
        ("How do you get the element type of an array type?",
         "`T[number]` — `string[][number]` is `string`."),
        ("Type-position `typeof` vs runtime `typeof`?",
         "In a type (`typeof defaults`) it takes a variable's static type; in an expression it returns a runtime string like `\"number\"`."),
        ("How do you derive a key union from an object value?",
         "`keyof typeof settings`."),
        ("How do you get the union of an object's value types?",
         "`T[keyof T]`."),
        ("`keyof` an object with a string index signature?",
         "`string | number` — number keys are allowed too, because JavaScript turns them into strings."),
        ("What is `PropertyKey`?",
         "`string | number | symbol` — everything that can be an object key."),
        ("How is `function get<T, K extends keyof T>(obj: T, k: K): T[K]` better than returning `any`?",
         "The return type follows the key: `get(user, \"age\")` is a `number`, `get(user, \"name\")` a `string`."),
        ("Why is `Object.keys(obj) as (keyof T)[]` a white lie?",
         "At runtime the object may have extra keys; the cast is fine only when you control how the object was built."),
        ("`keyof {}`?",
         "`never` — an empty object type has no known keys."),
        ("TS7053 — cause?",
         "Indexing an object with a `string` its type doesn't declare an index signature for: \"Element implicitly has an 'any' type…\"."),
    ],
    20: [
        ("What is a mapped type?",
         "A type built by looping over keys: `{ [K in keyof T]: … }`."),
        ("How would you write `Partial<T>` yourself?",
         "`type MyPartial<T> = { [K in keyof T]?: T[K] }`."),
        ("How do you remove `readonly` or `?` in a mapped type?",
         "With a minus modifier: `{ -readonly [K in keyof T]-?: T[K] }`."),
        ("What is key remapping?",
         "An `as` clause renaming keys: `` { [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K] } ``."),
        ("How do you filter keys out in a mapped type?",
         "Remap the unwanted ones to `never`: `[K in keyof T as T[K] extends Function ? never : K]`."),
        ("What is a homomorphic mapped type?",
         "One that maps over `keyof T` directly; it preserves `T`'s `readonly` and `?` modifiers."),
        ("How would you write `Pick<T, K>` yourself?",
         "`type MyPick<T, K extends keyof T> = { [P in K]: T[P] }`."),
        ("How would you write `Record<K, V>` yourself?",
         "`type MyRecord<K extends PropertyKey, V> = { [P in K]: V }`."),
        ("Why does `Readonly<T>` not protect nested objects?",
         "It maps one level only. A `DeepReadonly` recurses: `{ readonly [K in keyof T]: DeepReadonly<T[K]> }`."),
        ("Why does `string & K` appear inside `Capitalize<…>` in a remap?",
         "`keyof T` may include `number` and `symbol`; `Capitalize` accepts only strings, so intersecting keeps the string keys."),
        ("Do mapped types exist at runtime?",
         "No. If you need the object they describe, you build it yourself — the type only checks that you did."),
        ("What does `{ [K in \"a\" | \"b\"]: number }` produce?",
         "`{ a: number; b: number }`."),
    ],
    21: [
        ("What is a conditional type?",
         "`T extends U ? X : Y` — a type-level if/else that picks `X` when `T` is assignable to `U`."),
        ("What does `infer` do?",
         "Declares a type variable to be captured by the match: `T extends Promise<infer V> ? V : T` extracts the promise's value type."),
        ("How would you write `ReturnType` yourself?",
         "`type MyReturn<F> = F extends (...args: any[]) => infer R ? R : never`."),
        ("What is a distributive conditional type?",
         "When the checked type is a naked type parameter, a union input is split and each member is checked separately: `Exclude` works this way."),
        ("How do you stop distribution?",
         "Wrap both sides in tuples: `[T] extends [U] ? X : Y`."),
        ("What does a distributive conditional return for `never`?",
         "`never` — an empty union distributes over zero members."),
        ("How would you write `Exclude<T, U>` yourself?",
         "`type MyExclude<T, U> = T extends U ? never : T`."),
        ("How do you get the element type of an array, or `T` itself if it isn't one?",
         "`type Unwrap<T> = T extends (infer E)[] ? E : T`."),
        ("What does `infer U extends string` add (TS 4.7)?",
         "A constraint on the inferred type: the branch matches only if what `U` captures is a `string`."),
        ("Why does a function returning a conditional type usually need a cast inside?",
         "The compiler can't evaluate the conditional for an unresolved generic `T`, so it can't check your return value against it."),
        ("How do you test whether `T` is `never`?",
         "`[T] extends [never] ? true : false` — the bare `T extends never` distributes and returns `never`."),
        ("How would you write `Awaited` for one level?",
         "`type Unpromise<T> = T extends Promise<infer V> ? V : T`."),
    ],
    22: [
        ("What is a template literal type?",
         "A string type built from other types: `` `${Entity}:${Action}` `` — every combination of the two unions."),
        ("How many members does `` `${\"a\" | \"b\"}-${\"x\" | \"y\" | \"z\"}` `` have?",
         "Six — template literals take the cartesian product of the unions."),
        ("Name the four intrinsic string types.",
         "`Uppercase`, `Lowercase`, `Capitalize`, `Uncapitalize`."),
        ("How do you parse a string type?",
         "Match it with `infer` in a template: `` S extends `${infer Head}/${infer Rest}` ? … : … ``."),
        ("How do you extract `\"id\"` from the route `\"/users/:id\"` at the type level?",
         "Recursively match `` `${string}:${infer P}/${infer Rest}` `` (and a final `` `${string}:${infer P}` ``), collecting each `P` into a union."),
        ("What is a recursive type?",
         "One that refers to itself: `type Json = string | number | boolean | null | Json[] | { [k: string]: Json }`."),
        ("What is TS2589?",
         "\"Type instantiation is excessively deep and possibly infinite\" — a recursive type went past the compiler's depth limit."),
        ("How do you reverse a tuple type?",
         "`type Reverse<T extends unknown[]> = T extends [infer H, ...infer R] ? [...Reverse<R>, H] : []`."),
        ("How do you get a tuple's length as a type?",
         "`T[\"length\"]` — for `[1, 2, 3]` it is the literal `3`."),
        ("What happens when you recurse on plain `string` instead of a literal?",
         "It never matches a specific pattern, so the result collapses to a wide type (usually `string` or `never`)."),
        ("What is `Paths<T>` used for?",
         "Typing dotted paths into an object (`\"a.b.c\"`) so a `get(obj, path)` helper rejects paths that don't exist."),
        ("Why keep type-level programs small?",
         "They slow the compiler, error messages grow unreadable, and depth limits bite. Reach for them where they remove real bugs."),
    ],
    23: [
        ("`private` vs `#private`?",
         "`private` is compile-time only — the field is a normal property at runtime. `#field` is truly private, enforced by JavaScript."),
        ("What is a class invariant?",
         "A rule that holds after every public method, e.g. \"balance is never negative\". Private state plus checked methods enforce it."),
        ("What does `implements` check?",
         "That the class has every member of the interface. It does not inherit anything or change the class's type."),
        ("When does `protected` make sense?",
         "When a subclass needs access but outside code shouldn't — it means nothing without a subclass."),
        ("What does `override` guard against?",
         "Typos and base-class renames: with `noImplicitOverride`, a method that doesn't really override anything is an error."),
        ("Can you instantiate an `abstract` class?",
         "No (TS2511). It exists to be extended; `abstract` methods have to be implemented by subclasses."),
        ("Why can a detached method crash?",
         "`const f = obj.method; f()` calls it with `this` undefined. Bind it, wrap it in an arrow, or define it as an arrow field."),
        ("Why are parameter properties (`constructor(private x: number)`) graded by type-check only here?",
         "They emit an assignment, so they aren't erasable — Node's strip-only mode refuses them."),
        ("What does a getter give you over a plain field?",
         "A computed, read-only view: `get balance() { return this.#balance; }` — callers can read, not write."),
        ("Classes are structural too — what does that mean?",
         "An object literal with the same public members is assignable to the class type; `instanceof` is the check that really needs the class."),
        ("When is a discriminated union better than a class hierarchy?",
         "When the set of variants is closed and you mostly *switch* on them — exhaustiveness checking beats virtual dispatch there."),
        ("What is a static factory?",
         "`static from(raw: string): Account | null` — a named constructor that can validate and fail, which `new` cannot."),
    ],
    24: [
        ("What makes an object iterable?",
         "A `[Symbol.iterator]()` method returning an iterator — an object with `next()` returning `{ value, done }`."),
        ("What is a generator?",
         "A `function*` that `yield`s values lazily; calling it returns an iterator that runs the body on demand."),
        ("Why can a generator describe an infinite sequence safely?",
         "Nothing runs until a value is asked for — `take(naturals(), 5)` computes only five."),
        ("What does `yield*` do?",
         "Delegates to another iterable, yielding each of its values in turn — handy for recursive tree traversal."),
        ("Can a generator be iterated twice?",
         "No — it is a one-shot iterator. Call the generator function again for a fresh one."),
        ("What is the `Generator<T, TReturn, TNext>` type?",
         "The yielded type, the final `return` type, and the type `next(value)` accepts."),
        ("What hangs: spreading which kind of iterator?",
         "An infinite one — `[...naturals()]` never finishes."),
        ("Why is `queue.shift()` a trap in BFS?",
         "`shift` is O(n) — it moves every remaining element. Use a head index into the array, or a ring buffer."),
        ("How do you make a `LinkedList<T>` work with `for…of`?",
         "Give it `*[Symbol.iterator]() { for (let n = this.head; n; n = n.next) yield n.value; }`."),
        ("What does a binary heap give you?",
         "O(log n) insert and remove-min, with O(1) peek — the engine of a priority queue."),
        ("How does a generic priority queue know what \"smaller\" means?",
         "It takes a comparator, `(a: T, b: T) => number`, in its constructor."),
        ("What are iterator helpers (ES2025)?",
         "`map`, `filter`, `take`, `drop`, `flatMap`, `reduce`, `toArray` directly on iterators — lazy pipelines without writing generators."),
    ],
    25: [
        ("What is the type of `e` in `catch (e)` under `strict`?",
         "`unknown` (`useUnknownInCatchVariables`). Narrow it — `e instanceof Error` — before reading `e.message`."),
        ("Throw or return a `Result`?",
         "Return a `Result` for failures the caller is expected to handle (bad input); throw for bugs and truly exceptional states."),
        ("What is `Error.cause` for?",
         "Chaining: `throw new Error(\"load failed\", { cause: err })` keeps the original error attached."),
        ("What does `finally` do if the `try` returns?",
         "It still runs — and a `return` inside `finally` overrides the `try`'s return, which is almost always a bug."),
        ("Write a `Result<T, E>` type.",
         "`type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };` — a discriminated union on `ok`."),
        ("Why can't you read `r.value` before checking `r.ok`?",
         "On the failure branch there is no `value` property at all, so the compiler refuses until `ok` has narrowed the union."),
        ("What does `andThen` (flatMap) on a `Result` do?",
         "Runs the next fallible step on a success; passes a failure through untouched — so a chain of steps reads straight down."),
        ("Why throw `Error` objects instead of strings?",
         "An `Error` carries a message, a name and a stack; `throw \"oops\"` carries nothing, and `e instanceof Error` fails for it."),
        ("What is `AggregateError`?",
         "An error holding several errors in `.errors` — what `Promise.any` rejects with, and handy for batch validation."),
        ("Fail fast or collect all errors?",
         "Fail fast when later steps depend on earlier ones; collect all when the user should fix everything in one go (form or config validation)."),
        ("How do you name a custom error class so logs say what happened?",
         "`class ValidationError extends Error { name = \"ValidationError\"; }` — the name prefixes the message in `String(err)` and stacks."),
        ("What is wrong with an empty `catch {}`?",
         "It swallows every error — including the bugs you never anticipated. Catch only what you can handle."),
    ],
    26: [
        ("What does `await` do?",
         "Pauses the async function until the promise settles, then resumes with its value — or throws its rejection."),
        ("`Promise.all` vs `Promise.allSettled`?",
         "`all` rejects as soon as one promise rejects; `allSettled` waits for every one and reports each as fulfilled or rejected."),
        ("`Promise.race` vs `Promise.any`?",
         "`race` settles with the first promise to settle, success or failure; `any` resolves with the first success, rejecting only if all fail."),
        ("Why is `await` inside a `for` loop sometimes slow?",
         "It runs the operations one after another. Start them all and `await Promise.all(...)` to run them concurrently."),
        ("What goes wrong with `items.forEach(async (x) => { await save(x); })`?",
         "`forEach` ignores the returned promises — nothing waits for the saves, and their errors go unhandled."),
        ("What is `async function f(): Promise<number>`'s return type if the body returns `5`?",
         "`Promise<number>` — an async function always returns a promise."),
        ("How do you keep async output deterministic?",
         "Collect the results and print them in input order — never let completion timing decide the output order."),
        ("How do you add a timeout to a promise?",
         "Race it against a timer that rejects: `Promise.race([work, timeout(ms)])`, or pass `AbortSignal.timeout(ms)` to an API that accepts a signal."),
        ("Print order: `setTimeout(a)`, `Promise.resolve().then(b)`, `console.log(c)`?",
         "`c`, then `b`, then `a` — synchronous code, then microtasks (promise reactions), then timers."),
        ("How does cancellation work with an `AbortController`?",
         "`controller.abort()` marks `controller.signal` aborted and fires its `abort` event; the work must check the signal and stop — it is cooperative."),
        ("How do you run 10 jobs with at most 2 at a time?",
         "A pool: start 2 workers, and have each take the next job index when it finishes, until none are left."),
        ("What does `Promise.withResolvers()` give you?",
         "`{ promise, resolve, reject }` — a promise plus the functions that settle it, without nesting code in `new Promise(...)`."),
    ],
    27: [
        ("Interview: `any` vs `unknown` vs `never`, one line each?",
         "`any` turns checking off; `unknown` is any value you must narrow before use; `never` is the type with no values — unreachable code, impossible cases."),
        ("Interview: `interface` or `type`?",
         "Either for object shapes; `interface` can be merged and extended, `type` can also name unions, tuples and mapped types. Pick one convention per codebase."),
        ("Interview: what is structural typing?",
         "Compatibility is decided by shape, not by name — any value with the right members fits, whatever it was declared as."),
        ("Interview: what does `satisfies` add over an annotation?",
         "It checks the value against a type but keeps the value's own, narrower inferred type."),
        ("Interview: how do you type a value parsed from JSON?",
         "As `unknown`, then validate it — a type predicate or a schema — so the type is earned, not asserted."),
        ("Interview: what is a discriminated union for?",
         "Modelling \"one of these cases\", each with its own data; switching on the tag narrows, and a `never` check makes the switch exhaustive."),
        ("Interview: how do generics differ from `any`?",
         "A type parameter links types together (input element type = output element type); `any` throws that information away."),
        ("Interview: what is a branded type?",
         "A primitive intersected with a phantom tag (`string & { __brand: \"UserId\" }`) so two structurally identical ids cannot be mixed up."),
        ("Interview: why is `enum` discouraged in modern TypeScript?",
         "It is not erasable syntax — it emits runtime code — and a literal union (`\"a\" | \"b\"`) does the job with no runtime cost."),
        ("Interview: how would you test a type?",
         "`type _ = Expect<Equal<Actual, Expected>>` for positive claims and `// @ts-expect-error` above a line that must be rejected — both run as part of `tsc`."),
        ("Interview: what does `noUncheckedIndexedAccess` change, and why turn it on?",
         "Every index read becomes `T | undefined`, so out-of-range reads must be handled — the type finally tells the truth about arrays and records."),
        ("Interview: `Promise.all` or `Promise.allSettled`?",
         "`all` when one failure should fail the whole operation; `allSettled` when every outcome matters on its own — e.g. reporting each resource."),
    ],
}

_seen_fronts = set()
for _tsw in TS_WEEKS:
    _cards = TS_CARDS.get(_tsw["week"], [])
    assert len(_cards) >= 12, f"TS week {_tsw['week']}: needs 12 review cards, has {len(_cards)}"
    for _front, _back in _cards:
        assert _front not in _seen_fronts, f"TS week {_tsw['week']}: duplicate card front {_front!r}"
        assert _front.strip() and _back.strip(), f"TS week {_tsw['week']}: empty card"
        _seen_fronts.add(_front)
    _tsw["flashcards"] = [{"front": f, "back": b} for (f, b) in _cards]
