# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# End-of-week quiz banks for the TypeScript Mastery track — deeper and cleaner.
#
# Two problems with the banks as they were:
#
#  * Too small. 5-10 questions a week with 4 drawn per sitting meant a learner
#    had seen the whole bank after two retakes, so passing measured memory of
#    the paper, not the week.
#  * Duplicated. Weeks 11-26 had been authored with their own questions, and the
#    chapters they schedule later gained a chapter quiz asking the same things
#    in slightly different words. `_finalize_mastery` dedupes on exact text only,
#    so both copies landed in the bank — 31 pairs — and one sitting could draw a
#    question and its twin. The week's copy is dropped (TS_QUIZ_DROP); the
#    chapter's, usually the fuller one, stays.
#
# After this every TypeScript week has a bank of at least 16 distinct questions
# and a sitting draws 8, so passing at 75% means 6 of 8.
#
# Questions are written with the correct answer first; the UI shuffles options
# (and questions) on every sitting. exec()'d inside gen_seed.py's namespace
# after mastery_defs.py, so `_q` and TS_WEEKS exist; the chapter questions are
# merged in afterwards by `_finalize_mastery`.
# ---------------------------------------------------------------------------


def _mq(question, answer, wrong, explanation):
    """A question with the correct option first (the UI shuffles options)."""
    return _q(question, [answer] + list(wrong), 0, explanation)


TS_QUIZ_SAMPLE = 8

# Authored week questions that duplicate a chapter-quiz question the week
# already draws on. Exact text, so a rewording upstream fails the build here
# instead of quietly bringing the twin back.
TS_QUIZ_DROP = {
    6: ["What is the type of `const add = (a: number) => (b: number) => a + b`?",
        "Why does `[\"a\"].map((s) => s.length)` type-check when map passes three arguments?"],
    11: ["Why does `function isPerson(x: unknown): boolean` fail to narrow?",
         "`function isPerson(x: unknown): x is Person { return true; }` — the compiler…",
         "What does `asserts x is string` do?"],
    12: ["Why must the discriminant be a literal type?",
         "You add a new variant. What does `const exhaustive: never = value` in the default branch do?",
         "What is the advantage over one object with all fields optional?"],
    14: ["With `strictNullChecks` on, what does `string` mean?",
         "What does `noUncheckedIndexedAccess` change?"],
    15: ["What does `satisfies` do that an annotation does not?",
         "Why is `const p: Point = { x: 1, y: 2, label: \"h\" }` an error when assigning the same object via a variable is not?",
         "Two unrelated aliases with identical members — is one assignable to the other?",
         "What makes a class partly nominal?"],
    16: ["Why should exactly one function apply the `as UserId` cast?"],
    18: ["Why is `<T extends { length: number }>` better than a plain `{ length: number }` parameter?",
         "In `get<T, K extends keyof T>(obj: T, key: K): T[K]`, what is `T[K]`?",
         "What does a type-parameter default like `<T = string>` do?"],
    19: ["Drop the `as const`. What does it become?",
         "How does type-position `typeof` differ from the runtime operator?"],
    20: ["In an `as` clause, what happens to a key mapped to `never`?",
         "You define `Getters<T>` renaming keys to getName/getAge. What exists at runtime?"],
    21: ["What does `infer` do?",
         "How do you STOP a conditional type distributing?"],
    22: ["How many members does `` `${\"a\" | \"b\"}-${\"x\" | \"y\" | \"z\"}` `` have?"],
    24: ["What happens the second time you iterate the same generator object?",
         "Why does `take(naturals(), 4)` terminate?",
         "Why type `pop()` as `T | undefined` rather than `T`?"],
    25: ["What makes `Result<T, E>` enforce handling?",
         "What is the total time of `await Promise.all(ids.map(fetchOne))` versus awaiting in a loop?",
         "How does `Promise.race` differ from `Promise.any`?"],
}

TS_QUIZ_MORE = {
    1: [
        _mq("What type does TypeScript infer for `const names = [\"a\", \"b\"]`?",
            "`string[]`", ["`[\"a\", \"b\"]`", "`readonly string[]`", "`any[]`"],
            "The array is mutable, so its elements widen to `string` — it could hold other strings later. `as const` is what keeps the literal tuple."),
        _mq("Which of these is NOT one of JavaScript's primitive types?",
            "`object`", ["`symbol`", "`bigint`", "`undefined`"],
            "The primitives are string, number, bigint, boolean, symbol, undefined and null. Objects (including arrays and functions) are not primitives."),
        _mq("`const n: number = Number(\"abc\");` — what happens?",
            "It compiles, and `n` is `NaN` at runtime", ["A compile error", "`n` is 0", "It throws at runtime"],
            "`Number(...)` is typed to return `number`, and `NaN` *is* a number. Types can't tell you a parse failed — you have to check with `Number.isNaN`."),
        _mq("What does the judge do with your type annotations when it runs your program?",
            "Type-checks them first, then strips them and runs the plain JavaScript that is left",
            ["Turns them into runtime checks", "Ignores them completely", "Compiles them into bytecode that enforces them"],
            "Types are a compile-time check. Once the program passes, the annotations are deleted and what runs is JavaScript."),
        _mq("`const price = 9.99; price = 10;` — result?",
            "Compile error: you cannot assign to a `const`", ["`price` becomes 10", "A warning only", "It only fails at runtime"],
            "`const` bindings cannot be reassigned (TS2588). Use `let` for values that genuinely change."),
        _mq("Which annotation is redundant?",
            "`const total: number = 1 + 2;`",
            ["`function area(w: number, h: number)`", "`let result: string | null = null;`", "`const items: string[] = [];`"],
            "`1 + 2` already infers `number`. Parameters can't be inferred, a `null` initializer would infer only `null`, and an empty array gives no element type — those annotations add information."),
        _mq("`const input = fs.readFileSync(0, \"utf8\")` — what is `input`'s type?",
            "`string`", ["`Buffer`", "`string | undefined`", "`any`"],
            "Passing an encoding selects the overload that returns a decoded `string`."),
        _mq("What are `Number(\"3\") + Number(\"4\")` and `\"3\" + \"4\"`?",
            "`7` and `\"34\"`", ["`7` and `7`", "`\"34\"` and `\"34\"`", "A compile error for both"],
            "`+` adds numbers but concatenates when either side is a string. Parse input before doing arithmetic on it."),
        _mq("What is the type of `x` in `const x = Math.random() > 0.5 ? \"yes\" : 42`?",
            "`\"yes\" | 42`", ["`string | number`", "`any`", "`unknown`"],
            "A `const` keeps literal types, so each branch contributes its literal and the result is their union."),
        _mq("You have `const v: unknown = getValue();`. What happens on `v.toString()`?",
            "Compile error — `v` must be narrowed first", ["It compiles and returns `unknown`", "It compiles; `unknown` behaves like `any`", "It is converted to a string automatically"],
            "`unknown` allows almost nothing until you prove what the value is (TS18046). That is exactly its advantage over `any`."),
        _mq("Which declaration keyword has no place in modern TypeScript code?",
            "`var`", ["`let`", "`const`", "`type`"],
            "`var` is function-scoped and hoisted, which causes the classic closure-in-a-loop bug. `let` and `const` are block-scoped."),
        _mq("`let total = 0; total += \"5\";` — what happens?",
            "Compile error: `string` is not assignable to `number`", ["`total` becomes 5", "`total` becomes `\"05\"`", "A runtime error"],
            "In plain JavaScript this would produce the string `\"05\"`. TypeScript knows `total` is a `number` and rejects the assignment."),
    ],
    2: [
        _mq("Under TypeScript, what happens to `const r = \"5\" - 2;`?",
            "Compile error: arithmetic needs number operands", ["`r` is 3", "`r` is `\"52\"`", "`r` is `NaN`"],
            "JavaScript would coerce and give 3, but TypeScript rejects `-` on a string (TS2362). It does allow `+`, which concatenates."),
        _mq("`const r = \"5\" + 2;` — does it compile, and what is `r`?",
            "Yes — `r` is the string `\"52\"`", ["No — compile error", "Yes — `r` is 7", "Yes — `r` is `NaN`"],
            "`+` with a string operand is concatenation, which TypeScript allows and types as `string`."),
        _mq("What does `!!\"false\"` evaluate to?",
            "`true`", ["`false`", "`\"false\"`", "A compile error"],
            "Any non-empty string is truthy — including the text `\"false\"`."),
        _mq("What are `null ?? \"x\"` and `0 ?? \"x\"`?",
            "`\"x\"` and `0`", ["`\"x\"` and `\"x\"`", "`null` and `0`", "`\"x\"` and `null`"],
            "`??` only replaces `null` and `undefined`; `0` is a real value and is kept."),
        _mq("In `a && b`, when is `b` evaluated?",
            "Only when `a` is truthy", ["Always", "Only when `a` is falsy", "Only when `b` is a boolean"],
            "`&&` short-circuits: a falsy `a` is returned immediately and `b` never runs."),
        _mq("`x > 0 ? \"pos\" : x < 0 ? \"neg\" : \"zero\"` when `x` is `NaN`?",
            "`\"zero\"`", ["`\"pos\"`", "`\"neg\"`", "It throws"],
            "Every comparison with `NaN` is false, so both tests fail and the last branch wins — handle `NaN` explicitly."),
        _mq("Which is the correct leap-year test?",
            "`(y % 4 === 0 && y % 100 !== 0) || y % 400 === 0`",
            ["`y % 4 === 0`", "`y % 4 === 0 && y % 400 === 0`", "`y % 100 !== 0 || y % 400 === 0`"],
            "Every 4th year, except centuries — unless the century is divisible by 400."),
        _mq("How does `switch (true) { case score >= 90: … }` work?",
            "Each `case` expression is evaluated and compared to `true` with `===`",
            ["It is a syntax error", "Cases are compared with `==`", "Only the first case is ever checked"],
            "`switch` uses strict equality, so a case matches when its boolean expression is exactly `true`."),
        _mq("`if (x = 5) { … }` — what does TypeScript do?",
            "It compiles; the assignment happens and the branch always runs",
            ["Compile error: use `===`", "It compares `x` to 5", "It throws at runtime"],
            "An assignment is an expression whose value is the assigned value. TypeScript doesn't flag it, so this classic typo slips through — use `===`."),
        _mq("What is `typeof NaN`?",
            "`\"number\"`", ["`\"NaN\"`", "`\"undefined\"`", "`\"object\"`"],
            "NaN is a numeric value — the result of an invalid number operation."),
        _mq("Which is a safe equality test for two computed floats?",
            "`Math.abs(a - b) < 1e-9`", ["`a === b`", "`a == b`", "`Object.is(a, b)`"],
            "Rounding error makes exact equality unreliable; compare against a small tolerance."),
    ],
    3: [
        _mq("How many times does `for (let i = 0; i <= 10; i += 2)` run its body?",
            "6", ["5", "10", "11"],
            "i takes 0, 2, 4, 6, 8, 10 — six values, because the bound is inclusive."),
        _mq("A digit counter loops `while (n > 0) { n = Math.trunc(n / 10); count++; }`. What does it give for `n = 0`?",
            "0 — the loop never runs, so 0 needs special handling", ["1", "It loops forever", "`NaN`"],
            "Zero has one digit, but the loop condition is false straight away. Edge cases like this are why tests include 0."),
        _mq("What does `break` inside the inner of two nested loops exit?",
            "Only the inner loop", ["Both loops", "The whole function", "Only the current iteration"],
            "`break` exits the innermost loop. Use a labelled break (`outer: for …` / `break outer`) to leave both."),
        _mq("What is `5 / 0` in JavaScript?",
            "`Infinity`", ["A thrown error", "`NaN`", "`0`"],
            "Division by zero doesn't throw; it gives `Infinity` (or `-Infinity`). `0 / 0` is `NaN`."),
        _mq("What is `10 % 3.5`?",
            "`3`", ["`1`", "`0.5`", "A compile error"],
            "`%` works on fractions too: 10 − 2 × 3.5 = 3."),
        _mq("Is `2 ** 53 + 1 === 2 ** 53` true or false?",
            "True — above 2^53 not every integer is representable", ["False", "A compile error", "It throws a RangeError"],
            "2^53 + 1 rounds back to 2^53. Past `Number.MAX_SAFE_INTEGER`, use `bigint`."),
        _mq("`const big = 123n + 1;` — what happens?",
            "Compile error: `bigint` and `number` can't be mixed", ["`124n`", "`124`", "`\"123n1\"`"],
            "Mixing the two in arithmetic is rejected (TS2365). Write `123n + 1n`, or convert with `BigInt(1)`."),
        _mq("What sums 1..n in constant time?",
            "`n * (n + 1) / 2`", ["`n * n / 2`", "`(n + 1) / 2`", "`n ** 2 + 1`"],
            "Gauss's formula — no loop needed."),
        _mq("`Number.parseFloat(\"3.14abc\")`?",
            "`3.14`", ["`NaN`", "`3`", "A compile error"],
            "`parseFloat` reads the longest valid numeric prefix; `Number(\"3.14abc\")` would be `NaN`."),
        _mq("What does `continue` do inside a loop?",
            "Skips the rest of this iteration and moves to the next", ["Exits the loop", "Restarts the loop from the first iteration", "Nothing outside a switch"],
            "It jumps to the next iteration (running the `for` update step first)."),
        _mq("`for (const x of [1, 2, 3]) x = x * 2;` — what happens?",
            "Compile error: `x` is a `const`", ["The array becomes [2, 4, 6]", "Nothing — it runs and changes nothing", "A runtime TypeError only"],
            "Each iteration gets a fresh `const` binding, which can't be reassigned (TS2588). Reassigning a `let` copy wouldn't change the array either."),
    ],
    4: [
        _mq("Does `s.toUpperCase()` change `s`?",
            "No — it returns a new string", ["Yes, in place", "Only if `s` was declared with `let`", "Only for ASCII strings"],
            "Strings are immutable; every string method returns a new string."),
        _mq("`\"hello\".indexOf(\"z\")`?",
            "`-1`", ["`undefined`", "`null`", "`0`"],
            "`indexOf` returns -1 when the substring isn't found."),
        _mq("`\"a-b-c\".split(\"-\", 2)`?",
            "`[\"a\", \"b\"]`", ["`[\"a\", \"b-c\"]`", "`[\"a\", \"b\", \"c\"]`", "`[\"a-b\", \"c\"]`"],
            "The second argument caps how many pieces are returned; the rest is discarded, not joined."),
        _mq("`\"x\".repeat(3)`?",
            "`\"xxx\"`", ["`[\"x\", \"x\", \"x\"]`", "`\"x3\"`", "`3`"],
            "`repeat(n)` concatenates the string n times."),
        _mq("Under plain `strict`, what are the runtime value and static type of `\"Hello\"[10]`?",
            "`undefined` at runtime, but typed `string`", ["`\"\"`, typed `string`", "A thrown RangeError", "`undefined`, typed `undefined`"],
            "Out-of-range indexing gives `undefined`, but the type says `string` unless `noUncheckedIndexedAccess` is on — a gap you'll close later in the course."),
        _mq("`\"abc\".includes(\"\")`?",
            "`true`", ["`false`", "A compile error", "`-1`"],
            "The empty string is found at every position of every string."),
        _mq("`\" a b \".trim().split(\" \").length`?",
            "2", ["3", "4", "5"],
            "`trim` removes the outer spaces, leaving `\"a b\"`, which splits into two parts."),
        _mq("What does `\"Straße\".toUpperCase()` return?",
            "`\"STRASSE\"` — the string gets longer", ["`\"STRAßE\"`", "`\"STRAẞE\"`", "It throws"],
            "Case mapping is Unicode-aware; `ß` uppercases to `SS`, so lengths can change."),
        _mq("What is `` `${1 + 1}` ``?",
            "The string `\"2\"`", ["The number 2", "The string `\"1 + 1\"`", "A compile error"],
            "Template literal placeholders are evaluated, then converted to strings."),
        _mq("`/^\\d+$/.test(\"12a\")`?",
            "`false`", ["`true`", "`\"12\"`", "It throws"],
            "`^` and `$` anchor the pattern to the whole string, and `a` is not a digit."),
        _mq("`\"b\".localeCompare(\"a\")` returns…",
            "A positive number", ["A negative number", "0", "`true`"],
            "`localeCompare` returns negative, zero or positive — exactly the shape a sort comparator needs."),
        _mq("`\"a,b\".split(\"\")`?",
            "`[\"a\", \",\", \"b\"]`", ["`[\"a\", \"b\"]`", "`[\"a,b\"]`", "`[]`"],
            "Splitting on the empty string separates every character (by UTF-16 code unit)."),
    ],
    5: [
        _mq("`function f(x: number, y?: number) { return y ?? x; }` — what is `f(3)`?",
            "`3`", ["`undefined`", "`NaN`", "A compile error"],
            "`y` is omitted, so it's `undefined`, and `??` falls back to `x`."),
        _mq("`function greet(name = \"you\") { … }` — what does `greet(undefined)` use for `name`?",
            "`\"you\"` — passing `undefined` triggers the default", ["`undefined`", "A compile error", "`\"undefined\"`"],
            "Defaults apply whenever the argument is `undefined`, whether omitted or passed explicitly."),
        _mq("Can you call `const f = () => 1;` on a line above its declaration?",
            "No — it's in the temporal dead zone and throws a ReferenceError", ["Yes, arrows are hoisted", "Yes, but it returns `undefined`", "Only in strict mode"],
            "Only `function` declarations are hoisted with their body. A `const` exists from its declaration line on."),
        _mq("What return type is inferred for `function f(n: number) { if (n > 0) return \"pos\"; }`?",
            "`\"pos\" | undefined`", ["`string`", "`\"pos\"`", "`void`"],
            "One path returns `\"pos\"`, the other falls off the end and returns `undefined`."),
        _mq("Which type describes a function taking any number of strings and returning a string?",
            "`(...parts: string[]) => string`", ["`(parts: string) => string[]`", "`(...parts: string) => string`", "`(parts: ...string[]) => string`"],
            "A rest parameter collects the remaining arguments into an array, so it's typed as an array."),
        _mq("`const add = (a: number, b: number) => a + b; add(1, \"2\");` — result?",
            "Compile error: `string` is not assignable to `number`", ["`\"12\"`", "`3`", "`NaN`"],
            "Argument types are checked at every call (TS2345)."),
        _mq("Given overloads `parse(x: string): number` and `parse(x: string[]): number[]`, can you call `parse(v)` with `v: string | string[]`?",
            "No — callers see only the overloads, and neither accepts the union", ["Yes, the implementation signature accepts it", "Yes, it returns `number | number[]`", "Only with `as any`"],
            "The implementation signature is hidden. Add a third overload for the union, or use one union signature."),
        _mq("What does a function with no `return` statement return?",
            "`undefined`", ["`null`", "Nothing — calling it is an error", "`void` as a runtime value"],
            "Every call produces a value; without `return` it's `undefined`."),
        _mq("`function f(opts: { width?: number } = {})` — inside `f()`, what is `opts.width`?",
            "`undefined`", ["0", "A thrown TypeError", "`null`"],
            "The default makes `opts` an empty object, and a missing property reads as `undefined`."),
        _mq("Why is a pure function easier to test?",
            "Its output depends only on its inputs, so each test is just \"call it and compare\"",
            ["It runs faster", "It can't throw", "TypeScript checks it more strictly"],
            "No hidden state and no side effects means no setup and no ordering between tests."),
    ],
    6: [
        _mq("`[1, 2, 3].map((x) => x * 2).filter((x) => x > 2)`?",
            "`[4, 6]`", ["`[2, 4, 6]`", "`[3]`", "`[6]`"],
            "`map` gives [2, 4, 6]; `filter` keeps those above 2."),
        _mq("`for (var i = 0; i < 3; i++) setTimeout(() => console.log(i));` prints…",
            "`3 3 3`", ["`0 1 2`", "`0 0 0`", "`undefined` three times"],
            "`var` is one shared binding; by the time the callbacks run, `i` is 3. With `let`, each iteration has its own `i` and it prints 0 1 2."),
        _mq("What does a typical `once(fn)` helper return?",
            "A function that calls `fn` the first time and returns the cached result afterwards",
            ["The result of `fn()` immediately", "A promise", "A boolean saying whether `fn` has run"],
            "It closes over a flag and a cached value — a closure keeping private state."),
        _mq("What happens to `function fact(n: number): number { return n * fact(n - 1); }`?",
            "It never stops: no base case, so it overflows the stack", ["It returns 0", "It returns `NaN`", "Compile error: missing base case"],
            "TypeScript doesn't check termination. Without `if (n <= 1) return 1`, it recurses until `RangeError: Maximum call stack size exceeded`."),
        _mq("How does naive recursive Fibonacci's running time grow?",
            "Exponentially — roughly doubling with each n", ["Linearly", "Logarithmically", "Quadratically"],
            "Each call makes two more, recomputing the same values. Memoisation makes it linear."),
        _mq("`[].reduce((acc, x) => acc + x, 0)`?",
            "`0`", ["It throws", "`undefined`", "`NaN`"],
            "With an initial value, `reduce` over an empty array just returns it."),
        _mq("With `const compose = (f, g) => (x) => f(g(x))`, `double = x => x * 2` and `inc = x => x + 1`, what is `compose(double, inc)(3)`?",
            "8", ["7", "6", "9"],
            "`compose` applies right to left: inc(3) = 4, then double(4) = 8."),
        _mq("How do you type a callback that takes a number and returns a boolean?",
            "`(n: number) => boolean`", ["`function(number): boolean`", "`Function<number, boolean>`", "`(number) => boolean`"],
            "A function type names its parameters: `(n: number) => boolean`. `(number) => boolean` declares a parameter *named* `number` of type `any`."),
        _mq("`[3, 1, 2].sort((a, b) => b - a)`?",
            "`[3, 2, 1]`", ["`[1, 2, 3]`", "`[3, 1, 2]`", "`[2, 1, 3]`"],
            "A positive result puts `b` first, so `b - a` sorts descending."),
        _mq("`[].every((x) => x > 0)`?",
            "`true`", ["`false`", "`undefined`", "It throws"],
            "\"Every element passes\" is vacuously true when there are no elements. `some` on `[]` is `false`."),
        _mq("A recursive function recurses once per item on a list of a million items. What happens in Node?",
            "It likely fails with \"Maximum call stack size exceeded\" — rewrite it as a loop",
            ["It runs fine; Node optimises tail calls", "It runs, just slowly", "TypeScript refuses to compile it"],
            "Node doesn't eliminate tail calls, and the stack holds roughly ten thousand frames. Deep linear recursion should be a loop."),
    ],
    7: [
        _mq("`[1, 2, 3].slice(1)`?",
            "`[2, 3]`", ["`[1]`", "`[1, 2]`", "`2`"],
            "`slice(start)` copies from `start` to the end, leaving the original untouched."),
        _mq("`const a = [1, 2, 3]; a.splice(1, 1);` — what is `a` now?",
            "`[1, 3]`", ["`[1, 2, 3]`", "`[2]`", "`[1, 2]`"],
            "`splice(start, deleteCount)` removes in place (and returns the removed items)."),
        _mq("`[...\"ab\", ...\"cd\"]`?",
            "`[\"a\", \"b\", \"c\", \"d\"]`", ["`[\"ab\", \"cd\"]`", "`\"abcd\"`", "A compile error"],
            "Strings are iterable, so spreading one gives its characters."),
        _mq("`Array.from({ length: 3 }, (_, i) => i * i)`?",
            "`[0, 1, 4]`", ["`[1, 4, 9]`", "`[0, 0, 0]`", "`[undefined, undefined, undefined]`"],
            "`Array.from` calls the mapper with each index 0..length-1."),
        _mq("`[1, [2, [3]]].flat()`?",
            "`[1, 2, [3]]`", ["`[1, 2, 3]`", "`[1, [2, [3]]]`", "`[[1], [2], [3]]`"],
            "`flat()` flattens one level by default; `flat(Infinity)` goes all the way."),
        _mq("`const xs: readonly number[] = [1]; xs.push(2);` — what happens?",
            "Compile error: `push` doesn't exist on `readonly number[]`", ["`xs` becomes [1, 2]", "A runtime error only", "A warning"],
            "The readonly array type simply has no mutating methods."),
        _mq("`[0, 1, 2].findIndex((x) => x > 5)`?",
            "`-1`", ["`undefined`", "`3`", "`null`"],
            "`findIndex` returns -1 when nothing matches; `find` returns `undefined`."),
        _mq("`[1, 2, 3].indexOf(\"2\")` in TypeScript?",
            "Compile error: `string` is not assignable to `number`", ["`1`", "`-1`", "`undefined`"],
            "The argument must match the element type (TS2345) — which also stops you searching a number array for a string that will never be found."),
        _mq("What type does `const mixed = [1, \"a\"]` get?",
            "`(string | number)[]`", ["`[number, string]`", "`any[]`", "`[1, \"a\"]`"],
            "An array literal infers an array of the union of its element types — not a tuple."),
        _mq("What type does `const pair = [1, \"a\"] as const` get?",
            "`readonly [1, \"a\"]`", ["`(string | number)[]`", "`[number, string]`", "`readonly (1 | \"a\")[]`"],
            "`as const` makes it a read-only tuple of literal types."),
        _mq("`[5, 1, 10].sort((a, b) => a - b)`?",
            "`[1, 5, 10]`", ["`[1, 10, 5]`", "`[10, 5, 1]`", "`[5, 1, 10]`"],
            "The numeric comparator sorts numbers ascending (unlike the default string sort)."),
    ],
    8: [
        _mq("`const o = { a: 1 }; const p = o; p.a = 2;` — what is `o.a`?",
            "`2`", ["`1`", "A compile error", "`undefined`"],
            "`p` and `o` are two names for one object. Copy with `{ ...o }` when you need independence."),
        _mq("`{ ...{ a: 1, b: 2 }, a: 3 }`?",
            "`{ a: 3, b: 2 }`", ["`{ a: 1, b: 2 }`", "`{ a: [1, 3], b: 2 }`", "A compile error"],
            "Later properties overwrite earlier ones."),
        _mq("`JSON.stringify({ b: 1, a: 2 })`?",
            "`'{\"b\":1,\"a\":2}'`", ["`'{\"a\":2,\"b\":1}'`", "`'{b:1,a:2}'`", "`'[1,2]'`"],
            "Key order follows insertion order (for non-integer keys); nothing is sorted."),
        _mq("`JSON.parse(\"{'a': 1}\")`?",
            "It throws a SyntaxError — JSON needs double quotes", ["`{ a: 1 }`", "`{ \"a\": 1 }`", "`null`"],
            "JSON is stricter than JavaScript: keys and strings must use double quotes."),
        _mq("`Object.entries({ a: 1 })`?",
            "`[[\"a\", 1]]`", ["`[\"a\", 1]`", "`{ a: 1 }`", "`[[\"a\"], [1]]`"],
            "An array of `[key, value]` pairs."),
        _mq("`const { x: { y } } = { x: { y: 5 } };` — what is bound?",
            "`y`, with the value 5", ["`x` and `y`", "`x`, with the value `{ y: 5 }`", "Nothing — it's a syntax error"],
            "Nested destructuring binds only the leaf names; `x` here is a pattern, not a variable."),
        _mq("`{ name?: string }` vs `{ name: string | undefined }`?",
            "The first allows the key to be missing; the second requires the key, though its value may be `undefined`",
            ["They're identical", "The second allows the key to be missing", "The first allows `null`"],
            "Optional (`?`) is about presence; `| undefined` is about the value."),
        _mq("`interface A { x: number }` then `interface A { y: number }` — result?",
            "They merge: `A` has both `x` and `y`", ["Duplicate identifier error", "The second replaces the first", "`A` has only `x`"],
            "Declaration merging is unique to interfaces; this is how libraries let you extend their types."),
        _mq("`type A = { x: number }` then `type A = { y: number }` — result?",
            "Duplicate identifier error", ["They merge", "The second replaces the first", "`A` becomes a union"],
            "Type aliases can't be reopened; use an intersection to combine them."),
        _mq("What does `JSON.parse(JSON.stringify({ when: new Date(0) })).when` give back?",
            "The string `\"1970-01-01T00:00:00.000Z\"`, not a `Date`", ["A `Date`", "`0`", "`{}`"],
            "Dates serialise to ISO strings and come back as strings — revive them yourself."),
    ],
    9: [
        _mq("`new Map([[\"a\", 1]]).size`?",
            "`1`", ["`2`", "`undefined`", "A compile error"],
            "The constructor takes `[key, value]` pairs; there is one."),
        _mq("`new Set([1, 2, 2, 3]).size`?",
            "`3`", ["`4`", "`2`", "`1`"],
            "Duplicates are dropped."),
        _mq("Why can you write `map.set(\"a\", 1).set(\"b\", 2)`?",
            "`set` returns the map itself, so calls chain", ["`set` returns the value", "Chaining is special syntax for Maps", "You can't — it's a compile error"],
            "`Map.prototype.set` and `Set.prototype.add` both return the collection."),
        _mq("`[...new Map([[\"x\", 1], [\"y\", 2]]).keys()]`?",
            "`[\"x\", \"y\"]`", ["`[1, 2]`", "`[[\"x\", 1], [\"y\", 2]]`", "`{ x: 1, y: 2 }`"],
            "`keys()` returns an iterator of keys in insertion order."),
        _mq("After `if (map.has(k))`, why is `map.get(k)` still typed `V | undefined`?",
            "The compiler doesn't connect the two calls — `get` once and check the result instead",
            ["It isn't; `has` narrows `get`", "Because `k` might be `null`", "Because Map values are always optional"],
            "`has` returns a plain boolean. `const v = map.get(k); if (v !== undefined)` narrows properly."),
        _mq("What key groups anagrams together?",
            "The word's letters, sorted", ["The word's length", "The first letter", "The sum of its character codes"],
            "All anagrams sort to the same string (\"listen\" and \"silent\" both give \"eilnst\")."),
        _mq("`new Set([NaN, NaN]).size`?",
            "`1`", ["`2`", "`0`", "It throws"],
            "Sets use SameValueZero, under which `NaN` equals itself."),
        _mq("`new Set([0, -0]).size`?",
            "`1`", ["`2`", "`0`", "It throws"],
            "SameValueZero treats `0` and `-0` as equal."),
        _mq("What is the average cost of `set.has(x)`?",
            "O(1)", ["O(n)", "O(log n)", "O(n log n)"],
            "Hash-based lookup, independent of the set's size on average."),
        _mq("`Object.fromEntries(new Map([[\"a\", 1]]))`?",
            "`{ a: 1 }`", ["`[[\"a\", 1]]`", "`{}`", "A compile error"],
            "`fromEntries` accepts any iterable of pairs, including a Map."),
    ],
    10: [
        _mq("`type Dir = \"N\" | \"S\"; const d: Dir = \"E\";` — result?",
            "Compile error: `\"E\"` is not assignable to `Dir`", ["`d` is `\"E\"`", "`d` widens to `string`", "A runtime error only"],
            "A literal union lists every allowed value; anything else is rejected (TS2322)."),
        _mq("You have `const s: string` and `function move(d: Dir)`. What does `move(s)` do?",
            "Compile error — narrow or validate `s` first", ["It compiles", "It compiles, then crashes", "It converts `s` to a `Dir`"],
            "`string` is wider than `Dir`. Check it: `if (s === \"N\" || s === \"S\") move(s);`."),
        _mq("With `x: string | number` and no narrowing, what may you call on `x`?",
            "Only members both types share, like `toString()`", ["Anything on `string`", "Anything on `number`", "Nothing at all"],
            "A union offers the intersection of its members' capabilities until you narrow."),
        _mq("`enum Color { Red, Green }` — what is `Color.Green`?",
            "`1`", ["`\"Green\"`", "`0`", "`2`"],
            "Numeric enums count up from 0 unless given values."),
        _mq("Does a string enum like `enum E { A = \"a\" }` get a reverse mapping?",
            "No — only numeric enums do", ["Yes, `E[\"a\"] === \"A\"`", "Only with `const enum`", "Only at runtime in strict mode"],
            "Reverse mappings exist only for numeric members."),
        _mq("Why does Node's type stripping refuse `enum`?",
            "An enum emits a runtime object, so it can't simply be deleted", ["Enums are deprecated", "Enums need `strict` off", "Node doesn't support objects"],
            "Stripping only deletes types. An enum is code, so a stripped file would be missing it."),
        _mq("`const SIZES = [\"S\", \"M\"] as const; SIZES.push(\"L\");` — result?",
            "Compile error: the tuple is read-only", ["`SIZES` becomes 3 long", "A runtime error only", "It works, but `SIZES` becomes `string[]`"],
            "`as const` makes a `readonly` tuple, which has no `push`."),
        _mq("What is `type T = \"a\" | string`?",
            "Just `string` — the literal is absorbed", ["`\"a\"`", "A compile error", "`\"a\" | string`, kept distinct"],
            "A union simplifies away members that are subtypes of another member."),
        _mq("`boolean` is really which union?",
            "`true | false`", ["`0 | 1`", "`\"true\" | \"false\"`", "It isn't a union"],
            "That's why narrowing on `=== true` leaves `false` behind."),
        _mq("Which of these can a type alias name but an interface cannot?",
            "A union like `string | number`", ["An object shape", "A shape with methods", "A shape that extends another"],
            "Interfaces describe object shapes only; aliases can name any type."),
    ],
    11: [
        _mq("`function f(x: string | string[]) { if (Array.isArray(x)) { … } }` — what is `x` inside the `if`?",
            "`string[]`", ["`string`", "`any[]`", "`string | string[]`"],
            "`Array.isArray` narrows to the array member of the union."),
        _mq("With `x: string | Date | null`, what is `x` inside `if (typeof x === \"object\")`?",
            "`Date | null`", ["`Date`", "`object`", "`null`"],
            "`typeof null` is `\"object\"`, so `null` survives the check. Add `x !== null`."),
        _mq("What does `x instanceof Date` narrow `x` to?",
            "`Date`", ["`object`", "`Date | null`", "Nothing — `instanceof` doesn't narrow"],
            "`instanceof` narrows to the class's instance type."),
        _mq("After `if (!x) return;` with `x: string | undefined`, what type is `x`, and what did the check also exclude?",
            "`string` — but the empty string `\"\"` was rejected too", ["`string`, and nothing else was excluded", "`string | undefined`", "`never`"],
            "Truthiness narrowing removes `undefined` from the type, and also `\"\"` at runtime. Use `x === undefined` when empty strings are valid."),
        _mq("`let v: string | number = \"a\"; v = 1;` — what is `v`'s type right after?",
            "`number`", ["`string | number`", "`string`", "`1`"],
            "Assignment narrows too: after `v = 1`, the compiler knows it holds a number (the declared type is still the union)."),
        _mq("With `Fish` having `swim()` and `Bird` having `fly()`, what does `if (\"swim\" in pet)` narrow `pet` to?",
            "`Fish`", ["`Bird`", "`Fish & Bird`", "Nothing"],
            "The `in` operator narrows to the union members that declare the property."),
        _mq("Which check does NOT narrow `x: unknown` to `string`?",
            "`if (String(x) === x)`", ["`if (typeof x === \"string\")`", "`if (isString(x))` where `isString(v: unknown): v is string`", "`if (typeof x !== \"string\") return;`"],
            "The compiler only narrows on the forms it recognises — `typeof`, `instanceof`, `in`, equality with literals, predicates. A clever runtime trick is invisible to it."),
        _mq("`const found = items.find((i) => i.id === id); found.name` — under `strict`?",
            "Compile error: `found` is possibly `undefined`", ["It compiles", "`found.name` is `any`", "`find` throws if nothing matches"],
            "`find` returns `T | undefined`. Check before use (TS18048)."),
        _mq("What does `x!` do at runtime?",
            "Nothing — it's erased; it only silences the compiler", ["Throws if `x` is null", "Converts `x` to a boolean", "Returns a default"],
            "A non-null assertion is a promise to the compiler. If it's wrong, you get the crash later."),
        _mq("What must `function assertNumber(x: unknown): asserts x is number` do when `x` isn't a number?",
            "Throw", ["Return `false`", "Return `undefined`", "Log a warning"],
            "The caller narrows because the function *returned*. The only way to report failure is not to return — throw."),
        _mq("`const data: unknown = JSON.parse(text); data.id` — what does the compiler say?",
            "Error: `data` is of type `unknown`", ["It compiles", "`data.id` is `any`", "`data.id` is `unknown`"],
            "Nothing can be read off an `unknown` until you narrow it (TS18046)."),
        _mq("With `x: string | number`, after `if (typeof x === \"string\") return;`, what is `x`?",
            "`number`", ["`string | number`", "`string`", "`never`"],
            "The early return removes the `string` case from the rest of the function."),
    ],
    12: [
        _mq("For `Shape = { kind: \"c\"; r: number } | { kind: \"s\"; side: number }`, what happens on `shape.r` inside `case \"s\":`?",
            "Compile error: `r` doesn't exist on the square member", ["It's `undefined`", "It's `number | undefined`", "It compiles"],
            "Inside the case, `shape` is narrowed to the square, which has no `r`."),
        _mq("Can a discriminant be a boolean?",
            "Yes — `{ ok: true; … } | { ok: false; … }` is the classic `Result`", ["No, only strings", "Only with `as const`", "Only for two members"],
            "Any literal type works: string, number or boolean literals."),
        _mq("After `if (res.ok) return res.value;`, what is `res` on the following lines?",
            "The failure member", ["Still the whole union", "`never`", "The success member"],
            "The `return` removes the success case from the rest of the function."),
        _mq("You forget a case, and `const exhaustive: never = shape;` is in the default. What does the compiler report?",
            "`Type '…' is not assignable to type 'never'`, naming the member you missed",
            ["Nothing until runtime", "Unreachable code", "`exhaustive` is unused"],
            "The unhandled member flows into `default`, and it can't be assigned to `never` (TS2322)."),
        _mq("Where do fields shared by every member of a discriminated union go?",
            "In every member — often via a shared base type intersected in", ["Only in the first member", "In a separate interface nobody references", "Nowhere — shared fields aren't allowed"],
            "Each member is a complete shape. `type Base = { id: string }; type A = Base & { kind: \"a\" }` avoids repeating them."),
        _mq("Which models a request best?",
            "`{ status: \"loading\" } | { status: \"ok\"; data: T } | { status: \"error\"; error: string }`",
            ["`{ loading: boolean; data?: T; error?: string }`", "`{ status: string; data: T | null; error: string | null }`", "`T | string | null`"],
            "Only the tagged union makes \"loading with data and an error\" impossible to represent."),
        _mq("An action with an unexpected `type` arrives from the network. What does the `never` check in your reducer do about it?",
            "Nothing at runtime — it's compile-time only, so the default branch should also throw or ignore",
            ["It throws automatically", "It rejects the action", "It logs a warning"],
            "The compiler only knows about the types you declared. Untrusted data must be validated at runtime."),
        _mq("What lets TypeScript tell the members apart in `switch (s.kind)`?",
            "The distinct literal type of `kind` in each member", ["The order of the members", "The property names", "`instanceof` checks it inserts"],
            "It compares the literal in each `case` against each member's tag type."),
        _mq("What's the risk of `default: return 0;` in a switch over a discriminated union?",
            "A member added later falls silently into it", ["None — it's best practice", "The switch stops narrowing", "It's a compile error"],
            "A catch-all hides the compiler's \"you missed a case\" help."),
        _mq("With `Shape = { kind: \"c\"; r: number } | { kind: \"s\"; side: number }`, is `const s: Shape = { kind: \"c\", r: 1, side: 2 };` accepted?",
            "No — `side` is an excess property for the circle member", ["Yes", "Yes, but `side` is dropped", "Only without `strict`"],
            "The literal is checked against the member its tag selects, and that member has no `side`."),
        _mq("`Shape` is a union of two members tagged `\"c\"` and `\"s\"`. `function area(s: Shape): number { switch (s.kind) { case \"c\": return …; case \"s\": return …; } }` — why does this compile with no `return` after the switch?",
            "Every member is handled, so the compiler knows the end of the function is unreachable",
            ["Functions returning `number` default to 0", "A `switch` always returns", "It doesn't — TS2366 is reported"],
            "Exhaustiveness counts for return analysis too. Remove one case and you get \"Function lacks ending return statement\" (TS2366)."),
        _mq("Can two members of a discriminated union share the same tag value?",
            "They can, but then the tag no longer tells them apart", ["No, it's a compile error", "Yes, and narrowing still works perfectly", "Only for string tags"],
            "Narrowing on the tag would leave a union of both members — the point of the tag is lost."),
    ],
    13: [
        _mq("Your program does `input.split(\"\\n\")` on `n` lines that end with a trailing newline, with no `trim()`. How long is the array?",
            "`n + 1` — there's an empty string after the last newline", ["`n`", "`n - 1`", "`n + 2`"],
            "Splitting `\"a\\nb\\n\"` gives `[\"a\", \"b\", \"\"]`. Trim first or filter empties."),
        _mq("What is the cheapest way to check two strings are anagrams?",
            "Count letters (a Map or a 26-slot array) and compare the counts", ["Compare every permutation", "Compare their lengths", "Sort both and compare only the first letters"],
            "Counting is O(n); sorting both is O(n log n) and also fine."),
        _mq("Which of these is O(n log n)?",
            "`arr.sort((a, b) => a - b)`", ["`arr.map((x) => x * 2)`", "`set.has(x)`", "`arr.includes(x)`"],
            "Comparison sorting is O(n log n); the others are O(n) or O(1)."),
        _mq("`Math.max()` with no arguments?",
            "`-Infinity`", ["`0`", "`NaN`", "It throws"],
            "The identity for max is −∞ — which is also what `Math.max(...[])` gives on an empty array."),
        _mq("Merging two sorted arrays in O(n + m) uses…",
            "Two pointers, always taking the smaller head", ["Concatenating then sorting", "A nested loop", "A Set"],
            "Each step consumes one element, so the whole merge is linear."),
        _mq("A function returns `number | undefined`. What prints `0` when it's undefined, but keeps a real 0?",
            "`console.log(v ?? 0)`", ["`console.log(v || 0)`", "`console.log(v!)`", "`console.log(Number(v))`"],
            "`??` defaults only on null/undefined. (`Number(undefined)` is `NaN`.)"),
        _mq("`[...\"stressed\"].reverse().join(\"\")`?",
            "`\"desserts\"`", ["`\"stressed\"`", "A compile error", "`[\"d\",\"e\",…]`"],
            "Spread into characters, reverse the array, join back into a string."),
        _mq("You need the index AND the ability to stop early. Which loop?",
            "A classic `for (let i = 0; …)` loop", ["`forEach`", "`for…in`", "`map`"],
            "`forEach` and `map` can't `break`; `for…in` gives string keys."),
        _mq("What type does `words.map((w) => w.length)` have, for `words: string[]`?",
            "`number[]`", ["`string[]`", "`number`", "`any[]`"],
            "`map` returns an array of whatever the callback returns."),
        _mq("Building a Set from an array, then filtering another array with `set.has` costs…",
            "O(n + m)", ["O(n · m)", "O(n log m)", "O(1)"],
            "Building is O(n); each `has` is O(1), so the filter is O(m)."),
    ],
    14: [
        _mq("`const len = s?.length ?? 0` when `s` is `undefined`?",
            "`0`", ["`undefined`", "It throws", "`NaN`"],
            "`?.` short-circuits to `undefined`, and `??` supplies the fallback."),
        _mq("`let name: string = null;` under `strict`?",
            "Compile error: `null` isn't assignable to `string`", ["It compiles", "`name` becomes `\"null\"`", "It's a warning"],
            "With `strictNullChecks`, `null` must be named in the type: `string | null`."),
        _mq("What does `strictPropertyInitialization` flag?",
            "Class fields that aren't definitely assigned by the constructor", ["Unused properties", "Properties without `readonly`", "Optional properties"],
            "A field typed `string` must be initialised, assigned in the constructor, or declared `field!: string`."),
        _mq("What does `useUnknownInCatchVariables` change?",
            "`catch (e)` gives `e` the type `unknown` instead of `any`", ["Catch blocks become mandatory", "Errors must extend `Error`", "`finally` becomes required"],
            "Anything can be thrown, so `unknown` is the honest type. It's part of `strict`."),
        _mq("What does `noImplicitReturns` report?",
            "Functions where some code paths return a value and others fall off the end", ["Functions without a return type", "Arrow functions without braces", "Unused return values"],
            "It catches the forgotten `return` in one branch."),
        _mq("What happens when `// @ts-expect-error` sits above a line with no error?",
            "It becomes an error itself: \"Unused '@ts-expect-error' directive\"", ["Nothing", "It suppresses errors on the next two lines", "It disables checking for the file"],
            "That's its advantage over `@ts-ignore`: when the problem is fixed, it tells you to remove it (TS2578)."),
        _mq("What is `arr[5]` at runtime for a three-element `number[]`?",
            "`undefined`", ["A thrown RangeError", "`0`", "`NaN`"],
            "Out-of-range reads return `undefined`. Only `noUncheckedIndexedAccess` makes the type admit it."),
        _mq("What is the risk of `const v = map.get(k)!;`?",
            "If `k` is missing, `v` is really `undefined` while typed as `V`", ["None — `!` checks at runtime", "It deletes the key", "It throws when the key is missing"],
            "`!` is erased. The crash happens later, wherever `v` is used."),
        _mq("What does `target` in tsconfig control?",
            "Which JavaScript syntax version the output uses", ["Which files are compiled", "How strict the checks are", "Where the output is written"],
            "Newer syntax is down-levelled for older targets. `lib` is the separate setting for available built-in types."),
        _mq("What does `lib` in tsconfig control?",
            "Which built-in declarations exist — e.g. `es2022` or `dom`", ["Which npm packages are installed", "Which files are libraries", "The output module format"],
            "Without `dom`, `document` doesn't exist; with an older `lib`, newer methods don't type-check."),
        _mq("`function f(x?: number) { return x.toFixed(2); }` under `strict`?",
            "Compile error: `x` is possibly `undefined`", ["It compiles", "It returns `\"undefined\"`", "`toFixed` handles `undefined`"],
            "An optional parameter is `number | undefined` inside the body (TS18048)."),
        _mq("What does `x == null` check?",
            "`null` and `undefined` both", ["Only `null`", "Only `undefined`", "Any falsy value"],
            "It's the one widely accepted use of `==`: `null == undefined` is `true`, and nothing else is loosely equal to either."),
    ],
    15: [
        _mq("`const n = \"5\" as number;` — result?",
            "Compile error: conversion may be a mistake", ["`n` is 5", "`n` is `\"5\"`, typed `number`", "`n` is `NaN`"],
            "`as` refuses conversions between types that don't overlap (TS2352). It never converts anything anyway."),
        _mq("`const el = {} as { id: string }; el.id.length` — what happens?",
            "It compiles, then crashes at runtime: `el.id` is `undefined`", ["Compile error", "It returns 0", "It returns `undefined`"],
            "The assertion lied, and nothing at runtime notices until the property is used."),
        _mq("`const c = { mode: \"dark\" } satisfies { mode: \"dark\" | \"light\" };` — what is `c.mode`'s type?",
            "`\"dark\"`", ["`\"dark\" | \"light\"`", "`string`", "`any`"],
            "`satisfies` checks the shape but keeps the expression's own, narrower type."),
        _mq("`type P = { x: number }; const p: P = { x: 1, y: 2 };` — result?",
            "Compile error: `y` is an excess property", ["It compiles; `y` is dropped", "It compiles; `p.y` is 2", "A runtime error"],
            "A fresh literal with unknown keys is almost always a typo (TS2353)."),
        _mq("`function len(x: { length: number }) { … }` — is `len(\"abc\")` allowed?",
            "Yes — a string has a numeric `length`", ["No — `string` isn't an object type", "Only with `as`", "Only in non-strict mode"],
            "Structural typing: anything with the right members fits."),
        _mq("Can an instance of `class A { x = 1 }` be used where `class B { x = 1 }` is expected?",
            "Yes — they have the same structure", ["No — different class names", "Only if `A extends B`", "Only with `implements`"],
            "Classes compare structurally, as long as neither has private or protected members."),
        _mq("What makes two structurally identical classes incompatible?",
            "A `private`, `protected` or `#private` member", ["Different constructors", "Different method order", "Different file names"],
            "Private members are compared by where they were declared, which makes classes that have them nominal."),
        _mq("Is `(x: string) => void` assignable to `(x: string | number) => void`?",
            "No — the target may call it with a number it can't handle", ["Yes", "Only with `strict` off", "Only for arrow functions"],
            "Parameters are contravariant: the substitute must accept at least everything the original accepts."),
        _mq("Is `(x: string | number) => void` assignable to `(x: string) => void`?",
            "Yes — it accepts everything it will be given, and more", ["No", "Only with `as`", "Only if it returns a value"],
            "Accepting a wider parameter type is always safe."),
        _mq("Why write `const ROUTES = { … } as const satisfies Record<string, string>`?",
            "To keep a read-only, literal-typed object while still checking its shape", ["To convert it to a Map", "To make lookups faster", "`as const` and `satisfies` can't be combined"],
            "`as const` freezes the literal types; `satisfies` validates them without widening."),
    ],
    16: [
        _mq("`type UserId = string & { __brand: \"UserId\" }; const id: UserId = \"u1\";` — result?",
            "Compile error: a plain string isn't a `UserId`", ["It compiles", "`id` is `\"u1\"` typed `string`", "A runtime error"],
            "The brand is the point: only your constructor, with its one cast, can make a `UserId`."),
        _mq("Can a `UserId` be passed to a function expecting a plain `string`?",
            "Yes — a brand is a subtype of `string`", ["No", "Only with `as string`", "Only if the function is generic"],
            "Branding restricts which values *become* a `UserId`, not where one can go."),
        _mq("`const a = Object.freeze([1, 2]); a.push(3);` — does it compile?",
            "No — `Object.freeze` returns a `readonly number[]`", ["Yes, and `a` becomes [1, 2, 3]", "Yes, but it throws at runtime", "Yes, and the push is silently ignored"],
            "The type of a frozen array has no mutators, so the compiler stops you before the runtime would."),
        _mq("`const o = Object.freeze({ inner: { n: 1 } }); o.inner.n = 2;` — what happens?",
            "It compiles and works — `freeze` is shallow", ["Compile error", "It throws", "It's silently ignored"],
            "Only `o`'s own properties are frozen; `inner` is an ordinary object."),
        _mq("With `x: Readonly<{ a: { b: number } }>`, is `x.a.b = 2` allowed?",
            "Yes — `Readonly` is one level deep", ["No", "Only at runtime", "Only if `b` is optional"],
            "`x.a` can't be reassigned, but the object it points to is still mutable."),
        _mq("What is structural sharing?",
            "A new version of a data structure reusing the unchanged parts of the old one", ["Two variables pointing at one object", "Classes sharing a prototype", "Copying everything deeply"],
            "It makes immutable updates cheap: changing one field copies only the path to it."),
        _mq("How do you add `x` to an array without mutating it?",
            "`[...xs, x]`", ["`xs.push(x)`", "`xs.concat` is the only way", "`xs[xs.length] = x`"],
            "Spread builds a new array; `push` changes the original."),
        _mq("How do you remove the element at index `i` without mutating?",
            "`xs.filter((_, j) => j !== i)`", ["`xs.splice(i, 1)`", "`delete xs[i]`", "`xs.pop()`"],
            "`splice` mutates; `delete` leaves a hole."),
        _mq("How do you update one field of an object immutably?",
            "`{ ...obj, field: value }`", ["`obj.field = value`", "`Object.assign(obj, { field: value })`", "`Object.freeze(obj)`"],
            "`Object.assign(obj, …)` writes into `obj`; spreading into a new literal doesn't."),
        _mq("What does a `unique symbol` brand give you over a string-literal brand?",
            "It can't be forged by writing the property name by hand", ["Smaller output", "A runtime check", "Faster comparisons"],
            "Every `unique symbol` declaration is its own type, so no other code can produce a matching key."),
        _mq("Is `as const` deep?",
            "Yes — nested object and array literals become readonly too", ["No, one level only", "Only for arrays", "Only for strings"],
            "`as const` applies recursively to the whole literal expression (unlike `Readonly<T>`)."),
    ],
    17: [
        _mq("`Partial<{ a: number }>`?",
            "`{ a?: number }`", ["`{ a: number | undefined }`", "`{ a: number }`", "`{}`"],
            "Every property becomes optional."),
        _mq("`Required<{ a?: number }>`?",
            "`{ a: number }`", ["`{ a?: number }`", "`{ a: number | undefined }`", "`{ a: unknown }`"],
            "The `?` is removed."),
        _mq("`Pick<{ a: 1; b: 2 }, \"a\">`?",
            "`{ a: 1 }`", ["`{ b: 2 }`", "`1`", "`\"a\"`"],
            "`Pick` keeps the named keys."),
        _mq("`Record<\"x\" | \"y\", boolean>`?",
            "`{ x: boolean; y: boolean }`", ["`{ [key: string]: boolean }`", "`boolean[]`", "`Map<\"x\" | \"y\", boolean>`"],
            "One property per member of the key union."),
        _mq("`Extract<\"a\" | \"b\" | 1, string>`?",
            "`\"a\" | \"b\"`", ["`1`", "`string`", "`never`"],
            "`Extract` keeps the members assignable to the second argument."),
        _mq("`NonNullable<string | null | undefined>`?",
            "`string`", ["`string | null`", "`string | undefined`", "`never`"],
            "Both `null` and `undefined` are removed."),
        _mq("`Parameters<(a: number, b: string) => void>`?",
            "`[a: number, b: string]`", ["`number | string`", "`{ a: number; b: string }`", "`(number | string)[]`"],
            "A labelled tuple of the parameter types."),
        _mq("`ReturnType<() => Promise<number>>`?",
            "`Promise<number>`", ["`number`", "`void`", "`unknown`"],
            "It's the declared return type — the promise itself."),
        _mq("`Awaited<ReturnType<() => Promise<number>>>`?",
            "`number`", ["`Promise<number>`", "`unknown`", "`void`"],
            "`Awaited` unwraps the promise."),
        _mq("What is the type of `a` in `{ a: number } & { a: string }`?",
            "`never`", ["`number | string`", "`number`", "`string`"],
            "No value is both a number and a string, so the property's type is `never`."),
    ],
    18: [
        _mq("`function first<T>(xs: T[]): T | undefined` — what does `first([1, 2])` return, type-wise?",
            "`number | undefined`", ["`number`", "`T`", "`any`"],
            "`T` is inferred as `number`; the `| undefined` covers the empty array."),
        _mq("`function len<T extends { length: number }>(x: T) { … }` — what is `len(5)`?",
            "Compile error: `number` has no `length`", ["`undefined`", "`1`", "It compiles"],
            "The constraint rejects arguments without a numeric `length`."),
        _mq("`class Box<T> { value: T; constructor(v: T) { this.value = v; } }` — what is `new Box(3).value`'s type?",
            "`number`", ["`T`", "`3`", "`unknown`"],
            "`T` is inferred from the constructor argument and widened to `number` for the mutable field."),
        _mq("`first<string>([1])` — result?",
            "Compile error: `number` isn't assignable to `string`", ["`\"1\"`", "`1`", "`string | undefined`"],
            "An explicit type argument fixes `T`, and the argument must match it."),
        _mq("What does `function merge<A, B>(a: A, b: B): A & B` promise?",
            "A value with every property of both", ["A value of either type", "`A` with `B`'s keys removed", "A tuple `[A, B]`"],
            "`A & B` is an intersection: it has all members of both."),
        _mq("`get(user, \"nme\")` where `get<T, K extends keyof T>(obj: T, key: K)` — result?",
            "Compile error: `\"nme\"` isn't a key of the user type", ["`undefined`", "`any`", "It compiles"],
            "The `keyof` constraint turns a typo into an error at the call."),
        _mq("In `Promise<T>`, what is `T`?",
            "The type of the value the promise resolves with", ["The error type", "The time until it resolves", "The executor's type"],
            "Rejections are untyped (`any`/`unknown`); only the fulfilment value is in the type."),
        _mq("You write a helper that only counts elements. Should it be `count<T>(xs: T[])` or `count(xs: unknown[])`?",
            "`count(xs: unknown[])` — `T` would appear only once and link nothing",
            ["`count<T>(xs: T[])` — generics are always better", "`count(xs: any[])`", "It makes no difference to callers, so either"],
            "A type parameter earns its place by connecting two positions (input and output). Otherwise `unknown` says the same thing more simply."),
        _mq("With `function f<const T extends readonly string[]>(xs: T)`, what is `T` for `f([\"a\", \"b\"])`?",
            "`readonly [\"a\", \"b\"]`", ["`string[]`", "`(\"a\" | \"b\")[]`", "`readonly string[]`"],
            "A `const` type parameter (TS 5.0) infers as if the caller had written `as const`."),
        _mq("`function wrap<T>(x: T) { return [x]; }` — what is the inferred return type?",
            "`T[]`", ["`[T]`", "`any[]`", "`unknown[]`"],
            "An array literal infers an array type, not a tuple, unless asked otherwise."),
        _mq("What does `NoInfer<T>` do in `function pick<T extends string>(options: T[], fallback: NoInfer<T>)`?",
            "Makes `T` come from `options` only, so a `fallback` not in the list is an error",
            ["Disables type checking for `fallback`", "Makes `fallback` optional", "Infers `T` from `fallback` only"],
            "Without it, `pick([\"a\", \"b\"], \"c\")` would widen `T` to include `\"c\"` (TS 5.4)."),
        _mq("When is a generic default like `<T = string>` used?",
            "When `T` can be neither inferred nor is it passed explicitly", ["Always, overriding inference", "Only for classes", "Only when `T` is `unknown`"],
            "Inference and explicit arguments both take priority over the default."),
    ],
    19: [
        _mq("`keyof { a: 1; b: 2 }`?",
            "`\"a\" | \"b\"`", ["`1 | 2`", "`string`", "`[\"a\", \"b\"]`"],
            "`keyof` produces the union of property names."),
        _mq("With `type P = { name: string; age: number }`, what is `P[\"age\"]`?",
            "`number`", ["`\"age\"`", "`string | number`", "An error"],
            "An indexed access type looks up the property's type."),
        _mq("With `type P = { name: string; age: number }`, what is `P[keyof P]`?",
            "`string | number`", ["`\"name\" | \"age\"`", "`P`", "`never`"],
            "Indexing with the key union gives the union of all value types."),
        _mq("`const o = { x: 1 };` — what is `typeof o`?",
            "`{ x: number }`", ["`{ x: 1 }`", "`\"object\"`", "`object`"],
            "The property is mutable, so it widens to `number`. (In an expression, `typeof o` would be the string `\"object\"`.)"),
        _mq("`const arr = [1, \"a\"];` — what is `(typeof arr)[number]`?",
            "`string | number`", ["`1 | \"a\"`", "`number`", "`[number, string]`"],
            "Without `as const`, the element type is widened."),
        _mq("Does `keyof string[]` include `number`?",
            "Yes — along with `length`, `push` and the other array members", ["No, only method names", "No, it's `never`", "Only `length`"],
            "Arrays have numeric index keys as well as named properties."),
        _mq("`const COLORS = { red: \"#f00\" } as const;` — what is `(typeof COLORS)[\"red\"]`?",
            "`\"#f00\"`", ["`string`", "`\"red\"`", "`readonly string`"],
            "`as const` keeps the literal value type."),
        _mq("With `type P = { name: string; age: number }`, what does `P[\"missing\"]` give?",
            "A compile error", ["`undefined`", "`never`", "`unknown`"],
            "Indexed access requires a key that exists on the type."),
        _mq("With `type P = { name: string; age: number }`, what is `P[\"name\" | \"age\"]`?",
            "`string | number`", ["`string & number`", "An error", "`\"name\" | \"age\"`"],
            "Indexing with a union of keys distributes over them."),
        _mq("Why write `ReturnType<typeof f>` rather than `ReturnType<f>`?",
            "`ReturnType` takes a type, and `f` is a value — `typeof` lifts it", ["It's shorter", "`typeof` makes it faster", "`ReturnType<f>` gives `any`"],
            "Values and types live in different namespaces; `typeof` bridges from value to type."),
        _mq("When is `Object.keys(o) as (keyof typeof o)[]` safe?",
            "When you built `o` yourself and know it carries no extra keys", ["Always", "Never", "Only for arrays"],
            "The cast asserts there are no extra keys — true for a literal you control, not for data from outside."),
        _mq("What does `keyof` produce for a type with a `[key: string]: V` index signature?",
            "`string | number`", ["`string`", "`never`", "`V`"],
            "Numeric keys are converted to strings, so they're allowed too."),
    ],
    20: [
        _mq("`{ [K in \"a\" | \"b\"]: K }`?",
            "`{ a: \"a\"; b: \"b\" }`", ["`{ a: string; b: string }`", "`\"a\" | \"b\"`", "`{ K: \"a\" | \"b\" }`"],
            "Each key maps to its own literal."),
        _mq("Which built-in is `{ readonly [K in keyof T]: T[K] }`?",
            "`Readonly<T>`", ["`Required<T>`", "`Partial<T>`", "`Record<keyof T, T>`"],
            "It adds `readonly` to every property."),
        _mq("Which built-in is `{ [K in keyof T]?: T[K] }`?",
            "`Partial<T>`", ["`Required<T>`", "`Pick<T, keyof T>`", "`NonNullable<T>`"],
            "It adds `?` to every property."),
        _mq("What does `{ [K in keyof T]: T[K] | null }` describe?",
            "`T` with every field also allowed to be `null`", ["`T` with every field removed", "`T` or `null`", "Only the nullable fields of `T`"],
            "A mapped type can transform each value type."),
        _mq("What happens when a homomorphic mapped type is applied to an array type?",
            "It produces an array (or tuple) type, mapping the elements", ["It maps the array's method names", "It's a compile error", "It produces an object with numeric keys"],
            "Mapped types over `keyof T` treat arrays and tuples specially, so `Partial<[number, string]>` is `[number?, string?]`."),
        _mq("What does the `-?` modifier do?",
            "Removes optionality", ["Adds optionality", "Removes `readonly`", "Makes the property nullable"],
            "`-?` is how `Required<T>` is built."),
        _mq("What does `[K in keyof T as K extends `` `_${string}` `` ? never : K]` do?",
            "Drops every key starting with an underscore", ["Adds an underscore to every key", "Keeps only underscored keys", "Nothing — `as` can't filter"],
            "Remapping a key to `never` removes it."),
        _mq("Is `Record<K, V>` itself a mapped type?",
            "Yes — it's `{ [P in K]: V }`", ["No, it's built in to the compiler", "No, it's an interface", "Only for string keys"],
            "Most utility types are ordinary mapped or conditional types you could write yourself."),
        _mq("Which modifiers does a homomorphic mapped type (over `keyof T`) keep from `T`?",
            "`readonly` and `?`", ["None", "Only `readonly`", "Only `?`"],
            "That's why `Partial<Readonly<T>>` is still read-only."),
        _mq("`keyof (A & B)`?",
            "`keyof A | keyof B`", ["`keyof A & keyof B`", "The common keys only", "`never`"],
            "An intersection has every key of both. (`keyof (A | B)` is the reverse: only the shared keys.)"),
        _mq("What does `{ [K in keyof T]: () => T[K] }` produce for `T = { a: number }`?",
            "`{ a: () => number }`", ["`() => { a: number }`", "`{ a: number }`", "`{ a: () => T }`"],
            "Each value type is wrapped in a function type."),
        _mq("Why does `DeepReadonly` need recursion?",
            "`Readonly` only covers the top level; nested objects need the same treatment", ["To be faster", "To handle functions", "`Readonly` is already deep"],
            "`{ readonly [K in keyof T]: DeepReadonly<T[K]> }` walks every level."),
    ],
    21: [
        _mq("`type IsArr<T> = T extends unknown[] ? true : false;` — what is `IsArr<string[]>`?",
            "`true`", ["`false`", "`boolean`", "`never`"],
            "`string[]` is assignable to `unknown[]`."),
        _mq("`type IsArr<T> = T extends unknown[] ? true : false;` — what is `IsArr<string[] | number>`?",
            "`boolean` — it distributes to `true | false`", ["`true`", "`false`", "`never`"],
            "A naked type parameter distributes over the union, checking each member separately."),
        _mq("`type Elem<T> = T extends (infer E)[] ? E : never;` — what is `Elem<number[]>`?",
            "`number`", ["`number[]`", "`never`", "`E`"],
            "`infer E` captures the element type."),
        _mq("`type Elem<T> = T extends (infer E)[] ? E : never;` — what is `Elem<string>`?",
            "`never`", ["`string`", "`unknown`", "An error"],
            "`string` isn't an array, so the false branch runs."),
        _mq("`type First<T> = T extends [infer F, ...unknown[]] ? F : never;` — `First<[1, 2]>`?",
            "`1`", ["`[1]`", "`1 | 2`", "`never`"],
            "`F` captures the first element of the tuple."),
        _mq("`type First<T> = T extends [infer F, ...unknown[]] ? F : never;` — what is `First<[]>`?",
            "`never`", ["`undefined`", "`[]`", "`unknown`"],
            "An empty tuple doesn't match `[infer F, ...unknown[]]`."),
        _mq("`type Args<T> = T extends (...a: infer A) => unknown ? A : never;` — `Args<(x: string) => void>`?",
            "`[x: string]`", ["`string`", "`string[]`", "`(x: string) => void`"],
            "Rest-parameter position infers a tuple — this is how `Parameters` works."),
        _mq("`Exclude<string | number | boolean, number>`?",
            "`string | boolean`", ["`number`", "`string | number | boolean`", "`never`"],
            "Members assignable to `number` are removed."),
        _mq("`[never] extends [never] ? 1 : 2`?",
            "`1`", ["`2`", "`never`", "`1 | 2`"],
            "Wrapped in a tuple there's no distribution, and `[never]` is assignable to itself."),
        _mq("`type T = any extends string ? 1 : 2`?",
            "`1 | 2`", ["`1`", "`2`", "`never`"],
            "`any` as the checked type takes both branches."),
        _mq("Where may `infer` appear?",
            "Only in the `extends` clause of a conditional type", ["Anywhere in a type", "Only in function signatures", "Only inside mapped types"],
            "It declares a variable for the pattern being matched."),
        _mq("`type Unbox<T> = T extends Promise<infer V> ? Unbox<V> : T;` — `Unbox<Promise<Promise<1>>>`?",
            "`1`", ["`Promise<1>`", "`Promise<Promise<1>>`", "`never`"],
            "The recursion peels one promise per step until none are left."),
    ],
    22: [
        _mq("Which string does `` `id-${number}` `` accept?",
            "`\"id-3.5\"`", ["`\"id-x\"`", "`\"id-\"`", "`\"ID-1\"`"],
            "`${number}` matches anything that parses as a number, fractions included."),
        _mq("`Uppercase<\"ab\">`?",
            "`\"AB\"`", ["`\"Ab\"`", "`string`", "`\"ab\"`"],
            "The intrinsic string types transform literal types."),
        _mq("`` type H<S> = S extends `${infer X}${infer R}` ? X : never; `` — what is `H<\"abc\">`?",
            "`\"a\"`", ["`\"abc\"`", "`\"\"`", "`never`"],
            "An `infer` followed by another placeholder captures a single character."),
        _mq("`` type Trim<S> = S extends ` ${infer R}` ? Trim<R> : S; `` — `Trim<\"  x\">`?",
            "`\"x\"`", ["`\" x\"`", "`\"  x\"`", "`never`"],
            "Each recursive step removes one leading space."),
        _mq("What does `` `${string}` `` match?",
            "Any string", ["Only the empty string", "Only literal types", "Nothing — it's an error"],
            "It's equivalent to `string` on its own; it's useful as part of a larger pattern."),
        _mq("Which is a valid recursive type for a tree?",
            "`type Tree<T> = { value: T; children: Tree<T>[] }`", ["`type Tree<T> = Tree<T> | T`", "`type Tree = Tree[]`", "Recursive types aren't allowed"],
            "The recursion sits inside an object type, so it's deferred and well-founded."),
        _mq("`` `${Uppercase<\"get\">}_${\"a\" | \"b\"}` ``?",
            "`\"GET_a\" | \"GET_b\"`", ["`\"GET_A\" | \"GET_B\"`", "`\"get_a\" | \"get_b\"`", "`string`"],
            "Only the first part is uppercased; the union distributes over the second."),
        _mq("`Capitalize<\"hello world\">`?",
            "`\"Hello world\"`", ["`\"Hello World\"`", "`\"HELLO WORLD\"`", "`\"hello world\"`"],
            "Only the very first character is changed."),
        _mq("What does `` \"42\" extends `${infer N extends number}` ? N : never `` give (TS 4.8+)?",
            "The number literal `42`", ["The string `\"42\"`", "`number`", "`never`"],
            "An `infer … extends number` constraint in a template parses the matched text into a number literal."),
        _mq("Why is `type Json = string | number | boolean | null | Json[] | { [k: string]: Json }` allowed?",
            "The self-references sit inside array and object types, so they're resolved lazily", ["Because it has a base case", "Because it uses `null`", "It isn't — it's an error"],
            "A bare `type Bad = Bad | string` has nothing to defer and is rejected."),
    ],
    23: [
        _mq("`class A { #x = 1; static read(a: A) { return a.#x; } }` — allowed?",
            "Yes — code inside the class can read `#x` on any `A`", ["No — `#x` is per instance", "Only from instance methods", "Only in a subclass"],
            "Private names are scoped to the class body, not to one instance."),
        _mq("`class A { private x = 1 }` — `new A().x` from outside?",
            "Compile error, but at runtime the property is there", ["It works; `private` is advisory", "It throws at runtime", "It returns `undefined`"],
            "`private` is checked by the compiler only. `#x` is the runtime-private version."),
        _mq("In a subclass constructor, `this.y = 1; super();` — result?",
            "Error: `super()` must be called before `this` is used", ["It works", "`y` is set on the parent", "A warning only"],
            "The object doesn't exist until the parent constructor has run (TS17009)."),
        _mq("Where do `static` members live?",
            "On the class itself, not on instances", ["On every instance", "On the prototype", "In a global registry"],
            "Access them as `ClassName.member`."),
        _mq("Can a `readonly` class field be assigned in the constructor?",
            "Yes — only after construction is it fixed", ["No, only in its declaration", "Only once, anywhere", "Only in a static block"],
            "`readonly` fields may be set at the declaration or in the constructor."),
        _mq("Does `implements I` give a class any code from `I`?",
            "No — an interface has no implementation; it only checks", ["Yes, default methods", "Yes, if `I` has method bodies", "Only static members"],
            "`implements` is a check. Inheritance of code comes from `extends`."),
        _mq("Assigning to a property that has a `get` but no `set`?",
            "Compile error: it's read-only", ["It creates a new field", "It's silently ignored", "It calls the getter"],
            "A getter without a setter is typed `readonly` (TS2540)."),
        _mq("In a `static` method, what does `this` refer to?",
            "The class (constructor) itself", ["The first instance", "`undefined`", "The global object"],
            "That's why `this.create()` works inside a static factory."),
        _mq("`({ x: 1, y: 2 }) instanceof Point` for a class `Point { x = 0; y = 0 }`?",
            "`false` — even though the shape matches", ["`true`", "A compile error", "`undefined`"],
            "`instanceof` checks the prototype chain, not the shape. Structural typing is compile-time only."),
        _mq("Which is composition rather than inheritance?",
            "`class Car { engine = new Engine(); }`", ["`class Car extends Engine {}`", "`class Car implements Engine {}`", "`class Car extends Vehicle implements Engine {}`"],
            "The car *has* an engine instead of *being* one — swap it without touching a hierarchy."),
    ],
    24: [
        _mq("`function* g() { yield 1; yield 2; }` — `[...g()]`?",
            "`[1, 2]`", ["`[g]`", "`[]`", "`2`"],
            "Spreading drains the generator."),
        _mq("`function* g() { yield 1; yield 2; }` — what does the third `next()` on one `g()` iterator return?",
            "`{ value: undefined, done: true }`", ["`{ value: 2, done: false }`", "It throws", "`{ value: 3, done: false }`"],
            "After the last `yield` the generator returns, and further calls report `done`."),
        _mq("Is a generator's `return` value visited by `for…of`?",
            "No — only yielded values are", ["Yes, as the last item", "Only when it's not `undefined`", "Only with `yield*`"],
            "`for…of` stops at `done: true` and ignores its `value`."),
        _mq("Stack vs queue order?",
            "Stack is last-in first-out; queue is first-in first-out", ["Both FIFO", "Both LIFO", "Stack is FIFO; queue is LIFO"],
            "Stacks drive DFS and undo; queues drive BFS and scheduling."),
        _mq("Why use a ring buffer for a queue?",
            "O(1) enqueue and dequeue without shifting elements", ["It's sorted", "It never fills up", "It uses no memory"],
            "Head and tail indices wrap around a fixed array."),
        _mq("In an array-backed binary heap, where are the children of index `i`?",
            "`2i + 1` and `2i + 2`", ["`i + 1` and `i + 2`", "`2i` and `2i + 1`", "`i / 2`"],
            "And the parent is `Math.floor((i - 1) / 2)`."),
        _mq("Cost of inserting at the head of a singly linked list?",
            "O(1)", ["O(n)", "O(log n)", "O(n²)"],
            "Point the new node at the old head and update `head`."),
        _mq("What does iterating a `Map` with `for…of` yield?",
            "`[key, value]` pairs", ["Keys only", "Values only", "Entries objects with `.key`/`.value`"],
            "Destructure them: `for (const [k, v] of map)`."),
        _mq("`Iterable<T>` vs `Iterator<T>`?",
            "An iterable has `[Symbol.iterator]()`, which returns an iterator; an iterator has `next()`",
            ["They're the same", "An iterator has `[Symbol.iterator]`, an iterable has `next`", "Iterables are arrays only"],
            "`for…of` asks the iterable for a fresh iterator, then calls `next()` until done."),
        _mq("Why a generic `Stack<T>` instead of a `Stack` that stores `any`?",
            "So `pop()` returns `T | undefined` and callers keep their types", ["It's faster", "`any` can't be stored in arrays", "Generics are required for classes"],
            "With `any`, every value that comes out has lost its type."),
    ],
    25: [
        _mq("`try { throw \"oops\"; } catch (e) { … }` — what is `e`?",
            "The string `\"oops\"` — not an `Error`, and with no stack trace", ["An `Error` whose message is \"oops\"", "`undefined`", "A compile error"],
            "Anything can be thrown. Throw `Error` objects so there's a message and a stack."),
        _mq("`async function f() { throw new Error(\"x\"); }` — what does calling `f()` without `await` do?",
            "Returns a rejected promise; nothing throws at the call site", ["Throws immediately", "Returns `undefined`", "Logs the error and continues"],
            "An async function turns throws into rejections. Unawaited, the rejection goes unhandled."),
        _mq("What does this print? `console.log(1); setTimeout(() => console.log(2)); Promise.resolve().then(() => console.log(3)); console.log(4);`",
            "`1 4 3 2`", ["`1 2 3 4`", "`1 4 2 3`", "`1 3 4 2`"],
            "Synchronous code first; then microtasks (promise callbacks); then timers."),
        _mq("What does `await 5` evaluate to?",
            "`5`", ["A pending promise", "`undefined`", "A compile error"],
            "Awaiting a non-promise wraps it in a resolved promise and gives the value back."),
        _mq("What does `Promise.all([])` do?",
            "Resolves immediately with `[]`", ["Never resolves", "Rejects", "Resolves with `undefined`"],
            "With nothing to wait for, it's already done."),
        _mq("What does `Promise.any` do when every promise rejects?",
            "Rejects with an `AggregateError` holding all the reasons", ["Resolves with `undefined`", "Rejects with the first reason", "Never settles"],
            "It resolves on the first success; only total failure rejects."),
        _mq("Type of `await Promise.all([Promise.resolve(1), Promise.resolve(\"a\")])`?",
            "`[number, string]`", ["`(number | string)[]`", "`any[]`", "`Promise<[number, string]>`"],
            "`Promise.all` on a tuple keeps each position's type."),
        _mq("What happens to an unhandled promise rejection in modern Node?",
            "The process crashes by default", ["It's silently ignored", "It's retried", "It becomes a warning only"],
            "Since Node 15 the default is to throw. Always `await` or `.catch`."),
        _mq("`function f() { try { return 1; } finally { console.log(\"f\"); } }` — calling `f()`?",
            "Prints `f`, then returns 1", ["Returns 1 without printing", "Prints `f` and returns `undefined`", "Throws"],
            "`finally` always runs, even after a `return`."),
        _mq("Why set `this.name = \"ValidationError\"` in a custom error class?",
            "So logs and stack traces show which kind of error it is", ["It's required for `instanceof`", "It sets the message", "It makes the error catchable"],
            "The name prefixes the message in `String(err)` and in stacks."),
        _mq("After `if (e instanceof Error)`, what is `e` (from `catch (e)` under `strict`)?",
            "`Error`", ["`unknown`", "`any`", "`never`"],
            "`instanceof` narrows the `unknown` catch variable, so `e.message` is safe."),
    ],
    26: [
        _mq("`export default function f() {}` — how can another file import it?",
            "Under any name: `import anything from \"./m\"`", ["Only as `import { f } from \"./m\"`", "Only as `import f from \"./m\"`", "Only with `require`"],
            "A default export has no fixed name at the import site."),
        _mq("What does `import * as m from \"./m\"` give you?",
            "A namespace object holding every export", ["Only the default export", "A copy of the file's source", "Every export as separate variables"],
            "Access them as `m.name`."),
        _mq("What does `export { a as b }` do?",
            "Exports the local `a` under the public name `b`", ["Renames `b` to `a`", "Exports both `a` and `b`", "Nothing — invalid syntax"],
            "Aliasing on export lets a module choose its public names."),
        _mq("`declare const x: number; console.log(x);` — with nothing else defining `x`, what happens at runtime?",
            "ReferenceError — `declare` emits nothing", ["Prints 0", "Prints `undefined`", "Compile error"],
            "`declare` only tells the compiler the value exists elsewhere. If it doesn't, the runtime disagrees."),
        _mq("How do you declare types for an untyped package `\"lib\"`?",
            "`declare module \"lib\" { … }` in a `.d.ts` file", ["`import type \"lib\"`", "`namespace lib { … }`", "`export module \"lib\"`"],
            "An ambient module declaration describes the package's exports."),
        _mq("What does `verbatimModuleSyntax` require?",
            "Type-only imports to be written with `import type`", ["All imports to use file extensions", "No default exports", "CommonJS output"],
            "Imports without `type` are kept in the output, so a type-only one must say so or the runtime would try to load it."),
        _mq("What does `esModuleInterop` mainly affect?",
            "Default-importing CommonJS modules", ["Circular imports", "`.d.ts` generation", "Type-only imports"],
            "It lets `import fs from \"fs\"` work against a CommonJS module that has no real default export."),
        _mq("Which is a `.d.ts` declaration for a function `add`?",
            "`export declare function add(a: number, b: number): number;`",
            ["`export function add(a, b) { return a + b; }`", "`declare add = (a: number, b: number) => number;`", "`export type add(a: number, b: number): number;`"],
            "Declarations have signatures and no bodies."),
        _mq("Why can circular imports bite at runtime?",
            "One module may run before the other has finished initialising its exports", ["They're always a compile error", "They duplicate the module", "They disable type checking"],
            "An import from a half-initialised module can be `undefined` (or in its temporal dead zone) when first used."),
        _mq("What does `isolatedModules` guarantee?",
            "Each file can be transpiled on its own, without type information from other files",
            ["Each file runs in its own process", "Modules can't import each other", "Every file has a default export"],
            "Single-file tools (esbuild, SWC, Node's stripping) need this: e.g. re-exporting a type must use `export type`."),
        _mq("What does `export type { User }` do at runtime?",
            "Nothing — it's erased entirely", ["Exports an empty object", "Exports `User` as a class", "It's an error in `.ts` files"],
            "Type-only exports and imports exist only for the compiler."),
    ],
}

for _tsw in TS_WEEKS:
    _n = _tsw["week"]
    _texts = [q["question"] for q in _tsw["quiz"]]
    for _drop in TS_QUIZ_DROP.get(_n, []):
        assert _drop in _texts, f"TS week {_n}: quiz drop target not found: {_drop!r}"
    _drops = set(TS_QUIZ_DROP.get(_n, []))
    _tsw["quiz"] = [q for q in _tsw["quiz"] if q["question"] not in _drops]
    _tsw["quiz"].extend(TS_QUIZ_MORE.get(_n, []))
    _tsw["quiz_sample"] = TS_QUIZ_SAMPLE

# Week 13 is the consolidation checkpoint for weeks 9-12 and schedules no
# chapters of its own, so its bank drew on nothing but its authored questions.
# Pull in the chapter questions of the weeks it consolidates.
_ts_by_week = {w["week"]: w for w in TS_WEEKS}
_ts_by_week[13]["quiz_from"] = [
    key for n in range(9, 13) for key in _ts_by_week[n]["concepts"]
]
