# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# "Coming from Python / JavaScript" notes for every TypeScript chapter
# (TS_MASTERY_ROADMAP.md X-09). The chapters' comparison box was written for
# Java programmers only; a learner may arrive from any of the three. Each entry
# is (from Python, from JavaScript), appended to the chapter's comparison note.
# exec()'d by gen_seed.py after the TypeScript chapters exist; the build fails
# if a TypeScript chapter has no entry.
# ---------------------------------------------------------------------------

TS_COMPARE = {
    "ts_program_io": ("Like `sys.stdin.read()` then `.split()` — the whole input arrives as one string. `console.log` is `print`, and it also separates arguments with a space.",
                      "The same Node APIs you know; the only addition is that `fs.readFileSync(0, \"utf8\")` is typed as returning `string`, so its methods are checked."),
    "ts_variables": ("There is no bare `x = 5`: every variable is declared, with `const` (never reassigned) or `let`. Python's module-level names correspond to `const` more often than you expect.",
                     "Unchanged from modern JavaScript — `const`/`let`, never `var`. What TypeScript adds is that the first value fixes the type: `let n = 1; n = \"x\"` is an error."),
    "ts_types": ("`number` is both `int` and `float` (one IEEE double); `string` and `boolean` are Python's `str` and `bool`. Annotations look like Python's hints, but here they are enforced before the program runs.",
                 "The same primitives as JavaScript's `typeof`. The difference is that an annotation is a promise the compiler holds you to, not a comment."),
    "ts_inference": ("Much like a type checker such as mypy inferring from assignments — but always on, and strict. `any` is the equivalent of an untyped Python value: it switches checking off.",
                     "You rarely need to write types on locals: TypeScript infers them from the JavaScript you already write. Reach for `unknown`, not `any`, for values you have not checked."),
    "ts_strings": ("Template literals `` `${x}` `` are f-strings. Strings are immutable, as in Python, and there is no separate `char` type either.",
                   "The same strings and template literals; TypeScript adds literal string types (`\"GET\" | \"POST\"`) on top of them."),
    "ts_string_methods": ("Most methods have a Python twin: `trim` ≈ `strip`, `split`, `startsWith` ≈ `startswith`, `includes` ≈ `in`, `padStart` ≈ `rjust`. There is no negative slicing with `[]` — use `slice(-3)` or `at(-1)`.",
                          "The same methods. TypeScript tells you which ones can return `undefined` (`at`) or `null` (`match`) before you trip over it."),
    "ts_regex": ("Regex literals `/…/g` replace `re.compile`. `match` returns an array or `null` (not a match object), and named groups are `(?<name>…)` without Python's `P`.",
                 "The same RegExp engine. TypeScript types a match as `RegExpMatchArray | null`, so forgetting the no-match case is a compile error."),
    "ts_unicode": ("Python strings are sequences of code points; JavaScript strings are UTF-16 code units, so `\"😀\".length` is 2 here and 1 in Python. `[...s]` gives code points.",
                   "Nothing changes at runtime — but the chapter's `Intl.Segmenter` and code-point iteration are the tools JavaScript programmers most often miss."),
    "ts_operators": ("`===` is Python's `==` for primitives; `&&`, `||`, `!` are `and`, `or`, `not`. `**` is the same, but `/` always gives a float and there is no `//` — use `Math.floor(a / b)`.",
                     "The same operators. TypeScript rejects some nonsense JavaScript allows, such as adding an object to a number or comparing values that can never be equal."),
    "ts_equality": ("`===` compares primitives by value and objects by identity — like Python's `is` for objects. Two lists with the same contents are not `===`; there is no deep `==`.",
                    "Always `===`. TypeScript flags comparisons that can never be true (TS2367) and `x === NaN` (TS2845)."),
    "ts_conditionals": ("Truthiness is close to Python's, with two traps: an empty array `[]` and an empty object `{}` are truthy. `switch` is Python's `match` on literals, but falls through without `break`.",
                        "The same `if`/`switch`/ternary. TypeScript narrows types inside each branch, which is the real reason to learn these carefully."),
    "ts_loops": ("`for (const x of xs)` is `for x in xs`. Beware `for…in`: it walks keys (as strings), like iterating a dict — it is not Python's `for … in`.",
                 "The same loops. Prefer `for…of` and array methods; `for…in` over an array gives string indices, and TypeScript types them that way."),
    "ts_number_math": ("One number type, so `7 / 2` is `3.5` and there is no integer overflow — but no arbitrary precision either above 2^53 (use `bigint`, like Python's big ints). `Math` is the `math` module.",
                       "Unchanged. TypeScript keeps `number` and `bigint` apart: mixing them is a compile error rather than a runtime TypeError."),
    "ts_number_format": ("`toFixed(2)` is `f\"{x:.2f}\"`, and `Intl.NumberFormat` does what `locale` formatting does. Floating-point surprises (`0.1 + 0.2`) are the same as in Python.",
                         "The same `toFixed`/`Intl`. For money, the chapter's integer-cents approach matters more than any type."),
    "ts_functions": ("`function f(x: number): string` is `def f(x: int) -> str:` with the hints enforced. Arrow functions are lambdas that can hold whole blocks.",
                     "The same functions and arrows; parameter annotations are the new part, and they are checked at every call site."),
    "ts_params": ("Optional `x?: T`, defaults `x = 1` and rest `...xs: T[]` map to Python's defaults and `*args`. There are no keyword arguments — pass an options object instead.",
                  "The same syntax. TypeScript checks that required parameters are passed and that a rest parameter's elements have the right type."),
    "ts_overloads": ("Like `typing.overload`: several signatures for callers, one implementation that handles them all.",
                     "Overload signatures are type-only: JavaScript still sees one function. They describe what callers may pass and get back."),
    "ts_closures_scope": ("Closures capture variables, not values, as in Python — but block scope is real: `let` inside a loop body is fresh each iteration, and there is no `nonlocal` needed to assign.",
                          "Identical runtime behaviour; the chapter's `let`-in-loops rule is the one that bites JavaScript code written with `var`."),
    "ts_higher_order": ("`map`/`filter`/`reduce` are methods on arrays rather than built-ins; `reduce` is `functools.reduce`. Currying and function returning functions work the same.",
                        "The same functions; TypeScript infers callback parameter types from the array, so `xs.map(x => …)` needs no annotations."),
    "ts_recursion": ("Same recursion, a smaller default stack (~10k frames), and no `sys.setrecursionlimit`. Convert deep recursion to a loop or explicit stack.",
                     "Unchanged at runtime; a recursive function needs its return type written when inference would depend on itself (TS7023)."),
    "ts_arrays": ("`T[]` is `list[T]`. Indexing past the end gives `undefined` rather than raising `IndexError` — which is what `noUncheckedIndexedAccess` makes you handle.",
                  "The same arrays. TypeScript adds element types and, with `noUncheckedIndexedAccess`, makes every index read say it may be missing."),
    "ts_array_methods": ("`sort` sorts in place and, without a comparator, compares as strings — `[10, 9].sort()` gives `[10, 9]`. Pass `(a, b) => a - b` for numbers.",
                         "The same methods; the typed callback parameters are the gain."),
    "ts_array_modern": ("`toSorted`/`toReversed` are `sorted()`/`reversed()`: new arrays, originals untouched. `Object.groupBy` is `itertools.groupby` without the need to sort first.",
                        "ES2023–2024 additions you may not have used yet; TypeScript knows their types as long as the `lib` includes them."),
    "ts_tuples": ("`[string, number]` is `tuple[str, int]`, but a TypeScript tuple is still a mutable array at runtime unless you make it `readonly`.",
                  "At runtime a tuple is just an array; the fixed length and per-position types exist only for the checker."),
    "ts_destructuring": ("`const [a, b] = xs` is tuple unpacking; `const { name } = user` has no Python twin short of `user[\"name\"]`. `...rest` is `*rest`.",
                         "The same destructuring; annotate the whole pattern (`{ a, b }: { a: number; b: string }`), not each name."),
    "ts_objects": ("Objects are dict-like records with fixed, known keys — closer to a dataclass than a `dict`. Use `Map` when the keys are data.",
                   "The same object literals; TypeScript checks every property access against the object's shape."),
    "ts_json": ("`JSON.parse`/`JSON.stringify` are `json.loads`/`json.dumps`. `JSON.parse` returns `any`, so annotate or validate what comes back.",
                "The same functions. The typing lesson is the one to take: never let `any` from `JSON.parse` spread through your code."),
    "ts_interfaces_types": ("An interface is a `typing.Protocol` or `TypedDict`: a shape any value can match without inheriting from it.",
                            "Interfaces and type aliases vanish at runtime; they describe the objects you already build."),
    "ts_aliases": ("`type Point = { x: number }` is a type alias, like `Point = TypedDict(...)` — names for shapes, nothing at runtime.",
                   "Pure types: nothing in the emitted JavaScript."),
    "ts_index_signatures": ("`Record<string, number>` is `dict[str, int]` — but a missing key reads as `undefined`, not a `KeyError`.",
                            "The same object-as-dictionary pattern; TypeScript can make you handle the missing-key case."),
    "ts_maps_sets": ("`Map` and `Set` are `dict` and `set` with any key type, insertion-ordered. Read with `get`/`has`, never brackets.",
                     "The same collections; TypeScript types their keys and values (`Map<string, number>`) and makes `get` return `V | undefined`."),
    "ts_set_algebra": ("`a.union(b)`, `a.intersection(b)`, `a.difference(b)` are Python's `|`, `&`, `-` on sets, as methods (ES2025).",
                       "The Set methods are new in ES2025 — older code converts to arrays and filters."),
    "ts_unions": ("`string | number` is `Union[str, int]` / `str | int`. The difference: you must narrow before using a member-specific method.",
                  "Unions describe values JavaScript already lets you mix; narrowing is how you prove which one you have."),
    "ts_literal_inference": ("Literal types like `\"GET\"` are `typing.Literal[\"GET\"]`; `as const` freezes a whole literal, like a `Final` tuple of literals.",
                             "No runtime change: `as const` only affects the inferred type (and makes it `readonly`)."),
    "ts_enums": ("A union of string literals plays the role of `enum.Enum` without any runtime object. TypeScript's own `enum` does generate code, which is why this course prefers unions.",
                 "`enum` is one of the few TypeScript features that emits JavaScript; unions of literals do not, and run under type stripping."),
    "ts_narrowing": ("Like `isinstance` narrowing in a type checker: after `typeof x === \"string\"` the checker knows `x` is a string in that branch.",
                     "The checks are plain JavaScript (`typeof`, `in`, `instanceof`); TypeScript simply follows them."),
    "ts_type_predicates": ("`x is Cat` is `TypeGuard[Cat]`: a function whose `True` result narrows its argument.",
                           "A predicate is an ordinary boolean function with a type-level promise about what `true` means."),
    "ts_nullish": ("`null`/`undefined` are Python's `None`, twice. `a ?? b` is `a if a is not None else b` — unlike `or`, it keeps `0` and `\"\"`.",
                   "With `strictNullChecks`, TypeScript makes you handle the `undefined` that JavaScript lets slip through; `?.` and `??` are the tools."),
    "ts_control_flow": ("The checker reasons about your `if`/`return` flow the way a Python type checker does, but assignments later in a function can widen a narrowed type again.",
                        "Nothing changes at runtime; learning which checks TypeScript can follow saves casts."),
    "ts_discriminated_unions": ("Like a union of dataclasses each with a `kind: Literal[...]` field, matched with `match`/`case` — and the checker proves every case is handled.",
                                "The `kind` field is ordinary data; the exhaustiveness check is what TypeScript adds."),
    "ts_top_bottom": ("`unknown` is `object` before checks; `never` is `NoReturn`/`Never`; `void` is a function returning `None`.",
                      "These are type-level ideas with no runtime form; `never` is how exhaustiveness is proved."),
    "ts_function_types": ("`(x: number) => string` is `Callable[[int], str]`.",
                          "Function types describe callbacks you already pass around; parameter names in them are documentation only."),
    "ts_type_testing": ("Like writing `reveal_type`/`assert_type` checks that must pass: tests that run in the compiler, not at runtime.",
                        "Type tests never execute: they fail the build when an inferred type drifts."),
    "ts_tsconfig": ("`strict` is roughly `mypy --strict`: the flags that make checking honest. Here they apply to every program before it runs.",
                    "`tsconfig.json` is the compiler's configuration; the flags change what is accepted, never the emitted JavaScript's behaviour."),
    "ts_modules": ("`import { f } from \"./m\"` is `from m import f`; there is no implicit module-level `__all__` — only `export`ed names are importable.",
                   "The same ES modules; `import type` imports names that exist only for the checker."),
    "ts_declaration_files": ("A `.d.ts` file is a `.pyi` stub: types for code written elsewhere, with no implementation.",
                             "Declaration files are how plain JavaScript libraries get types; `declare` describes what exists at runtime."),
    "ts_erasable_syntax": ("Node now runs TypeScript by deleting the types — like Python ignoring annotations at runtime. Only syntax that can simply be deleted is allowed.",
                           "Type stripping turns your file into the JavaScript you would have written; `enum`, `namespace` and parameter properties are the exceptions that need a compiler."),
    "ts_versions": ("Like tracking Python releases: new checker defaults and deprecations arrive with each version.",
                    "TypeScript versions change the checker, not the runtime; the JavaScript you run depends on your Node version."),
    "ts_assertions": ("`x as T` is `typing.cast(T, x)`: it changes what the checker believes and does nothing at runtime.",
                      "An assertion is erased completely; if it is wrong, the program is wrong and nothing will catch it."),
    "ts_satisfies": ("There is no Python twin: `satisfies` checks a value against a type without changing the value's inferred type.",
                     "`satisfies` is type-only; it gives you the check of an annotation and the precision of inference."),
    "ts_structural_typing": ("Structural typing is `Protocol` everywhere: any value with the right shape fits, no inheritance needed. It is duck typing, checked.",
                             "This is how JavaScript objects already behave; TypeScript checks shapes, not class names."),
    "ts_variance": ("The same rules as Python's generics: `list` is invariant, read-only `Sequence` covariant, callable parameters contravariant.",
                    "Variance explains which generic assignments are safe; it has no runtime form."),
    "ts_branded_types": ("Like `typing.NewType`: `UserId` is a `string` the checker will not confuse with other strings, at no runtime cost.",
                         "Brands exist only for the checker; the value is a plain string."),
    "ts_immutability": ("`readonly` arrays are tuples in spirit; `Object.freeze` is the runtime counterpart, like a `frozenset` for objects — but shallow.",
                        "`readonly` is compile-time only; `Object.freeze` is the runtime guard, and it is shallow."),
    "ts_parse_dont_validate": ("The same idea as parsing into a dataclass (or pydantic model) at the boundary, then trusting its types everywhere inside.",
                               "Turn untyped input into typed values once, at the edge, instead of re-checking it everywhere."),
    "ts_runtime_validation": ("A schema that yields both a runtime check and a static type is what pydantic does for Python.",
                              "Types disappear at runtime, so data from outside must be checked by code; a schema gives you both from one definition."),
    "ts_compose": ("`A & B` is a type with both shapes' fields — like a `TypedDict` that inherits from two others.",
                   "Intersections and `extends` are type-level; at runtime you build the combined object with spread."),
    "ts_utility_types": ("`Partial<T>` is roughly `TypedDict(total=False)`; `Pick`/`Omit` derive new shapes from old ones without restating them.",
                         "Utility types are built from mapped and conditional types; none of them exist at runtime."),
    "ts_generics": ("`function first<T>(xs: T[]): T` is `def first(xs: list[T]) -> T` with a `TypeVar` — declared inline.",
                    "Generics are erased: `first<number>` and `first<string>` are the same JavaScript function."),
    "ts_generic_constraints": ("`T extends { length: number }` is a `TypeVar` with a `bound`.",
                               "Constraints only affect checking; the emitted code is the same."),
    "ts_generic_inference": ("Like a type checker solving `TypeVar`s from the arguments — here with more machinery for literals and `const` type parameters.",
                             "Inference happens at each call; understanding it is how you avoid writing explicit type arguments."),
    "ts_keyof_indexed": ("`keyof T` is like `Literal` of a `TypedDict`'s keys; `T[\"name\"]` reads a field's type. Python has no direct equivalent.",
                         "`keyof` and indexed access are type-level; `typeof x` in a type position reads a value's type."),
    "ts_lookup_types": ("Deriving types from data (`keyof typeof TABLE`) keeps one source of truth, as an `Enum` built from a dict would.",
                        "Let the object you already have define the type, instead of writing both."),
    "ts_mapped_types": ("There is no Python equivalent: a mapped type builds a new object type by transforming each key of another.",
                        "Type-level only; the runtime counterpart is `Object.fromEntries(Object.entries(o).map(…))`."),
    "ts_key_remapping": ("No Python equivalent: `as` in a mapped type renames or drops keys at the type level.",
                         "The type-level mirror of renaming keys with `Object.entries` and `map`."),
    "ts_conditional_types": ("No Python equivalent: `T extends U ? X : Y` is an `if` evaluated by the type checker, and `infer` pattern-matches types.",
                             "Conditional types compute types from types; nothing runs."),
    "ts_distributive": ("No Python equivalent; distribution is `map` over a union's members, done by the checker.",
                        "A type-level rule; the chapter's `[T]` wrapper is the idiom for turning it off."),
    "ts_template_literal_types": ("Like `Literal` strings that can be built from other literals: `` `on${Capitalize<E>}` ``.",
                                  "Template literal types mirror template strings at the type level."),
    "ts_type_level": ("No Python equivalent: recursive types and type-level computation are a TypeScript speciality.",
                      "Type-level programs run in the compiler; keep them small and readable."),
    "ts_type_performance": ("No Python equivalent — Python's checkers do not compute this much at the type level. The limits exist to keep the compiler fast.",
                            "Deep type computation slows the editor; the chapter shows the limits and how to stay inside them."),
    "ts_classes": ("Classes are close to Python's: `constructor` is `__init__`, `this` is `self` (implicit), and fields are declared up front. `#x` is a real private field — stronger than `_x`.",
                   "The same ES classes; TypeScript adds field types and `implements` checks. Prefer `#private` to TypeScript's compile-time-only `private`."),
    "ts_this_accessors": ("`get area()` is `@property`. Unlike Python's bound methods, a detached method loses `this` — `const f = obj.m; f()` breaks.",
                          "The same `this` rules; TypeScript can type `this` and catch detached calls (TS2684)."),
    "ts_class_design": ("`abstract` classes are `abc.ABC` with `@abstractmethod`; composition over inheritance holds just the same.",
                        "`abstract`, `implements` and `override` are checked by TypeScript; only the class itself exists at runtime."),
    "ts_decorators": ("Similar in spirit to Python decorators, but they apply to classes and class members only, and receive a `context` object.",
                      "Standard (TC39) decorators — not the older `experimentalDecorators` many libraries used."),
    "ts_iterators": ("Generators with `function*` and `yield` are Python generators; `Symbol.iterator` is `__iter__`.",
                     "The same iteration protocol; TypeScript types what is yielded, returned and passed to `next`."),
    "ts_iterator_helpers": ("`iter.map(…).filter(…).take(3)` is `itertools` as methods — lazy, like a generator pipeline.",
                            "Iterator helpers (ES2025) bring array-style methods to any iterator, lazily."),
    "ts_ds_generics": ("Generic classes are `class Stack(Generic[T])` — the type parameter is declared on the class.",
                       "Type parameters on classes are erased; one runtime class serves every element type."),
    "ts_heap_pq": ("There is no `heapq` built in: the chapter builds the heap by hand, with a comparator instead of tuple ordering.",
                   "JavaScript has no standard priority queue either; this is the one to write once and reuse."),
    "ts_errors": ("`try`/`catch`/`finally` is `try`/`except`/`finally`, with one `catch` for everything: you narrow `e` yourself, since anything can be thrown.",
                  "The same statements; under `strict` the caught value is `unknown`, so you must check it before reading `.message`."),
    "ts_error_types": ("Returning a `Result` instead of raising is less common in Python, closer to returning `(value, error)` pairs — but the checker enforces handling both.",
                       "A discriminated-union result makes failure part of the function's type; `throw` does not appear in any signature."),
    "ts_error_cause": ("`new Error(msg, { cause })` is `raise … from err`; `AggregateError` groups several, like an `ExceptionGroup`.",
                       "`cause` is standard since ES2022; TypeScript types it as `unknown`."),
    "ts_resource_management": ("`using x = …` is `with` for a single resource: disposal runs when the block ends, even on an exception.",
                               "`using`/`await using` are new (explicit resource management); they replace `try`/`finally` cleanup."),
    "ts_async": ("`async`/`await` read like Python's asyncio, but no event loop needs starting: Node always has one, and a `Promise` starts running when created, unlike a coroutine.",
                 "The same promises; TypeScript types the resolved value (`Promise<T>`) and catches a forgotten `await` in a condition (TS2801)."),
    "ts_async_patterns": ("`Promise.all` is `asyncio.gather`; `Promise.race` is `asyncio.wait(..., FIRST_COMPLETED)`.",
                          "The same combinators; TypeScript infers a tuple of results from a tuple of promises."),
    "ts_event_loop": ("One thread, one event loop, like asyncio — but promise callbacks (microtasks) always run before timers.",
                      "The same event loop; the chapter makes the microtask-before-timer order predictable."),
    "ts_cancellation": ("`AbortController` plays the role of cancelling an asyncio task: you pass its `signal` down, and work checks it.",
                        "The standard web cancellation API, available in Node; TypeScript types the signal and its `reason`."),
    "ts_async_iteration": ("`for await (const x of stream)` is `async for x in stream`; `async function*` is an async generator.",
                           "The same async iteration; TypeScript types the values as they arrive."),
}

# Notes that compare with Java without saying "Java" (Streams, HashMap, POJOs…).
_CMP_JAVA = {"ts_narrowing", "ts_array_methods", "ts_objects", "ts_maps_sets", "ts_async", "ts_json",
             "ts_immutability", "ts_higher_order", "ts_async_patterns", "ts_regex"}

_missing_compare = sorted(k for k, c in CONCEPTS.items()
                          if c.get("language") == "typescript" and k not in TS_COMPARE)
assert not _missing_compare, f"X-09: TypeScript chapters without Python/JavaScript notes: {_missing_compare}"
for _cmp_key, (_cmp_py, _cmp_js) in TS_COMPARE.items():
    assert _cmp_key in CONCEPTS, f"X-09: notes for an unknown chapter {_cmp_key}"
    _cmp_note = CONCEPTS[_cmp_key]["java"].rstrip()
    # The original note speaks to Java programmers; say so now that it has company.
    if "Java" in _cmp_note.replace("JavaScript", "") or "NullPointer" in _cmp_note or _cmp_key in _CMP_JAVA:
        _cmp_note = "**From Java:** " + _cmp_note
    CONCEPTS[_cmp_key]["java"] = _cmp_note + f"\n\n**From Python:** {_cmp_py}\n\n**From JavaScript:** {_cmp_js}"
