# -*- coding: utf-8 -*-
# Glossary entries for every compiler error a TypeScript chapter shows
# (TS_MASTERY_ROADMAP.md X-07). Each `bad` program is the chapter's own
# snippet; gen_ts_errors.py type-checks bad (must report the code) and good
# (must report nothing) before writing anything. Imported by gen_ts_errors.py.

MORE_ERRORS = [
    (1039, "Initializers are not allowed in ambient contexts",
     "A `declare` statement gave a value.",
     "`declare` only describes something that exists elsewhere — it never creates it, so it cannot set a value. Drop the initializer, or drop `declare` if you meant to define it here.",
     'declare let version: string = "1.0";',
     "declare let version: string;", 14),
    (1064, "The return type of an async function must be Promise<T>",
     "An async function was annotated with a plain return type.",
     "An `async` function always returns a promise, whatever its body returns. Annotate what callers really get: `Promise<number>`, not `number`.",
     "async function count(): number {\n  return 3;\n}",
     "async function count(): Promise<number> {\n  return 3;\n}\ncount().then(console.log);", 26),
    (1103, "'for await' loops are only allowed within async functions",
     "A `for await` loop sits in an ordinary function.",
     "Waiting needs an async context. Make the enclosing function `async` (it then returns a promise), or move the loop to the module's top level.",
     "async function* ticks(): AsyncGenerator<number> {\n  yield 1;\n}\nfunction show(): void {\n  for await (const t of ticks()) console.log(t);\n}",
     "async function* ticks(): AsyncGenerator<number> {\n  yield 1;\n}\nasync function show(): Promise<void> {\n  for await (const t of ticks()) console.log(t);\n}\nshow();", 26),
    (1196, "Catch clause variable type annotation must be 'any' or 'unknown'",
     "`catch (e: Error)` claims to know what was thrown.",
     "Anything can be thrown — a string, a number, `undefined` — so the compiler will not let you promise it is an `Error`. Leave it `unknown` and narrow with `instanceof Error`.",
     'try {\n  JSON.parse("{");\n} catch (e: Error) {\n  console.log(e.message);\n}',
     'try {\n  JSON.parse("{");\n} catch (e) {\n  console.log(e instanceof Error ? e.message : String(e));\n}', 25),
    (1206, "Decorators are not valid here",
     "A decorator was put on something that cannot take one.",
     "Decorators apply to classes and class members only — not to plain functions or variables. For a function, wrap it in a higher-order function instead.",
     "function logged(target: unknown, context: unknown) {\n  return target;\n}\n@logged\nfunction greet() {\n  return \"hi\";\n}",
     "function logged<T extends () => string>(fn: T): T {\n  return fn;\n}\nconst greet = logged(() => \"hi\");\nconsole.log(greet());", 23),
    (1241, "Unable to resolve signature of method decorator",
     "The decorator's parameters do not match how decorators are called.",
     "Standard (TC39) decorators receive `(value, context)`. A legacy three-argument `(target, key, descriptor)` decorator only works under `experimentalDecorators`. Write the standard signature.",
     "function legacy(target: object, key: string, descriptor: PropertyDescriptor) {\n  return descriptor;\n}\nclass Calc {\n  @legacy\n  add(a: number, b: number) {\n    return a + b;\n  }\n}",
     "function logged<T>(target: T, context: ClassMethodDecoratorContext): T {\n  console.log(\"decorating\", String(context.name));\n  return target;\n}\nclass Calc {\n  @logged\n  add(a: number, b: number) {\n    return a + b;\n  }\n}", 23),
    (1361, "Cannot be used as a value because it was imported using 'import type'",
     "Something imported with `import type` was used at runtime.",
     "`import type` is erased completely, so nothing is there to call. Use a plain `import` for values; keep `import type` for names used only in types.",
     'import type { readFileSync } from "fs";\nconst text = readFileSync(0, "utf8");\nconsole.log(text.length);',
     'import { readFileSync } from "fs";\nconst text = readFileSync(0, "utf8");\nconsole.log(text.length);', 14),
    (2305, "Module has no exported member",
     "You imported a name the module does not export.",
     "Check the spelling and the module's actual exports — often a similarly named export exists (`readFileSync`, not `readFile`), or it is a default export.",
     'import { readFile } from "fs";',
     'import { readFileSync } from "fs";\nconsole.log(typeof readFileSync);', 14),
    (2307, "Cannot find module",
     "The import path does not lead to a module the compiler can see.",
     "Check the relative path and file name. For a package, its types must be installed. In a single-file program there is no `./math` — define it in the same file.",
     'import { add } from "./math";\nconsole.log(add(1, 2));',
     "function add(a: number, b: number): number {\n  return a + b;\n}\nconsole.log(add(1, 2));", 14),
    (2312, "An interface can only extend an object type with statically known members",
     "An interface tried to extend a union.",
     "An interface needs one fixed set of members to extend, and a union has several possible shapes. Use a type alias with an intersection instead.",
     "type Pet = { name: string } | { id: number };\ninterface Owner extends Pet {}",
     "type Pet = { name: string } | { id: number };\ntype Owner = Pet & { since: number };\nconst o: Owner = { name: \"rex\", since: 2020 };\nconsole.log(o.since);", 17),
    (2348, "Value of type 'typeof X' is not callable. Did you mean to include 'new'?",
     "A class was called like a function.",
     "Classes are constructed with `new`. Calling one without it throws at runtime, and TypeScript refuses it up front.",
     "class Point {\n  x = 0;\n}\nconst p = Point();",
     "class Point {\n  x = 0;\n}\nconst p = new Point();\nconsole.log(p.x);", 13),
    (2394, "This overload signature is not compatible with its implementation signature",
     "The implementation cannot handle every overload.",
     "The implementation signature must accept everything each overload accepts. Widen its parameter types (usually to a union) so every overload is covered.",
     "function size(value: string): number;\nfunction size(value: number[]): number;\nfunction size(value: string): number {\n  return value.length;\n}\nconsole.log(size(\"abc\"));",
     "function size(value: string): number;\nfunction size(value: number[]): number;\nfunction size(value: string | number[]): number {\n  return value.length;\n}\nconsole.log(size(\"abc\"));", 5),
    (2420, "Class incorrectly implements interface",
     "A class says `implements X` but is missing some of X's members.",
     "`implements` is a checked promise: every member the interface lists must exist with a compatible type. Add what is missing (the message lists it).",
     "interface Shape {\n  area(): number;\n}\nclass Square implements Shape {\n  readonly side: number;\n  constructor(side: number) {\n    this.side = side;\n  }\n  perimeter(): number {\n    return this.side * 4;\n  }\n}",
     "interface Shape {\n  area(): number;\n}\nclass Square implements Shape {\n  readonly side: number;\n  constructor(side: number) {\n    this.side = side;\n  }\n  area(): number {\n    return this.side ** 2;\n  }\n}\nconsole.log(new Square(3).area());", 23),
    (2430, "Interface incorrectly extends interface",
     "An extending interface redeclared a member with an incompatible type.",
     "A sub-interface may narrow an inherited member, never change it to something unrelated. Rename the new member, or rethink the relationship.",
     "interface Base {\n  id: number;\n}\ninterface Doc extends Base {\n  id: string;\n}",
     "interface Base {\n  id: number;\n}\ninterface Doc extends Base {\n  title: string;\n}\nconst d: Doc = { id: 1, title: \"notes\" };\nconsole.log(d.title);", 10),
    (2456, "Type alias circularly references itself",
     "A type alias is defined directly in terms of itself.",
     "A type may refer to itself only through a structure — an array, an object property, a function — never as a bare member of its own union.",
     "type Bad = Bad | string;",
     "type Tree = string | Tree[];\nconst t: Tree = [\"a\", [\"b\"]];\nconsole.log(JSON.stringify(t));", 22),
    (2515, "Non-abstract class does not implement inherited abstract member",
     "A concrete subclass left an abstract member unimplemented.",
     "An abstract member is a hole the subclass must fill. Implement it, or mark the subclass `abstract` too.",
     "abstract class Shape {\n  abstract area(): number;\n  abstract readonly name: string;\n}\nclass Square extends Shape {\n  readonly name = \"square\";\n}",
     "abstract class Shape {\n  abstract area(): number;\n  abstract readonly name: string;\n}\nclass Square extends Shape {\n  readonly name = \"square\";\n  area(): number {\n    return 4;\n  }\n}\nconsole.log(new Square().area());", 23),
    (2542, "Index signature only permits reading",
     "You tried to assign through an index that is read-only.",
     "Strings are immutable, so `s[0] = …` can never work; readonly arrays forbid it too. Build a new value instead.",
     "const s: string = \"cat\";\ns[0] = \"b\";",
     "const s: string = \"cat\";\nconst t = \"b\" + s.slice(1);\nconsole.log(t);", 4),
    (2555, "Expected at least N arguments, but got M",
     "A call left out a required argument before a rest parameter.",
     "Rest parameters may be empty, but the required parameters before them may not. Pass them.",
     "function log(level: string, ...messages: string[]): void {\n  console.log(level, messages.join(\" \"));\n}\nlog();",
     "function log(level: string, ...messages: string[]): void {\n  console.log(level, messages.join(\" \"));\n}\nlog(\"info\");", 5),
    (2558, "Expected N type arguments, but got M",
     "An explicit type argument list has the wrong length.",
     "Pass exactly as many type arguments as the generic declares — or none, and let inference work them out.",
     "function pair<T>(a: T, b: T): [T, T] {\n  return [a, b];\n}\nconst p = pair<string, number>(\"a\", 1);",
     "function pair<T>(a: T, b: T): [T, T] {\n  return [a, b];\n}\nconst p = pair<string>(\"a\", \"b\");\nconsole.log(p);", 18),
    (2559, "Type has no properties in common with type",
     "A value shares nothing with an all-optional ('weak') type.",
     "A type whose properties are all optional would accept almost anything, so TypeScript insists a value shares at least one of them. Pass an object with the options.",
     "interface Options {\n  verbose?: boolean;\n}\nfunction configure(o: Options): string {\n  return \"configured with \" + JSON.stringify(o);\n}\nconsole.log(configure(42));",
     "interface Options {\n  verbose?: boolean;\n}\nfunction configure(o: Options): string {\n  return \"configured with \" + JSON.stringify(o);\n}\nconsole.log(configure({ verbose: true }));", 15),
    (2589, "Type instantiation is excessively deep and possibly infinite",
     "A recursive type recursed too far.",
     "The checker caps recursion depth. Keep recursive types shallow, use tail-recursive conditional types (which get a higher limit), or compute less at the type level.",
     "type BuildWrapped<N extends number, T extends unknown[] = []> =\n  T[\"length\"] extends N ? [] : [0, ...BuildWrapped<N, [...T, 0]>];\ntype Many = BuildWrapped<200>;\nconst m: Many = [];",
     "type BuildWrapped<N extends number, T extends unknown[] = []> =\n  T[\"length\"] extends N ? [] : [0, ...BuildWrapped<N, [...T, 0]>];\ntype Few = BuildWrapped<3>;\nconst m: Few = [0, 0, 0];\nconsole.log(m.length);", 22),
    (2590, "Expression produces a union type that is too complex to represent",
     "A type expanded into more union members than the checker allows.",
     "Unions are capped at 100,000 members; a template literal of six digits makes a million. Validate the shape at runtime, or use a branded `string`, instead of enumerating it.",
     "type Digit = \"0\" | \"1\" | \"2\" | \"3\" | \"4\" | \"5\" | \"6\" | \"7\" | \"8\" | \"9\";\ntype Code = `${Digit}${Digit}${Digit}${Digit}${Digit}${Digit}`;\nconst c: Code = \"123456\";",
     "type Digit = \"0\" | \"1\" | \"2\" | \"3\" | \"4\" | \"5\" | \"6\" | \"7\" | \"8\" | \"9\";\ntype Code = `${Digit}${Digit}${Digit}`;\nconst c: Code = \"123\";\nconsole.log(c);", 22),
    (2591, "Cannot find name 'require'",
     "CommonJS `require` was used in an ES module.",
     "This environment runs ES modules: use `import`. (`require` also needs Node's type definitions to be known to the checker.)",
     'const fs = require("fs");\nconsole.log(typeof fs.readFileSync);',
     'import * as fs from "fs";\nconsole.log(typeof fs.readFileSync);', 14),
    (2636, "Type is not assignable as implied by variance annotation",
     "A variance annotation (`in`/`out`) contradicts how the type parameter is used.",
     "`out T` promises T only flows out; a setter taking T makes it flow in too. Use `in out T` (invariant) or remove the member that breaks the promise.",
     "interface Box<out T> {\n  get(): T;\n  set: (value: T) => void;\n}",
     "interface Box<in out T> {\n  get(): T;\n  set: (value: T) => void;\n}\nlet stored = 1;\nconst b: Box<number> = { get: () => stored, set: (v) => { stored = v; } };\nb.set(2);\nconsole.log(b.get());", 15),
    (2673, "Constructor of class is private",
     "`new` was used on a class whose constructor is private.",
     "A private constructor means instances are made only through the class's own factory (`static open(...)`). Call that instead.",
     "class Account {\n  private constructor(readonly owner: string) {}\n  static open(owner: string) {\n    return new Account(owner);\n  }\n}\nconst a = new Account(\"ana\");",
     "class Account {\n  private constructor(readonly owner: string) {}\n  static open(owner: string) {\n    return new Account(owner);\n  }\n}\nconst a = Account.open(\"ana\");\nconsole.log(a.owner);", 23),
    (2677, "A type predicate's type must be assignable to its parameter's type",
     "`x is T` names a type that `x` could never be.",
     "A predicate narrows the parameter to a subtype of what it already is. A `string` can never be a `number`; take `unknown` (or a union) instead.",
     "function isNumber(x: string): x is number {\n  return !Number.isNaN(Number(x));\n}",
     "function isNumber(x: unknown): x is number {\n  return typeof x === \"number\";\n}\nconsole.log(isNumber(3));", 11),
    (2678, "Type is not comparable to type",
     "A `case` (or comparison) uses a value the switched type can never be.",
     "A `case` label outside the union is dead code — usually a typo or a member missing from the type. Fix the label, or add the member.",
     "type Size = \"s\" | \"m\";\nfunction label(size: Size): string {\n  switch (size) {\n    case \"s\":\n      return \"small\";\n    case \"x\":\n      return \"extra\";\n    default:\n      return \"medium\";\n  }\n}",
     "type Size = \"s\" | \"m\" | \"x\";\nfunction label(size: Size): string {\n  switch (size) {\n    case \"s\":\n      return \"small\";\n    case \"x\":\n      return \"extra\";\n    default:\n      return \"medium\";\n  }\n}\nconsole.log(label(\"x\"));", 2),
    (2684, "The 'this' context is not assignable to method's 'this'",
     "A method that needs its `this` was called detached from its object.",
     "Pulling a method off an object loses `this`. Call it on the object, bind it, or wrap it in an arrow.",
     "class Counter {\n  count = 0;\n  inc(this: Counter): void {\n    this.count++;\n  }\n}\nconst c = new Counter();\nconst inc = c.inc;\ninc();",
     "class Counter {\n  count = 0;\n  inc(this: Counter): void {\n    this.count++;\n  }\n}\nconst c = new Counter();\nconst inc = () => c.inc();\ninc();\nconsole.log(c.count);", 23),
    (2693, "Only refers to a type, but is being used as a value",
     "A type was used where a runtime value is needed.",
     "Types are erased, so `instanceof Circle` has nothing to test against when `Circle` is a type. Narrow on a property (`\"radius\" in s`) or a discriminant instead.",
     "type Circle = { radius: number };\ntype Square = { side: number };\nfunction area(s: Circle | Square): number {\n  if (s instanceof Circle) return Math.PI * s.radius ** 2;\n  return s.side ** 2;\n}",
     "type Circle = { radius: number };\ntype Square = { side: number };\nfunction area(s: Circle | Square): number {\n  if (\"radius\" in s) return Math.PI * s.radius ** 2;\n  return s.side ** 2;\n}\nconsole.log(area({ side: 2 }));", 14),
    (2749, "Refers to a value, but is being used as a type",
     "A value's name was used as a type.",
     "A `const` object is a value; to use its shape as a type, write `typeof Level` — or derive the union of its values with `(typeof Level)[keyof typeof Level]`.",
     "const Level = { Debug: 10, Info: 20, Warn: 30 } as const;\nfunction show(level: Level): string {\n  return String(level);\n}",
     "const Level = { Debug: 10, Info: 20, Warn: 30 } as const;\ntype Level = (typeof Level)[keyof typeof Level];\nfunction show(level: Level): string {\n  return String(level);\n}\nconsole.log(show(Level.Info));", 14),
    (2775, "Assertions require every name in the call target to be declared with an explicit type annotation",
     "An assertion function was written as an arrow without an annotated variable.",
     "The checker only honours `asserts` when the function's type is known up front. Use a `function` declaration, or annotate the variable's type.",
     "const assertPositive = (n: number): asserts n => {\n  if (n <= 0) throw new Error(\"not positive\");\n};\nassertPositive(3);",
     "function assertPositive(n: number): asserts n {\n  if (n <= 0) throw new Error(\"not positive\");\n}\nassertPositive(3);\nconsole.log(\"ok\");", 11),
    (2801, "This condition will always return true since this Promise is always defined",
     "A promise was tested for truthiness instead of being awaited.",
     "A promise object is always truthy, whatever it will resolve to. `await` it to test the value.",
     "async function isReady(): Promise<boolean> {\n  return false;\n}\nif (isReady()) console.log(\"ready!\");",
     "async function isReady(): Promise<boolean> {\n  return false;\n}\nif (await isReady()) console.log(\"ready!\");", 26),
    (2820, "Type is not assignable. Did you mean …?",
     "A string literal is almost, but not quite, one of the allowed literals.",
     "The typo is caught because the type lists the allowed strings. Fix the spelling — the message suggests the closest match.",
     "const PRICES = { apple: 1.2, pear: 0.8 } as const;\ntype Fruit = keyof typeof PRICES;\nconst basket: Fruit[] = [\"apple\", \"aple\", \"pear\"];",
     "const PRICES = { apple: 1.2, pear: 0.8 } as const;\ntype Fruit = keyof typeof PRICES;\nconst basket: Fruit[] = [\"apple\", \"apple\", \"pear\"];\nconsole.log(basket.reduce((sum, f) => sum + PRICES[f], 0));", 19),
    (2845, "This condition will always return 'false'",
     "A comparison with `NaN` can never be true.",
     "`NaN` is not equal to anything, itself included, so `x === NaN` is always false. Use `Number.isNaN(x)`.",
     "const n = Number(\"x\");\nconsole.log(n === NaN ? \"not a number\" : `ok: ${n}`);",
     "const n = Number(\"x\");\nconsole.log(Number.isNaN(n) ? \"not a number\" : `ok: ${n}`);", 2),
    (2850, "The initializer of a 'using' declaration must have a [Symbol.dispose]() method",
     "`using` was given an object that does not know how to dispose of itself.",
     "`using` calls `[Symbol.dispose]()` at the end of the scope; a `close()` method is not enough. Implement the symbol method (it can call `close`).",
     "const handle = { close() {} };\nfunction read() {\n  using h = handle;\n}",
     "const handle = {\n  close() {\n    console.log(\"closed\");\n  },\n  [Symbol.dispose]() {\n    this.close();\n  },\n};\nfunction read() {\n  using h = handle;\n  console.log(\"reading\", typeof h);\n}\nread();", 25),
    (2852, "'await using' statements are only allowed within async functions",
     "`await using` sits in an ordinary function.",
     "Asynchronous disposal has to be awaited, which needs an async context. Make the function `async`.",
     "function read(conn: AsyncDisposable) {\n  await using c = conn;\n}",
     "async function read(conn: AsyncDisposable) {\n  await using c = conn;\n  console.log(typeof c);\n}\nread({ [Symbol.asyncDispose]: async () => {} });", 25),
    (4104, "The type 'readonly T[]' is 'readonly' and cannot be assigned to the mutable type",
     "A readonly array was passed where a mutable one is expected.",
     "A mutable array type would let the receiver `push` into data that promised not to change. Copy it (`[...xs]`), or make the receiver accept `readonly T[]`.",
     "const frozen: readonly number[] = [1, 2];\nconst editable: number[] = frozen;",
     "const frozen: readonly number[] = [1, 2];\nconst editable: number[] = [...frozen];\neditable.push(3);\nconsole.log(editable);", 16),
    (4113, "This member cannot have an 'override' modifier because it is not declared in the base class",
     "`override` is on a method the base class does not have.",
     "`override` is a checked claim: it catches renames and typos. Match the base class's member name, or drop `override` if the method is new.",
     "class Base {\n  greet(): string {\n    return \"hi\";\n  }\n}\nclass Loud extends Base {\n  override greeting(): string {\n    return \"HI\";\n  }\n}",
     "class Base {\n  greet(): string {\n    return \"hi\";\n  }\n}\nclass Loud extends Base {\n  override greet(): string {\n    return \"HI\";\n  }\n}\nconsole.log(new Loud().greet());", 23),
    (5076, "'??' and '||' operations cannot be mixed without parentheses",
     "`??` and `||` appear in one expression with nothing saying which comes first.",
     "The two operators treat `0` and `\"\"` differently, so their order matters and JavaScript refuses to guess. Add parentheses.",
     "const a: number | undefined = undefined;\nconst b = 0;\nconsole.log(a ?? b || 5);",
     "const a: number | undefined = undefined;\nconst b = 0;\nconsole.log((a ?? b) || 5);", 2),
    (6234, "This expression is not callable because it is a 'get' accessor",
     "A getter was called like a method.",
     "A `get` accessor is read like a property. Drop the parentheses.",
     "class Rect {\n  readonly w = 3;\n  readonly h = 4;\n  get area(): number {\n    return this.w * this.h;\n  }\n}\nconsole.log(new Rect().area());",
     "class Rect {\n  readonly w = 3;\n  readonly h = 4;\n  get area(): number {\n    return this.w * this.h;\n  }\n}\nconsole.log(new Rect().area);", 23),
    (7023, "Implicitly has return type 'any' because it is referenced in its own return expressions",
     "A recursive function's return type cannot be inferred.",
     "To infer the return type the checker would need the return type. Annotate it.",
     "function depth(tree: { children: unknown[] }) {\n  return tree.children.length === 0\n    ? 1\n    : 1 + Math.max(...tree.children.map((c) => depth(c as { children: unknown[] })));\n}\nconsole.log(depth({ children: [] }));",
     "function depth(tree: { children: unknown[] }): number {\n  return tree.children.length === 0\n    ? 1\n    : 1 + Math.max(...tree.children.map((c) => depth(c as { children: unknown[] })));\n}\nconsole.log(depth({ children: [] }));", 6),
    (7031, "Binding element implicitly has an 'any' type",
     "A destructured parameter has no type.",
     "Destructuring does not give the parameter a type. Annotate the whole pattern: `({ name, age }: { name: string; age: number })`.",
     "function describe({ name, age }) {\n  return `${name} (${age})`;\n}",
     "function describe({ name, age }: { name: string; age: number }) {\n  return `${name} (${age})`;\n}\nconsole.log(describe({ name: \"ada\", age: 36 }));", 14),
    (7052, "Element implicitly has an 'any' type because type has no index signature. Did you mean to call 'set'?",
     "Brackets were used to write to a `Map`.",
     "`map[key] = value` sets an ordinary property that `get` and `size` never see. Use `map.set(key, value)`.",
     "const ages = new Map<string, number>();\nages[\"ana\"] = 31;\nconsole.log(ages.size);",
     "const ages = new Map<string, number>();\nages.set(\"ana\", 31);\nconsole.log(ages.size);", 9),
]
