# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# "In an interview" — the section every TypeScript chapter ends with.
#
# The chapters teach the syntax and a "Watch out for" list; none of them said
# what an interviewer actually asks about the topic, or what a good answer
# sounds like. Each chapter gets three questions with a model answer — short
# enough to say out loud, specific enough to show you know why, not just what.
#
# exec()'d inside gen_seed.py's namespace after typescript_mastery.py, so every
# TypeScript concept already has its lesson in LESSONS; this appends to them.
# The build fails if a TypeScript chapter is missing, or a key is not a chapter.
# ---------------------------------------------------------------------------

TS_INTERVIEW = {
    "ts_variables": [
        ("`let`, `const` or `var` — which do you use, and why?",
         "`const` by default, `let` when the binding really changes, `var` never. `var` is function-scoped and hoisted, which causes bugs like every loop callback seeing the last index; `let`/`const` are block-scoped and live in a temporal dead zone until declared."),
        ("Does `const` make an object immutable?",
         "No. It makes the *binding* immutable — you can't point the name at another value — but the object's properties can still change. For that you want `readonly` types, `as const`, or `Object.freeze`."),
        ("What is the temporal dead zone?",
         "The span between entering a block and the `let`/`const` declaration line. Reading the variable there throws a `ReferenceError`, which is what catches use-before-declaration bugs that `var` would hide as `undefined`."),
    ],
    "ts_types": [
        ("What are the primitive types in TypeScript?",
         "`string`, `number`, `bigint`, `boolean`, `symbol`, `undefined` and `null`. Everything else — arrays, functions, dates — is an object type."),
        ("Why is there no `int` type?",
         "JavaScript has one number type, an IEEE-754 double, and TypeScript describes JavaScript. Integers above 2^53 lose precision; `bigint` is the separate type for arbitrarily large integers."),
        ("Where do you actually write type annotations?",
         "On function parameters (they can't be inferred) and on exported/public return types (they pin the contract). Locals are usually inferred from their initialiser, and annotating them adds noise."),
    ],
    "ts_inference": [
        ("`any` vs `unknown` — when would you use each?",
         "`unknown` for a value you haven't checked yet — it forces you to narrow before using it. `any` switches checking off entirely; I only accept it at a boundary I'm about to replace, and prefer `unknown` even there."),
        ("What does TypeScript infer for `const x = 5` versus `let y = 5`?",
         "`x` is the literal type `5`, because a `const` can never change. `y` widens to `number`, because it can be reassigned. This widening rule explains most \"why is this a string, not my literal?\" questions."),
        ("What is contextual typing?",
         "Inference flowing *into* an expression from where it's used: in `nums.map((n) => n * 2)`, `n` is typed from `nums`' element type. It's why callbacks rarely need annotations."),
    ],
    "ts_strings": [
        ("Template literal or concatenation?",
         "Template literals: they read naturally, handle multi-line text, and interpolate expressions. Concatenation with `+` is easy to get wrong when a number is involved (`\"1\" + 2` is `\"12\"`)."),
        ("Are strings mutable?",
         "No. Every string method returns a new string; `s[0] = \"x\"` silently does nothing. To change one character you build a new string."),
        ("Why can `\"😀\".length` be 2?",
         "`length` counts UTF-16 code units, and characters outside the Basic Multilingual Plane take two. Iterating with `for…of` or spreading `[...s]` walks code points instead."),
    ],
    "ts_operators": [
        ("`==` vs `===`?",
         "`===` compares without coercion and is what I use everywhere. `==` coerces types first, so `\"\" == 0` is true. The one common exception is `x == null`, which checks for both `null` and `undefined`."),
        ("`||` vs `??`?",
         "`||` falls back on any falsy value, including `0` and `\"\"`; `??` only on `null` and `undefined`. For defaults, `??` is almost always what you mean."),
        ("What does optional chaining return when it short-circuits?",
         "`undefined`. `a?.b.c` stops at `a` if it's nullish, but only guards that link — if `a.b` is `undefined`, `.c` still throws."),
    ],
    "ts_conditionals": [
        ("Which values are falsy?",
         "`false`, `0`, `-0`, `0n`, `\"\"`, `null`, `undefined` and `NaN`. Everything else is truthy — including `\"0\"`, `[]` and `{}`."),
        ("Why can `if (value)` be a bug?",
         "It rejects `0` and `\"\"` along with `null`/`undefined`. When zero or empty is a valid value, compare explicitly: `if (value !== undefined)`."),
        ("`switch` or an object lookup?",
         "A lookup table when each case just maps a key to a value — it's data, easy to extend, and `Record<Key, Value>` makes the compiler check it's complete. A `switch` when cases run different logic, especially over a discriminated union with an exhaustiveness check."),
    ],
    "ts_loops": [
        ("`for…of` vs `for…in`?",
         "`for…of` iterates values of any iterable (arrays, strings, Maps). `for…in` iterates an object's enumerable keys as strings, including inherited ones — rarely what you want for arrays."),
        ("How do you stop a `forEach` early?",
         "You can't. Use a `for…of` loop with `break`, or `some`/`every`/`find`, which stop at the first decisive element."),
        ("How do you avoid off-by-one errors?",
         "State the loop invariant (\"`sum` holds items `0..i-1`\"), use half-open ranges consistently, and test the boundaries — empty input, one element, the last index."),
    ],
    "ts_functions": [
        ("Function declaration vs arrow function?",
         "Declarations are hoisted and get their own `this`; arrows aren't hoisted and capture `this` from where they're defined. I use arrows for callbacks and small helpers, declarations for named top-level functions."),
        ("Should you annotate return types?",
         "On exported and public functions, yes — it documents the contract and makes the compiler report a mistake at the function rather than at every caller. For small internal helpers, inference is fine."),
        ("What does a `() => void` callback type promise?",
         "That the caller ignores the result — so a function returning a value is still accepted. That's deliberate: it lets you pass `arr.push` to something expecting `() => void`."),
    ],
    "ts_params": [
        ("Optional parameter vs default parameter?",
         "`x?: T` makes `x` `T | undefined` inside the function. `x = value` makes it `T` inside, with the default used whenever the argument is `undefined`."),
        ("When would you use an options object?",
         "When a function has more than two or three optional settings: call sites become self-describing (`format(v, { width: 8 })`), every option can be optional, and adding one doesn't break callers."),
        ("How is a rest parameter typed?",
         "As an array or tuple: `(...parts: string[])`. Tuple rest types (`...args: [string, number]`) let you type a fixed but variadic signature."),
    ],
    "ts_unions": [
        ("What can you do with a value of type `string | number`?",
         "Only what both members support, until you narrow it. `typeof x === \"string\"` narrows to `string` inside that branch."),
        ("Literal union or `enum`?",
         "A literal union. It's pure type syntax that erases to nothing, needs no import at call sites, and works in strip-only runtimes like Node's — which reject `enum` because it emits code."),
        ("What happens to `\"a\" | string`?",
         "It collapses to `string` — the literal is a subtype and gets absorbed. That's why a \"suggested values but any string allowed\" type needs a trick like `\"a\" | (string & {})`."),
    ],
    "ts_aliases": [
        ("`type` vs `interface`?",
         "For object shapes they're mostly interchangeable. Interfaces can be merged by redeclaring and extended with `extends`; type aliases can name unions, tuples, primitives and mapped or conditional types. I default to `type` and use `interface` for extensible public shapes."),
        ("What is declaration merging?",
         "Two `interface` declarations with the same name combine into one type. Libraries use it so you can add members to their types (module augmentation); type aliases can't do it."),
        ("How do you combine two object types?",
         "`interface B extends A`, or an intersection `A & B`. `extends` reports conflicting members as errors; an intersection turns a conflicting property into `never`."),
    ],
    "ts_narrowing": [
        ("How does TypeScript narrow a union?",
         "Through control-flow analysis: `typeof`, `instanceof`, `in`, equality with literals, truthiness, `Array.isArray` and type predicates all refine the type inside the branch they guard."),
        ("Why can narrowing be lost inside a callback?",
         "The callback may run later, after the variable has changed, so narrowing on a `let` doesn't carry into it. Copy the narrowed value into a `const` first."),
        ("What's the gotcha with `typeof x === \"object\"`?",
         "`typeof null` is `\"object\"`, so that check leaves `null` in the type. Pair it with `x !== null`."),
    ],
    "ts_arrays": [
        ("`T[]` or `Array<T>`?",
         "Identical types. `T[]` is the usual spelling; `readonly T[]` (or `ReadonlyArray<T>`) is the read-only form that removes the mutating methods."),
        ("What is a tuple, and when would you use one?",
         "A fixed-length array where each position has its own type, like `[string, number]`. Good for returning a small fixed group — `[min, max]` — though for more than two or three values a named object reads better."),
        ("What does `noUncheckedIndexedAccess` change?",
         "Every index read becomes `T | undefined`, so an out-of-range access has to be handled instead of silently producing `undefined` typed as `T`."),
    ],
    "ts_array_methods": [
        ("Which array methods mutate?",
         "`push`, `pop`, `shift`, `unshift`, `splice`, `sort`, `reverse`, `fill`, `copyWithin`. ES2023 added copying versions: `toSorted`, `toReversed`, `toSpliced`, `with`."),
        ("Why does `[10, 9, 1].sort()` give `[1, 10, 9]`?",
         "The default comparator converts elements to strings. For numbers, pass `(a, b) => a - b`."),
        ("`map` + `filter` or `reduce`?",
         "`map`/`filter` when they express the intent — they're easier to read and type. `reduce` when you're genuinely folding to one value (a sum, a lookup map). Always give `reduce` an initial value, or an empty array throws."),
    ],
    "ts_objects": [
        ("How deep does a spread copy?",
         "One level. Nested objects are shared between the original and the copy — use `structuredClone` or copy each nested level you change."),
        ("Why does `Object.keys` return `string[]` instead of `(keyof T)[]`?",
         "Structural typing: an object may carry more keys than its type mentions, so claiming `keyof T` would be unsound."),
        ("Optional property vs `| undefined`?",
         "`{ x?: number }` lets the key be missing; `{ x: number | undefined }` requires the key but allows the value `undefined`. With `exactOptionalPropertyTypes` the difference is enforced."),
    ],
    "ts_maps_sets": [
        ("When do you use a `Map` instead of an object?",
         "When keys aren't plain strings, when you add and remove keys dynamically, or when you need the size and insertion order. Maps also have no inherited keys like `toString` to trip over."),
        ("Why is `map.get(k)` typed `V | undefined` even after `map.has(k)`?",
         "The compiler doesn't link the two calls. Call `get` once and check its result for `undefined`."),
        ("What's the average cost of `set.has(x)`?",
         "O(1) — it's a hash table. That's why building a `Set` first turns an O(n·m) membership filter into O(n + m)."),
    ],
    "ts_enums": [
        ("Why do many teams avoid `enum`?",
         "It emits a runtime object (numeric enums with reverse mappings), needs a TypeScript-aware compiler, and numeric enums accept surprising numbers. A literal union or an `as const` object gives the same safety with zero runtime cost."),
        ("What is a `const enum`?",
         "An enum whose uses are inlined at compile time, leaving no object. It breaks under `isolatedModules` tools, so it's discouraged in most modern setups."),
        ("How do you get enum-like values from an `as const` object?",
         "`const Color = { Red: \"red\", Blue: \"blue\" } as const; type Color = (typeof Color)[keyof typeof Color];` — a value namespace and a type with the same name."),
    ],
    "ts_generics": [
        ("What problem do generics solve?",
         "Reusing code across types without losing precision. `first<T>(xs: T[]): T | undefined` returns a `number` for a `number[]` — `any` would lose that."),
        ("When are generics the wrong tool?",
         "When a type parameter appears only once and links nothing — `<T>(x: T): void` is just `(x: unknown): void`. A generic earns its place by relating two positions, usually input and output."),
        ("How are type arguments decided?",
         "Usually inferred from the arguments at the call. You pass them explicitly only when nothing at the call site mentions them, like `new Set<string>()`."),
    ],
    "ts_classes": [
        ("`private` vs `#private`?",
         "`private` is checked only by the compiler — the property is still there at runtime. `#field` is real JavaScript privacy, enforced by the engine."),
        ("When would you not use a class?",
         "When there's no state to protect — plain functions and data are simpler. Classes earn their place when an invariant has to hold across methods, like a balance that must never go negative."),
        ("Are classes nominal in TypeScript?",
         "Mostly no: they compare structurally, so an object literal with the same public members fits. Private and protected members make them nominal, because those are compared by declaration."),
    ],
    "ts_this_accessors": [
        ("Why does `const f = obj.method; f()` often break?",
         "Detaching the method loses `this`, so inside it `this` is `undefined`. Bind it, wrap it in an arrow, or define the method as an arrow-function field."),
        ("What does a getter give you over a public field?",
         "A computed or read-only view: callers read `account.balance` like a field, while the class controls how it's derived and prevents writes."),
        ("How do you type `this` explicitly?",
         "With a fake first parameter: `function handler(this: Button, e: Event)`. It's erased at runtime and makes the compiler check the call context."),
    ],
    "ts_modules": [
        ("Named exports or default exports?",
         "Named, mostly: the name is fixed at the import site, which makes renames and search reliable and editors auto-import them well. Default exports can be imported under any name, which drifts."),
        ("What is `import type` for?",
         "Importing something only as a type, so the import is erased completely. It matters with `verbatimModuleSyntax` and strip-only tools, which keep every non-type import."),
        ("Why are circular imports dangerous?",
         "One module can run before the other has finished initialising its exports, so a value you import is `undefined` (or in its temporal dead zone) when first used."),
    ],
    "ts_nullish": [
        ("What does `strictNullChecks` do?",
         "Removes `null` and `undefined` from every type unless you add them explicitly. `string` stops meaning \"maybe a string\", which catches a whole class of runtime `undefined` errors."),
        ("When is the non-null assertion `!` acceptable?",
         "When you've just proved non-null in a way the compiler can't follow — for example `map.get(k)!` right after checking `map.has(k)`. Otherwise it's a lie that moves the crash elsewhere."),
        ("`null` or `undefined` for \"no value\"?",
         "Pick one convention per concept. A common one: `undefined` for \"absent/not provided\" (optional properties and parameters already use it), `null` for \"deliberately empty\"."),
    ],
    "ts_errors": [
        ("What is the type of the variable in `catch (e)`?",
         "`unknown` under `strict` (`useUnknownInCatchVariables`), because anything can be thrown. Narrow with `e instanceof Error` before reading `e.message`."),
        ("Why throw `Error` objects instead of strings?",
         "An `Error` carries a stack trace and works with `instanceof`, `cause` and tooling. A thrown string has none of that."),
        ("What does `finally` guarantee?",
         "It runs whether the `try` returns, throws or completes — the place for cleanup. Avoid returning from it: that overrides the `try`'s return or swallows its exception."),
    ],
    "ts_utility_types": [
        ("Name the utility types you use most and what they do.",
         "`Partial` (all optional — patches), `Pick`/`Omit` (subset of keys — views), `Record` (keyed map), `ReturnType`/`Parameters` (derive from functions), `Readonly`, `Required`, `NonNullable`, `Awaited`."),
        ("`Pick` and `Omit` — any asymmetry?",
         "`Pick`'s keys are constrained to `keyof T`, so a typo is an error. `Omit` accepts any key, so a typo silently omits nothing."),
        ("Does `Omit<User, \"password\">` remove the password at runtime?",
         "No — types are erased. If you spread the user into the result, the password is still there. You have to actually leave it out of the object you build."),
    ],
    "ts_async": [
        ("What does an `async` function return?",
         "Always a `Promise` — returning `5` gives `Promise<number>`, and throwing gives a rejected promise instead of an exception at the call site."),
        ("How do you run independent async work in parallel?",
         "Start them all, then await together: `await Promise.all(ids.map(load))`. Awaiting inside a loop runs them one after another."),
        ("What happens to an unhandled rejection?",
         "In modern Node it crashes the process by default. Always `await` a promise or attach `.catch`."),
    ],
    "ts_destructuring": [
        ("When does a destructuring default apply?",
         "Only when the value is `undefined` — not `null`. `const { a = 1 } = { a: null }` leaves `a` as `null`."),
        ("What does `const { a, ...rest } = obj` give `rest`?",
         "A new object with every own enumerable property except `a`, and TypeScript types it precisely as `Omit`-like."),
        ("How do you rename while destructuring?",
         "`const { name: userName } = user` — the colon renames; `{ name: userName = \"anon\" }` also adds a default."),
    ],
    "ts_assertions": [
        ("What does `as` do at runtime?",
         "Nothing. It's a claim to the compiler, not a conversion. If the claim is wrong the error surfaces later, far from the cast."),
        ("When is `as` reasonable?",
         "When you know more than the compiler and can't express it — a DOM element type, a value you've just validated, test fixtures. Prefer narrowing or `satisfies` where they work."),
        ("What is `x as unknown as T` for?",
         "Forcing an assertion between types that don't overlap enough for a direct `as`. Its ugliness is a feature: it flags a genuinely unsafe claim."),
    ],
    "ts_compose": [
        ("`extends` or intersection `&`?",
         "`extends` when building a named hierarchy of object shapes — conflicts are reported. `&` when combining types ad hoc or in generics — but conflicting properties silently become `never`."),
        ("What is composition over inheritance?",
         "Building behaviour by combining small functions and objects rather than extending classes. It avoids deep hierarchies where a change to a base class ripples everywhere."),
        ("What is `{ a: string } & { a: number }`?",
         "An object type whose `a` is `string & number`, which is `never` — no value can satisfy it. It's a common sign of an accidental conflict."),
    ],
    "ts_json": [
        ("What type does `JSON.parse` return?",
         "`any` — the compiler can't see inside the string. Treat the result as `unknown` and validate it before use."),
        ("What does `JSON.stringify` lose?",
         "`undefined` values, functions and symbols in objects; `NaN`/`Infinity` become `null`; `Date`s become strings; `Map`/`Set` become `{}`."),
        ("How do you validate parsed JSON?",
         "Parse into `unknown`, then check the shape with a type predicate or a schema validator, which narrows it to a real type. That keeps untrusted data from leaking through as `any`."),
    ],
    "ts_immutability": [
        ("`readonly` vs `Object.freeze`?",
         "`readonly` is compile-time only and costs nothing at runtime. `Object.freeze` is enforced at runtime but shallow, and a write to a frozen property fails silently outside strict mode."),
        ("Is `Readonly<T>` deep?",
         "No, one level. A `DeepReadonly` recursive mapped type covers nested objects."),
        ("Why prefer immutable updates?",
         "No aliasing surprises, easy undo and change detection (compare references), and functions that are safe to call from anywhere. Structural sharing keeps the copying cheap."),
    ],
    "ts_number_math": [
        ("Why is `0.1 + 0.2 !== 0.3`?",
         "Binary floating point can't represent 0.1 exactly, so the sum is `0.30000000000000004`. Compare with a tolerance, or work in integers (cents) when exactness matters."),
        ("What's `Number.MAX_SAFE_INTEGER` and why does it matter?",
         "2^53 − 1 — above it, integers can't all be represented, so arithmetic silently loses precision. Use `bigint` for IDs or counters that can exceed it."),
        ("`Math.floor` vs `Math.trunc`?",
         "They differ for negatives: `Math.floor(-2.5)` is `-3` (towards −∞), `Math.trunc(-2.5)` is `-2` (towards zero)."),
    ],
    "ts_string_methods": [
        ("`replace` vs `replaceAll`?",
         "With a string pattern, `replace` changes only the first match. Use `replaceAll`, or a regex with the `g` flag, to change every occurrence."),
        ("How do you split on any whitespace?",
         "`s.trim().split(/\\s+/)` — splitting on a single space keeps empty strings for runs of spaces."),
        ("How do you compare strings for sorting?",
         "`a.localeCompare(b)` — it respects the locale and case properly. `<` compares UTF-16 code units, so `\"Z\" < \"a\"`."),
    ],
    "ts_higher_order": [
        ("What is a higher-order function? Give an example you use.",
         "A function that takes or returns a function — `map`, `filter`, a `debounce` wrapper, a `memoize` helper. They let you separate the *what* (the callback) from the *how* (the iteration)."),
        ("How do you type a `pipe` helper?",
         "Overloads or variadic generics that link each function's input to the previous output. A simple version constrains every step to the same type: `pipe<T>(...fns: Array<(x: T) => T>)`."),
        ("What's currying, and when is it useful?",
         "Turning `f(a, b)` into `f(a)(b)`. It's handy for pre-configuring a function (`const isOver = (min: number) => (x: number) => x > min`) to pass to `filter`."),
    ],
    "ts_type_predicates": [
        ("What is a user-defined type guard?",
         "A function returning `x is T`. When it returns `true` the caller's variable narrows to `T` — the way to teach the compiler a check it can't infer on its own."),
        ("What's the risk with type predicates?",
         "The compiler trusts them completely. A predicate that returns `true` too often lets the wrong type through, and the error appears far away."),
        ("What's an assertion function?",
         "`function assert(x: unknown): asserts x is T` — it narrows by returning at all, and must throw when the check fails. Good at the top of a function for preconditions."),
    ],
    "ts_discriminated_unions": [
        ("What is a discriminated union?",
         "A union whose members share a literal-typed tag, like `kind: \"circle\" | \"square\"`. Switching on the tag narrows to exactly one member, with its own fields available."),
        ("How do you make a `switch` exhaustive?",
         "Assign the value to `never` in the `default` branch. When someone adds a member, the compiler reports every switch that doesn't handle it yet."),
        ("Why is it better than one type with optional fields?",
         "Optional fields allow impossible combinations (loading *and* errored with data). A tagged union makes illegal states unrepresentable, and each state only has the data it can have."),
    ],
    "ts_structural_typing": [
        ("What is structural typing?",
         "Compatibility by shape rather than by name: anything with the required members fits, whatever it was declared as. It's how JavaScript objects are actually used."),
        ("Why does an object literal with an extra property fail, but the same object in a variable passes?",
         "Excess-property checking applies only to fresh literals, where an extra key is almost certainly a typo. A variable may legitimately be a wider type."),
        ("Where is TypeScript's type system deliberately unsound?",
         "Array covariance (a `Dog[]` used as `Animal[]` can have a cat pushed into it), method parameter bivariance, `any`, and assertions. Knowing these tells you where tests still matter."),
    ],
    "ts_satisfies": [
        ("`: T` vs `satisfies T`?",
         "`: T` checks and then widens the variable to `T`. `satisfies T` checks but keeps the expression's own, narrower type — you get validation *and* literal keys."),
        ("When do you reach for `satisfies`?",
         "Config and lookup tables: `const routes = { … } satisfies Record<string, Route>` catches a bad entry while `keyof typeof routes` stays the exact union of names."),
        ("Does `satisfies` validate data at runtime?",
         "No — it's compile-time only, like every type. Data from outside still needs a runtime check."),
    ],
    "ts_branded_types": [
        ("What is a branded type?",
         "A primitive intersected with a unique tag, like `number & { readonly __brand: \"Cents\" }`. It stops a plain number — or a `UserId` — being passed where `Cents` is expected."),
        ("How should branded values be created?",
         "Through one validating constructor that returns the branded type (or `null`/throws). That function is the only place the cast appears, so every branded value has passed the check."),
        ("What does a brand cost at runtime?",
         "Nothing — it's erased. The value is still an ordinary number or string."),
    ],
    "ts_generic_constraints": [
        ("What does `K extends keyof T` give you?",
         "A key that must exist on `T`, which makes `obj[key]` typed as `T[K]` — the exact value type for that key."),
        ("Why constrain with `<T extends { length: number }>` rather than taking `{ length: number }` directly?",
         "The generic keeps the caller's own type: `longest(a, b)` returns a `string` for strings and an array for arrays. The plain parameter would return `{ length: number }`."),
        ("What does \"'T' could be instantiated with an arbitrary type\" mean?",
         "You returned a concrete type where the caller chooses `T`. A generic body has to work for every `T`, not just the one you were thinking of."),
    ],
    "ts_keyof_indexed": [
        ("What do `keyof`, `typeof` and indexed access give you together?",
         "A way to derive types from one source of truth: `keyof typeof config` for its keys, `(typeof config)[K]` for a value type, `T[number]` for an array's elements."),
        ("Type-position `typeof` vs runtime `typeof`?",
         "In a type (`typeof defaults`) it takes a variable's static type. In an expression it returns a runtime string like `\"number\"`."),
        ("How do you derive a union from a list of values?",
         "`const LEVELS = [\"debug\", \"info\"] as const; type Level = (typeof LEVELS)[number];` — without `as const` it would just be `string`."),
    ],
    "ts_mapped_types": [
        ("What is a mapped type?",
         "A type built by iterating keys: `{ [K in keyof T]: … }`. `Partial`, `Readonly`, `Pick` and `Record` are all mapped types."),
        ("How do you rename or filter keys?",
         "With an `as` clause: `` [K in keyof T as `get${Capitalize<string & K>}`] `` renames; mapping a key to `never` drops it."),
        ("What's a homomorphic mapped type?",
         "One that maps over `keyof T` directly. It preserves `readonly` and `?` modifiers and maps arrays and tuples element-wise."),
    ],
    "ts_conditional_types": [
        ("What is a conditional type?",
         "`T extends U ? X : Y` — a type-level if/else. With `infer` it can extract parts of a type, like a function's return type or a promise's value."),
        ("What is distribution?",
         "When the checked type is a naked type parameter, a union input is split and each member checked separately — that's how `Exclude` works. Wrap in tuples (`[T] extends [U]`) to stop it."),
        ("How would you implement `ReturnType`?",
         "`type MyReturn<F> = F extends (...args: any[]) => infer R ? R : never;`"),
    ],
    "ts_template_literal_types": [
        ("What are template literal types used for?",
         "Deriving string types: event names like `` `${Entity}:${Action}` ``, getter names, CSS units, route strings. They make the compiler check string conventions."),
        ("What's the cost of `` `${A}-${B}` `` with big unions?",
         "It produces every combination — the cartesian product — which can explode the number of members and slow the compiler."),
        ("How do you parse a string type?",
         "Match it with `infer` inside a template pattern — `` S extends `${infer Head}/${infer Rest}` ? … : … `` — and recurse on the rest."),
    ],
    "ts_type_level": [
        ("When is type-level programming worth it?",
         "When it removes a real class of bugs at the boundary everyone uses — typed routes, typed event names, a typed `get(obj, \"a.b\")`. Not for cleverness in application code."),
        ("What does TS2589 mean?",
         "\"Type instantiation is excessively deep and possibly infinite\" — a recursive type hit the compiler's depth limit. Simplify it, add a depth counter, or make the recursion tail-recursive."),
        ("How do you test a type?",
         "With compile-time assertions — `type _ = Expect<Equal<Actual, Expected>>` — and `// @ts-expect-error` lines for inputs that must be rejected. The test passes if the file type-checks."),
    ],
    "ts_iterators": [
        ("What makes something iterable?",
         "A `[Symbol.iterator]()` method returning an iterator — an object with `next()` that returns `{ value, done }`. Arrays, strings, Maps and Sets are built-in iterables."),
        ("Why use a generator?",
         "It produces values lazily, one at a time, so you can model infinite or expensive sequences and build pipelines (`take(filter(naturals(), p), 5)`) without materialising arrays."),
        ("Can you iterate a generator twice?",
         "No — a generator object is a one-shot iterator. Call the generator function again for a fresh one."),
    ],
    "ts_error_types": [
        ("Throw, or return a `Result`?",
         "Return a `Result` for expected failures the caller must handle — invalid input, not found. Throw for bugs and truly exceptional situations. A `Result` puts the failure in the type, so it can't be forgotten."),
        ("How do you model a `Result` in TypeScript?",
         "`type Result<T, E> = { ok: true; value: T } | { ok: false; error: E }` — a discriminated union the caller must check before reading `value`."),
        ("What's `Error.cause`?",
         "An option for chaining errors: `new Error(\"load failed\", { cause: err })` keeps the underlying error attached for logs."),
    ],
    "ts_async_patterns": [
        ("`Promise.all` vs `allSettled` vs `race` vs `any`?",
         "`all` fails fast on the first rejection; `allSettled` waits for everything and reports each outcome; `race` settles with the first to settle either way; `any` resolves with the first success and rejects only if all fail."),
        ("How do you limit concurrency?",
         "A small pool: keep N tasks in flight, start the next as each finishes. Firing thousands of requests with `Promise.all` can overwhelm the target."),
        ("How do you cancel async work?",
         "Pass an `AbortSignal` (from an `AbortController`, or `AbortSignal.timeout(ms)`) and have the work check it or pass it to APIs like `fetch` that accept one."),
    ],
    "ts_declaration_files": [
        ("What's a `.d.ts` file?",
         "Types without implementation — how TypeScript describes JavaScript code, whether a library you install or your own compiled output."),
        ("How do you type an untyped package?",
         "Write `declare module \"pkg\" { … }` in a `.d.ts` file describing just the exports you use, or install community types from DefinitelyTyped if they exist."),
        ("What does `declare` mean?",
         "\"This exists at runtime, trust me\" — it describes a value without creating it. If nothing actually defines it, you get a `ReferenceError` at runtime."),
    ],
    "ts_ds_generics": [
        ("How would you implement a generic stack?",
         "A class `Stack<T>` wrapping a private `T[]`, with `push(item: T)` and `pop(): T | undefined` — the `undefined` because an empty stack has nothing to give."),
        ("Why is `array.shift()` a problem in a BFS queue?",
         "It's O(n): every remaining element moves. Use a head index into the array, or a ring buffer, to dequeue in O(1)."),
        ("How does a generic priority queue know what \"smaller\" means?",
         "It takes a comparator `(a: T, b: T) => number` in its constructor, rather than constraining `T` — so the same heap orders numbers, tasks by deadline, or anything else."),
    ],
    "ts_tsconfig": [
        ("Which compiler flags do you always turn on?",
         "`strict` (null checks, no implicit any, strict function types and more), plus `noUncheckedIndexedAccess` for honest index reads, and `noImplicitOverride`/`noFallthroughCasesInSwitch` for safety."),
        ("What's the difference between `target` and `lib`?",
         "`target` is which JavaScript syntax the output uses; `lib` is which built-in type declarations exist. Newer methods need a newer `lib` even if the runtime supports them."),
        ("What does `skipLibCheck` do, and is it OK?",
         "It skips type-checking `.d.ts` files. It speeds builds and sidesteps broken third-party types, at the cost of missing errors in declaration files — a common, pragmatic default."),
    ],
}

# Attach to the lessons, and make sure every TypeScript chapter has its three.
_ts_keys = {k for k, c in CONCEPTS.items() if c.get("language") == "typescript"}
_missing = sorted(_ts_keys - set(TS_INTERVIEW))
assert not _missing, f"TypeScript chapters without interview questions: {_missing}"
_unknown = sorted(set(TS_INTERVIEW) - _ts_keys)
assert not _unknown, f"interview questions for unknown chapters: {_unknown}"
for _key, _qas in TS_INTERVIEW.items():
    assert len(_qas) >= 3, f"{_key}: needs at least 3 interview questions"
    _block = "\n\n### In an interview\n" + "\n".join(
        f"\n**{q}**\n\n{a}" for (q, a) in _qas
    )
    LESSONS[_key] = LESSONS.get(_key, "").rstrip("\n") + _block
